<?php if(!empty($pagination)): ?>
	<!-- Постраничная навигация -->
	<? $this->partial('partials/catalogue/pagination', ['pagination' => $pagination]); ?>
	<!-- /Постраничная навигация -->
<?php else:?>
	<div class="paging">
		<div class="info">Показаны все <?=$count;?></div>
	</div>
<?php endif;?>

<!-- Фильтры -->
<?php if(!isset($disableSort)):?>
	<?php $this->partial('partials/catalogue/filters');?>
<?php endif;?>
<!-- /Фильтры -->

<!-- Выдача товаров -->
<div class="CatalogueItems insert-filters" id="productsShow">

	<!-- Сайдбар ajax -->
	<div class="tags-filter Shadow" id="filterSidebar"></div>
	<!-- /Сайдбар ajax -->

	<!-- Вывод палитры -->
	<?php if(isset($items) && !empty($items)): ?>

		<?php

		// скидки на вещи в магазине исходя из суммы покупок
		if((isset($minicart) && !empty($minicart)) || !empty($shop['discounts']))
		{
			// получаю скидки магазина на вещи

			$shopDiscounts = \Helpers\Catalogue::getMaxDiscount($shop['discounts'], $minicart);
			if(!empty($minicart) && $minicart['count'] > 0)
				$buyes	=	\Helpers\Catalogue::getBasketSizes($basket);
		}
		?>
		<?php foreach($items as $item): ?>
			<?php
				if(isset($item['filter_size']) && $item['filter_size'])
				{
					$arraySize = explode(',',$item['filter_size']);
					uksort($arraySize, "\Helpers\Catalogue::itemCompareSize");
				}
				$img = array_values(json_decode($item['preview'], true)); // images json decode
				if(!empty($img)) {
					$img = $img[0];
					$this->partial('partials/catalogue/item_short');        // render small product
				}
			?>
		<?php endforeach; ?>
	<?php else: ?>
		<h2>Ничего не найдено</h2>
		<h4>Попробуйте изменить условия поиска</h4>
	<?php endif; ?>
	<!-- /Вывод палитры -->

</div>
<!-- /Выдача товаров -->
<div style="clear: both;"></div>
<?php if(!empty($pagination)): ?>
	<!-- Постраничная навигация -->
	<? $this->partial('partials/catalogue/pagination', ['pagination' => $pagination]); ?>
	<!-- /Постраничная навигация -->
<?php else:?>
	<div class="paging">
		<div class="info">Показаны все <?=$count;?></div>
	</div>
<?php endif;?>
<script>
	$(function() {

		var sideBar 	=	document.getElementById('filterSidebar');
		var renderItems =	document.getElementById('renderItems');


		<?php if(isset($isFavorite)): ?>
		$('img.like_on').on('click', function(e) {
			e.preventDefault();
			$(this).closest('div.item').fadeOut();
		});
		<?php endif;?>


		var exludeSidebar = [
			'favorites',
			'brands'
			],
			currentPath	=	window.location.pathname.split('/').slice(-1)[0];

		if(!$.inArray(currentPath, exludeSidebar))
			$(sideBar).hide();
		else
		{
			// показую сайдбар
			$.getJSON("/json/tags", function(data) {
				if(data.response.length)
					$(sideBar).html(data.response);
			});
		}

		// обработка ajax для перерисовки выдачи

		$('a.isAjax').on('click', function(e) {

			e.preventDefault();

			global.showStatus('common.loading');

			var url =	window.location.pathname +$(this).attr('href');

			$.getJSON(url, function(data) {
				if(data.response.length)
					$(renderItems).html(data.response);
					window.history.pushState("","", url);
				global.hideStatus('common.loading');

				$('html, body').animate({scrollTop:$('#renderItems').position().top+(210)}, 'slow');
			});
		});
	});
</script>
