<div class="item">
	<form autocomplete="off" data-send="<?= $item['id'] ?>">
	<div style="z-index: 2; position: relative;">
		<div style="display: none;" id="sizes_<?= $item['id'] ?>" class="sizes_win">
			<!-- Форма покупки -->
				<input type="hidden" name="product_id" value="<?= $item['id'] ?>">
				<input type="hidden" name="mode" value="small-cart">
				<input type="hidden" name="action" value="item_added">
				<?php if(isset($arraySize) && $arraySize != '' && empty($arraySize[0])): ?>
				<table>
					<tbody>
					<tr>
						<td id="leftPart" style="padding: 0px 10px 0px 0px; height: 320px;">
							<div style="height:275px;">
								<a href="<?=$this->url->get(ltrim($path, '/').'/'.$item['articul']);?>">
									<img class="preview" src="http://img<?= rand(0, 9) ?>.z95.ru/f/p/225x275/catalogue/<?= $item['id'] ?>/<?=$img?>">
								</a>
							</div>
							<div class="info">
								<a href="<?=$this->url->get(ltrim($path, '/').'/'.$item['articul']);?>">
									<b><?= $item['brand_name'] ?></b>
									<?= $item['name'] ?> <span class="articul"><?= $item['articul'] ?></span>
								</a>
							</div>
						</td>
						<td id="rightPart" style="padding: 0px 10px 0px 0px;">
							<input type="hidden" name="quantity" value="multiple">
							<img onclick="$('#sizes_<?= $item['id'] ?>').fadeOut();" class="close_png" src="/assets/<?php echo $shop['code']; ?>/images/d-t.gif">
								<div class="warning hidden" id="warning" onclick="$(this).fadeOut();"></div>
								<span>Выберите размер:</span>
								<br clear="all">
								<div class="small-sizes">
										<?php foreach($arraySize as $size => $count): ?>
										<?php $check = (\Helpers\Cart::isSizeHere($minicart, $item['id'], $size) || $count < 1) ? ['l' => 'title="'.$viewTranslate["SIZE_EXIST"].'"', 'd' => 'disabled="true" checked="true"'] : ['l' => '', 'd' => '']; ?>
										<div class="size">
											<label <?=$check['l'];?>>
												<input <?=$check['d'];?> class="s<?=$item['id'];?>" name="size[<?=$size; ?>]" type="checkbox" value="1" onchange="Cart.check(<?=$item['id'];?>);"><br>
												<?=$size;?>
											</label>
										</div>
									<?php endforeach; ?>
									<br clear="all"><br>

									<div class="left">
										<label>
											<input type="checkbox" class="s<?=$item['id'];?>" name="size[?]" onchange="Cart.check(<?=$item['id'];?>);" value="1" <?=(\Helpers\Cart::isSizeHere($minicart, $item['id'], '?')) ? ' disabled="true" checked="true"' : ''; ?>>
											Не уверен в размере — <br>хочу обсудить с менеджером</label>
									</div>
								</div>
							<br clear="all">
							<div class="add-button">
								<button onclick="Cart.addBefore($(this).closest('form')); return false;" id="s<?=$item['id'];?>" disabled="disabled">
									<?=$viewTranslate["ADD_TO_CART"];?>
								</button>
							</div>
						</td>
					</tr>
					</tbody>
				</table>
				<?php else: ?>
					<?php $check = (\Helpers\Cart::isSizeHere($minicart, $item['id'], $size)) ? ['l' => 'title="'.$viewTranslate["SIZE_EXIST"].'"', 'd' => 'disabled="true" checked="true"'] : ['l' => '', 'd' => '']; ?>
					<input type="hidden" name="quantity" value="single">
					<input type="hidden" <?=$check['d'];?> name="size[0]" id="s<?=$item['id'];?>" type="checkbox" value="1">
				<?php endif;?>
			<!-- /Форма покупки -->
		</div>
	</div>

	<div class="photo_hover" onmouseover="catalogue.startSlideShow('slide_show_<?= $item['id'] ?>');"
		 onmouseout="catalogue.stopSlideShow('slide_show_<?= $item['id'] ?>');">
		<a href="<?=$this->url->get(ltrim($path, '/').'/'.$item['articul']);?>">
			<img src="/assets/<?=$shop['code'];?>/images/d-t.gif" style="width:225px; height:275px;">
		</a>
	</div>

	<div style="z-index: 0; position: relative; width:225px; height:275px;" id="slide_show_<?= $item['id'] ?>">
		<?php if(isset($item['is_new']) && $item['is_new'] == 1): ?>
			<img src="/assets/<?=$shop['code'];?>/images/new_flag.png" class="new_flag">
		<?php endif; ?>
		<ul>
			<li class="show">
				<a href="<?=$this->url->get(ltrim($path, '/').'/'.$item['articul']);?>">
					<img class="preview" src="http://img<?= rand(0, 9) ?>.z95.ru/f/p/225x275/catalogue/<?= $item['id'] ?>/<?=$img?>">
				</a>
			</li>
			<li class="">
				<a href="<?=$this->url->get(ltrim($path, '/').'/'.$item['articul']);?>">
					<img class="preview add" src="http://img<?= rand(0, 9) ?>.z95.ru/f/p/225x275/catalogue/<?= $item['id'] ?>/<?= next(json_decode($item['preview'], true)) ?>">
				</a>
			</li>
		</ul>
	</div>

	<div class="info">
		<a href="<?=$this->url->get(ltrim($path, '/').'/'.$item['articul']);?>">
			<b><?= (isset($item['brand_name'])) ? $item['brand_name'] : ''?></b>
			<?= $item['name'] ?> <span class="articul"><?= $item['articul'] ?></span>
		</a>
		<?php if(isset($arraySize) && (!isset($arraySize[0]))): ?>
		<div class="sizes">
			<span style="color:gray">Размеры:</span> <span class="size-letters">
				<?php echo implode('/', array_keys($arraySize)); ?>
			</span>
		</div>
		<?php endif; ?>

		<div class="price">
			<?php if($item['discount'] == $item['price']): ?>
			<div style="white-space: nowrap">
				&nbsp; <?=number_format($item['discount'], 0, '.', ' '); ?> &nbsp;
				<span class="sign"><?=$shop['currency_symbol'];?></span>
			</div>
			<?php else :?>
			<div>
				<s style="white-space: nowrap"><?=number_format($item['price'], 0, '.', ' ');?></s>&nbsp;<?=number_format($item['discount'], 0, '.', ' ');?>&nbsp;
				<span class="sign"><?=$shop['currency_symbol'];?></span>
			</div>
			<?endif;?>
			<!-- Скидки магазина -->
			<?php if(isset($shopDiscounts)): // расчет цены исходя из скидок магазина ?>
				<?php if(!isset($shopDiscounts['next']) && isset($shopDiscounts['current'])): ?>
					<div class="discount-sign">
						<b>***</b><i><?=number_format($item['discount'] - ($item['discount'] * $shopDiscounts['current']) / 100, 0, '.', ' ');?></i>
					</div>
					<div class="discount-detail">
						<?printf($viewTranslate['DISCOUNT_SHOP_MAX'], $shopDiscounts['current']);?>
					</div>
				<?php elseif(isset($shopDiscounts['next']) && $shopDiscounts['next'] > 0): ?>
					<div class="discount-sign"><b>***</b><i><?=number_format($item['discount'] - ($item['discount'] * $shopDiscounts['next']) / 100, 0, '.', ' ');?></i></div>
					<div class="discount-detail">
						<?php if($shopDiscounts['type'] == 'count'): ?>
							<?printf($viewTranslate['DISCOUNT_SHOP_COUNT'], $shopDiscounts['next'], $shopDiscounts['board'][$shopDiscounts['next']]);?>
						<?php else: ?>
							<?printf($viewTranslate['DISCOUNT_SHOP_SUM'], $shopDiscounts['next'], $shopDiscounts['board'][$shopDiscounts['next']], $shop['currency_symbol']);?>
						<?php endif; ?>
					</div>
				<?php endif; ?>
			<?php endif;?>
			<!-- / Скидки магазина -->

			<!-- Корзина -->
			<?php $bCount = \Helpers\Cart::countBoughtSizes($minicart, $item['id']); ?>
			<?php if(isset($arraySize[0]) && $arraySize[0]	===	0):?>
				<div id="sizes_button_<?= $item['id'] ?>" class="close <?=($bCount > 0) ? ' on' : '';?>">
					<?=($bCount > 0) ? $bCount : '&nbsp;';?>
				</div>
			<?php else: ?>
			<?php if(!empty($arraySize) && (empty($arraySize[0]))):?>
			<div id="sizes_button_<?= $item['id'] ?>" class="sizes-button<?=($bCount > 0) ? ' on' : '';?>"
				onclick="basket.beforeAddToBasket('sizes_<?= $item['id'] ?>');" rel="<?=$item['id'];?>">
				<?=($bCount > 0) ? $bCount : '&nbsp;';?>
			</div>
			<?php else: ?>
				<div class="sizes-button<?=($bCount > 0) ? ' on' : '';?>" onclick="Cart.addBefore($(this).closest('form'));" rel="<?=$item['id'];?>"><?=($bCount > 0) ? $bCount : '&nbsp;';?></div>
			<?php endif;?>
			<?php endif;?>

			<!-- /Корзина -->
			<img alt="Понравилось" id="fav_icon_<?= $item['id'] ?>"
				 onclick="catalogue.addFavorites(<?= $item['id'] ?>, this)" src="/assets/<?=$shop['code'];?>/images/d-t.gif"
				 class="<?=(isset($favorites[$item['id']])) ? 'like_on' : 'like_off' ?>">
		</div>
	</div>
	</form>
</div>