<?php if(!isset($item)): ?>
	<div id="CATALOGUE_SEARCH_RESULT">
		<h1>Результат поиска: <span style="color: #A0A0A0;"><b></b></span></h1>
		<p>
			По вашему запросу ничего не нашли.
			Попробуйте <a onclick="catalogue.clear_search(); $('#CATALOGUE_SEARCH').val(''); return false;" href="#">очистить</a>
			или <a onclick="$('#CATALOGUE_SEARCH')[0].focus(); return false;" href="#">изменить</a> условия поиска
		</p>
	</div>
<?php return; endif; ?>

<div class="go-container prev" style="margin-left: 175px; display: block;" title="Предыдущая фотография">
	<div class="button"></div>
</div>
<div class="go-container next" style="margin-right: 175px; display: block;" title="Следующая фотография">
	<div class="button"></div>
</div>
<div class="column main-column">
<div class="ITEMS_LIST">
	<div id="CATALOGUE_SEARCH_RESULT">
	</div>
</div>
<table class="catalogue-item-details">
	<tbody>
	<tr>
		<td>
			<div style="position:relative;">
				<div title="Показать предыдущую/следующую картинку" id="gallery" style="height: 700px;">
					<div id="slides" style="width: 2500px;">
						<?php if($item['images'] !== null) { ?>
							<?php foreach($item['images'] as $key => $image) { ?>
								<div class="slide" style="width: 500px;">
									<img src="http://img<?php echo rand(0,9); ?>.z95.ru/f/p/600x700/catalogue/<?php echo $item['product_id']; ?>/<?php echo $image; ?>" id="<?php echo($key == 0) ?'img_main' :'' ?>" style="width: 500px;">
								</div>
							<?php } ?>
						<?php } ?>
					</div>
					<img onclick="catalogue.showBigPhoto(<?php echo $item['product_id']; ?>);" title="ZOOM-ZOOM!" alt="ZOOM-ZOOM!" class="zoom" id="zz_button" src="/assets/<?=$shop['code'];?>/images/megacon/zoom.png">
				</div>
			</div>
			<!-- Measured sizes -->
			<?php $this->partial('partials/catalogue/measured_sizes'); ?>
			<!-- //Measured sizes -->
		</td>
		<td style="padding:0 10px;">
			<div onclick="catalogue.hideBigPhoto();" id="bphoto_overlay"></div>
			<div id="bphoto_div">
				<img style="z-index: 1100;" onclick="catalogue.hideBigPhoto()" class="close_png" src="/assets/<?=$shop['code'];?>/images/d-t.gif">
				<div style="position:absolute; background: #fff;padding:20px;z-index: 1002;">
					<h1><?php echo $item['product_name']; ?> <?php echo $item['brand']; ?></h1>
				</div>
				<div style="position:absolute; right:0px; background: #fff;padding:20px;z-index: 1002;">
					<div id="BIG_PREVIEW">
						<?php if($item['images'] !== null) { ?>
							<?php foreach($item['images'] as $key => $image) { ?>
								<div id="/f/catalogue/<?php echo $item['product_id']; ?>/<?php echo $image; ?>" class="<?php echo ($key == 0) ? 'selected' : ''; ?>"><img src="http://img1.z95.ru/f/p/60x60/catalogue/<?php echo $item['product_id']; ?>/<?php echo $image; ?>"></div>
							<?php } ?>
						<?php } ?>
					</div>
				</div>
				<div id="gallery_big">
					<div id="big_slides" style="width: 0px;">
						<div id="slides">
							<?php if($item['images'] !== null) { ?>
								<?php foreach($item['images'] as $key => $image) { ?>
									<div class="slide" style="">
										<img src="http://img<?php echo rand(0,9); ?>.z95.ru/f/p/1000x1400/catalogue/<?php echo $item['product_id']; ?>/<?php echo $image; ?>" id="img_big_main">
									</div>
								<?php } ?>
							<?php } ?>
						</div>
					</div>
				</div>
			</div>

			<?php if($item['images'] !== null) { ?>

				<div id="PREVIEW">
					<?php foreach($item['images'] as $key => $image) { ?>
						<span id="/f/catalogue/<?php echo $item['product_id']; ?>/<?php echo $image; ?>" class="<?php echo ($key == 0) ? 'selected' : ''; ?>"><img src="http://img<?php echo rand(0,9); ?>.z95.ru/f/p/g/60x60/catalogue/<?php echo $item['product_id']; ?>/<?php echo $image; ?>"></span>
					<?php } ?>
				</div>
				<span onclick="catalogue.showBigPhoto(60247);" class="zoom-button">Увеличить фотографию</span>

			<?php } ?>
			<div class="item_info">
			</div>

			<!-- Цены -->
			<div class="prices">
				<div class="price">
					Цена:<br>
					<span class="price">
						<?php if($item['discount'] !== null || !empty($item['discount'])): ?>
							<s><?=number_format($item['price'], 0, '.', ' '); ?></s>
							<?=number_format($item['discount'], 0, '.', ' '); ?>
						<?php else: ?>
							<?=number_format($item['price'], 0, '.', ' '); ?>
						<?php endif; ?>
					</span>
					<?=$shop['currency_symbol'];?>
				</div>
				<?php if(isset($minicart['meta']) && ($minicart['meta']['shop_discounts']['current'] > 0 || (isset($minicart['meta']['shop_discounts']['next']) &&  $minicart['meta']['shop_discounts']['next'] > 0))): // расчет цены исходя из скидок магазина ?>
					<?php if(!isset($minicart['meta']['shop_discounts']['next'])): ?>
						<div class="price discount_price">
							<?printf($viewTranslate['ITEM_DISCOUNT_MAX'], $minicart['meta']['shop_discounts']['current']);?>
						</div>
					<?php else: ?>
						<div class="price discount_price">
							<?php if($minicart['meta']['shop_discounts']['type'] == 'count'): ?>
								<?printf($viewTranslate['ITEM_DISCOUNT_COUNT'], $minicart['meta']['shop_discounts']['next'], $minicart['meta']['shop_discounts']['board'][$minicart['meta']['shop_discounts']['next']]);?>
							<?php else: ?>
								<?printf($viewTranslate['ITEM_DISCOUNT_SUM'], $minicart['meta']['shop_discounts']['next'], $minicart['meta']['shop_discounts']['board'][$minicart['meta']['shop_discounts']['next']], $shop['currency_symbol']);?>
							<?php endif; ?>
							<span class="price"><?=round($item['discount'] - ($item['discount'] * $minicart['meta']['shop_discounts']['next']) / 100);?></span> <?=$shop['currency_symbol'];?>
						</div>
					<?php endif; ?>
				<?php endif;?>
			</div>
			<!-- /Цены -->

			<?php if (isset($item['tags'])): ?>
				<?php if (isset($item['tags']['made_in']) && $item['tags']['made_in'] != 'Китай'): ?>
					<div class="tags">
						<label><?php echo 'Производство'; ?>: </label> <?php echo $item['tags']['made_in'] ?>
					</div>
				<?php endif; ?>
				<?php if (isset($item['tags']['material'])): ?>
					<div class="tags">
						<label><?php echo 'Материал'; ?>: </label>
						<?php
							$material = array_shift($item['tags']['material']);
							if (count($material) > 0) {
								foreach ($material as $materia => $materia_percent) {
									$m[] = $materia_percent . '% — <i>' . $materia . '</i>';
								}
								echo implode(', ', $m);
							}
						?>
					</div>
				<?php endif; ?>

				<?php if (isset($item['tags']['color'])): ?>
					<div class="tags">
						<label><?php echo 'Цвет'; ?>: </label>
						<?php
							$color = array_shift($item['tags']['color']);
							echo $color;
						?>
					</div>
				<?php endif; ?>
			<?php endif; ?>

			<br clear="all">
			<div class="sizes_win">
				<!-- Добавление в корзину -->
				<?php $this->partial('partials/catalogue/item_add', ['minicart' => $minicart]); ?>
				<!-- /Добавление в корзину  -->
			</div>

			<!-- Сервисы доставки  -->
				<?php $this->partial('partials/catalogue/delivery', ['delivery' => $delivery]); ?>
			<!-- Сервисы доставки  -->

			<!--<button onclick="global.go({url:''});" type="button" class="add-button button" id="add">Все товары <?php echo $item['brand']; ?></button>-->
		</td>
	</tr>
	<!-- Buy together -->
	<?php $this->partial('partials/catalogue/buy_together'); ?>
	<!-- Buy together -->

	</tbody>
</table>
<script type="text/javascript" language="javascript" src="/assets/<?=$shop['code'];?>/js/slider.js"></script>
<script type="text/javascript">
	ss_ready = false;
	$('#img_main').load(function() {
		var w = $(this).width();
		if( w > 600 ){
			if (w/$(document).width()*100 > 45) {
				w = parseInt(w*0.67);
				//alert(w);
				//$(this).width(w);
			}
		}

		if ($(this).width() > $(this).height()) {
			$('#gallery').addClass('horizontal');
		}
		//console.log( $('#gallery').width() );
		//$('#gallery').width($(this).width());
		$(this).width($('#gallery').width());
		$('#gallery > #slides').width($(this).width());
		$('#gallery').height($(this).height());
		$('#gallery > #slides .slide').each(function(i){
			$(this).width($('#img_main').width());
			$(this).find('img').width($('#img_main').width())
		});

		window.ss_ready = ss_init();
	});

	$(window).resize(function() {
		if ($('#img_main')[0].complete) {
			$('#img_main').trigger('load');
			$('#PREVIEW span.selected').trigger('click',[true]);
		}
	});

	$(document).ready(function(){
		if (!ss_ready && $('#img_main')[0].complete) {
			$('#img_main').trigger('load');
		}
		$('#zz_button').show();
	});
</script>

<script type="text/javascript">
	var margin = Math.max(0,parseInt((($(window).width() - $('.page_container').width())*0.5 - $('.go-container').width())*0.5));
	$('.go-container.prev').css({'margin-left':margin}).show().attr({title: 'Предыдущая фотография'}).click(function() {
		$("#gallery").trigger($.Event("click", { pageX: 0 }));});

	$(window).resize(function() {
		var margin = Math.max(0,parseInt((($(window).width() - $('.page_container').width())*0.5 - $('.go-container').width())*0.5));
		$('.go-container.prev').css({'margin-left':margin});
	});

	$('.go-container.next').css({'margin-right':margin}).show().attr({title: 'Следующая фотография'}).click(function() {
		$("#gallery").click();});

	$(window).resize(function() {
		var margin = Math.max(0,parseInt((($(window).width() - $('.page_container').width())*0.5 - $('.go-container').width())*0.5));
		$('.go-container.next').css({'margin-right':margin});
	});
</script>
<span style="color:white">Рейтинг: <?php echo $item['rating']; ?></span>
<style>
	.inner_teaser { display: none; }
</style>
</div>
