<div id="manufacturers_block_left" class="block blockmanufacturer nopadding noborder">
	<h4 class="title_block">
		<a href="" title="Manufacturers">
			Manufacturers
		</a>
	</h4>

	<div class="block_content list-block" style="">
		<ul>
			<li class="first_item">
				<a href="" title="More about Manufacturers logo 10">
					Manufacturers logo 10
				</a>
			</li>
			<li class="item">
				<a href="" title="More about Manufacturers logo 11">
					Manufacturers logo 11
				</a>
			</li>
			<li class="item">
				<a href="" title="More about Manufacturers logo 4">
					Manufacturers logo 4
				</a>
			</li>
			<li class="item">
				<a href="" title="More about Manufacturers logo 6">
					Manufacturers logo 6
				</a>
			</li>
			<li class="item">
				<a href="" title="More about Manufacturers logo 7">
					Manufacturers logo 7
				</a>
			</li>
		</ul>
		<form action="" method="get">
			<div class="form-group selector1">
				<select class="form-control" name="manufacturer_list">
					<option value="">All manufacturers</option>
					<option value="">Manufacturers logo 10</option>
					<option value="">Manufacturers logo 11</option>
					<option value="">Manufacturers logo 4</option>
					<option value="">Manufacturers logo 6</option>
					<option value="">Manufacturers logo 7</option>
					<option value="">Manufacturers logo 7</option>
					<option value="">Manufacturers logo 9</option>
				</select>
			</div>
		</form>
	</div>
</div>