<?php (isset($items['items'])) ? $items = $items['items'] : $items; ?>
<?php if(empty($items)): ?>
	<h2 class="basket"><?=$viewTranslate['BASKET_EMPTY'];?></h2>
	<div style="padding: 10 0 20 0;">
		<?=$viewTranslate['VISIT_CATALOGUE'];?> <?=$this->tag->linkTo([['for' => 'catalogue'], $viewTranslate['CATALOGUE']]); ?>
	</div>
<?php return; endif; ?>
<h2 class="basket">
	<?php if($get != null): ?>
		<?=$viewTranslate['ITEM_ADDED'];?>:
	<?php else: ?>
		<?=$viewTranslate['CART'];?>
	<?php endif;?>
</h2>
<!-- Информатор скидок -->
<?php $this->view->partial('partials/basket/discounts_hover', ['discounts' => (isset($basket['discounts'])) ? $basket['discounts'] : []]); ?>
<!-- /Информатор скидок -->
<table class="small-basket">
	<tbody>
	<?php foreach($items as $counter => $item): ?>
		<?php $item['price'] = (!empty($item['discount'])) ? $item['discount'] : $item['price']; ?>
		<tr class="item-row" id="basket_row_<?=$item['product_id']; ?>">

			<!-- Превью -->
			<td class="image" preview_id="<?=$item['product_id']; ?>">
				<div style="z-index: 2;" class="basket-preview">
					<div style="display: none;"  class="basket-preview-big" id="preview_<?=$item['product_id']; ?>">
						<img rel="<?=$item['product_id']; ?>" src="http://z95.ru/f/p/150x225/catalogue/<?=$item['product_id']; ?>/<?=$item['images'][0]; ?>">
					</div>
				</div>
				<div style="z-index: 0;" class="basket-preview">
					<div class="basket-preview-small">
						<img data-prevs="<?=$item['product_id']; ?>" src="http://z95.ru/f/p/50x75/catalogue/<?=$item['product_id']; ?>/<?=$item['images'][0]; ?>">
					</div>
				</div>
			</td>
			<!-- /Превью -->

			<!-- Счетчик -->
			<td preview_id="<?=$item['product_id']; ?>" class="title">
				<div class="counter"><?=++$counter; ?></div>
				<a href="<?=$this->url->get('catalogue/'.$item['articul']);?>">
					<span class="capitalize"><?=$item['product_name'] ?></span> <?=$item['brand']; ?></a><br>
				(<?php echo $item['articul']; ?>)<br>

			</td>
			<!-- /Счетчик -->

			<!-- Разбор размеров и количества -->
			<?php if(isset($item['sizes']) && !empty($item['sizes'])): ?>
				<td class="sizes">
					<table align="right" class="small-basket-sizes">
						<tbody>
						<?php  $total = 0; foreach($item['sizes'] as $size => $count): ?>
							<tr>
								<td width="50" class="number size">
									<?php if($size === '?'): ?>
										<div class="question_size">?</div>
									<?php elseif($size === 0): ?>
									<?php else: ?>
										<?=$size; ?>
									<?php endif;?>
								</td>
								<td width="115" class="input">
									<button onclick="var ov = $(this).next().val(); var nv = Math.max(0, parseInt(ov)-1); if (nv &lt; ov) { $(this).next().val(nv); basket.recount('<?php echo $item['product_id']; ?>', '<?php echo $size; ?>', $(this).next().val(), 'small'); }" class="button sign">−</button>
									<input type="text" onchange="basket.recount('<?php echo $item['product_id']; ?>', '<?php echo $size; ?>', this.value, 'basket')" onkeyup="basket.recount('<?php echo $item['product_id']; ?>', '<?php echo $size; ?>', this.value, 'small')" value="<?php echo $count; ?>" id="<?php echo $item['product_id']; ?>_<?php echo $size; ?>" size="2">
									<button onclick="var ov = $(this).prev().val(); var nv = Math.min(10, parseInt(ov)+1); if (nv &gt; ov) { $(this).prev().val(nv); basket.recount('<?php echo $item['product_id']; ?>', '<?php echo $size; ?>', $(this).prev().val(), 'small'); }" class="button sign">+</button>
									<div style="position:relative;"></div>
								</td>
								<td width="10" class="number">x</td>
								<td width="45" class="number"><?=number_format($item['price'], 0, '.', ' ');?></td>
								<td width="10" class="number">=</td>
								<td width="70" class="number recount"><?=number_format(($item['price']* $count), 0, '.', ' '); ?> <?php echo $shop['currency_symbol']; ?></td>
								<td width="20" align="right">
									<button onclick="basket.recount('<?php echo $item['product_id']; ?>', '<?php echo $size ?>', 0, 'small', 0)" class="button delete sign" title="удалить">x</button>
								</td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>
				</td>
			<?php endif;?>
			<!-- /Разбор размеров и количства -->
		</tr>
	<?php endforeach; ?>
	<tr>
		<td class="total" colspan="4">
			<table align="right" class="total">
				<tbody>
				<tr>
					<td><?=$viewTranslate['BUY_ALL'];?></td>
					<td class="number"><?=number_format($basket['sum'], 0, '.', ' '); ?> <?php echo $shop['currency_symbol']; ?></td>
				</tr>
				<?php if(isset($basket['discounts'])): ?>
					<?php $this->view->partial('partials/basket/discounts_footer', ['informer' => $basket]); ?>
				<?php endif; ?>
				<tr>
					<td><?=$viewTranslate['DELIVERY_FREE'];?></td>
					<td class="number"></td>
				</tr>
				</tbody>
			</table>
		</td>
	</tr>
	<tr>
		<td align="center" style="padding-top:30px;" colspan="4">
			<button onclick="$('#SMALL_BASKET').hide();" class="button"><?=$viewTranslate['CONTINUE_SHOPPING'];?></button>
			<button onclick="window.location.href='/customer/cart'" class="button"><?=$viewTranslate['GET_BASKET'];?></button>
		</td>
	</tr>
	</tbody>
</table>
<script type="text/javascript">
	$('.basket-basket td[preview_id]').each(function (i, el) {
		var $preview_id = $('#preview_'+$(el).attr('preview_id'));
		$(el).hover(
			function () {
				var img = $('img', $preview_id)[0];
				if (img.complete) {
					$preview_id.show();
				}
			},
			function () {
				$preview_id.hide();
			}
		)
	});
</script>