<!-- / Catalogue layout -->
<div class="column main-column">
	<div class="inner_teaser">
		<a href="<?=\Helpers\LocationUrls::location('/catalogue/sale'); ?>" >
			<?= $this->tag->image(array('f/t/5ad05dbba33a7c986ffad79ff33dbd98.jpg')); ?>
		</a>
	</div>
	<div id="CONTENT">
		<h1><?=$title;?></h1>

		<!-- Bread Crumbs -->
		<ul class="Thermo">
			<?= $breadcrumbs->get("/&nbsp;"); ?>
		</ul>
		<!-- /Bread Crumbs -->

		<div class="clear"></div>
		<div class="element-catalogue_items">

			<!-- Block tags module -->
			<?php //if(in_array($template, $sometemplates)) $this->partial('partials/catalogue/tags-cloud'); ?>
			<!-- /Block tags module -->

			<!-- Render content -->
			<?php $this->partial('partials/catalogue/'.$template); ?>
			<!-- /Render content -->
		</div>
	</div>
</div>
<!-- / Catalogue layout -->