<!-- / Catalogue layout -->
<div class="column main-column">
	<?php if(isset($banners['inner']) && !empty($banners['inner'])): ?>
		<div class="inner_teaser">
			<a href="<?=\Helpers\LocationUrls::location('/catalogue/sale'); ?>" >
				<?= $this->tag->image(array('f/t/'.$banners['inner'][0]['image'])); ?>
			</a>
		</div>
	</div>
	<?endif;?>

	<!-- Catalogue content layout -->
	<div id="CONTENT">
		<h1><?=$title;?></h1>
			<?php if(!empty($breadcrumbs)): ?>
				<!-- Bread Crumbs -->
				<ul class="Thermo">
					<?php foreach($breadcrumbs as $crumb): ?>
						<li>
							<?=($crumb['active']) ? $crumb['text'] : $this->tag->linkTo($crumb['link'], $crumb['text']).' / '; ?>
						</li>
					<?php endforeach; ?>
				</ul>
				<!-- Bread Crumbs -->
			<?endif;?>

		<div class="clear"></div>
		<div class="element-catalogue_items">

			<!-- Block tags module -->
			<?php //if(in_array($template, $sometemplates)) $this->partial('partials/catalogue/tags-cloud'); ?>
			<!-- /Block tags module -->

			<!-- Render content -->
			<?php $this->partial('partials/catalogue/'.$template); ?>
			<!-- /Render content -->
		</div>
	</div>
	<!-- /Catalogue content layout -->
</div>
<!-- / Catalogue layout -->