<div class="column main-column">
	<div class="ITEMS_LIST">
		<div id="CATALOGUE_SEARCH_RESULT">
		</div>
	</div>
	<div class="inner_teaser">
		<a href="<?=\Helpers\LocationUrls::location('/catalogue/'); ?>" target="_blank" title="">
			<img src="/f/t/5ad05dbba33a7c986ffad79ff33dbd98.jpg" alt="">
		</a>
	</div>
	<div id="CONTENT">
		<h1>Распродажа</h1>
		<ul class="Thermo"><li><a href="/">Главная</a></li><li>/&nbsp;<a href="/catalogue/">Каталог</a></li><li>/&nbsp;Распродажа</li></ul><div class="clear"></div><div class="element-catalogue_items"><div class="index-top-categories">

				<?php if(!empty($salesGroup)): ?>
					<?php foreach($salesGroup as $gender => $values): $sum[$gender] = 0; $opacity = 1;?>
						<?php if($gender !=0): ?>
							<div class="category id_<?=$gender;?>">
								<h2><?=($gender == 1) ? 'Мужчинам' : 'Женщинам'?><span class="count"></span></h2>
								<div class="discount-tiles">
									<?php foreach($values as $sales): ?>
										<a href="<?=\Helpers\LocationUrls::location('/catalogue/sale?percent[]='.$sales['percent'].'&sex='.$gender); ?>" class="tile" style="opacity: <?=$opacity;?>">
											<div class="value"><?=$sales['percent'];?>%</div>
											<div class="count">наименований — <span><?=$sales['count'];?></span></div>
										</a>
									<? $sum[$gender] += $sales['count']; $opacity = sprintf("%f", ($opacity - 0.2)); endforeach; ?>
									<a href="<?=\Helpers\LocationUrls::location('/catalogue/sale?percent[]=0&percent[]=100&sex='.$gender); ?>" class="tile" style="opacity: <?=$opacity;?>">
										<div class="value">Все</div>
										<div class="count">наименований — <span><?=$sum[$gender];?></span></div>
									</a>
								</div>
							</div>
						<?php endif; ?>
					<?php endforeach; ?>
				<?php else: ?>
					Распродаж нет
				<?php endif; ?>
			</div>
		</div>
	</div>
</div>
<div class="clear"></div>