<?php use Phalcon\Tag as Tag; ?>
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7 " lang="en"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8 ie7" lang="en"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9 ie8" lang="en"><![endif]-->
<!--[if gt IE 8]> <html class="no-js ie9" lang="en"><![endif]-->
<html lang="en" class="">
<head>
	<meta name="description" content="">
	<meta name="generator" content="">
	<meta name="robots" content="index,follow">
	<meta name="viewport" content="width=device-width, minimum-scale=0.25, maximum-scale=1.6, initial-scale=1.0">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<?php
		Tag::setTitle('Leo Fashion Store');
		echo Tag::getTitle();
		echo Tag::stylesheetLink('http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/bootstrap(1).css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/global.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/highdpi.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/responsive-tables.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/uniform.default.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/jquery.fancybox.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/blockcart.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/blockcategories.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/blockcurrencies.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/blocklanguages.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/blocknewsletter.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/blockspecials.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/blocktags.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/blockuserinfo.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/blockviewed.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/paneltool.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/colorpicker.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/megamenu.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/typo.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/styles.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/hooks.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/blockwishlist.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/productcomments.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/jquery.autocomplete.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/product_list.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/blocksearch.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/leocustomajax.css');
		echo Tag::stylesheetLink('assets/' . $shop->code . '/css/comparator.css');
	?>
	<script type="text/javascript">
		var CUSTOMIZE_TEXTFIELD = 1;
		var FancyboxI18nClose = 'Close';
		var FancyboxI18nNext = 'Next';
		var FancyboxI18nPrev = 'Previous';
		var added_to_wishlist = 'Added to your wishlist.';
		var ajax_allowed = true;
		var ajaxsearch = true;
		var baseDir = '/';
		var baseUri = '/index.php';
		var blocksearch_type = 'top';
		var contentOnly = false;
		var customizationIdMessage = 'Customization #';
		var delete_txt = 'Delete';
		var displayList = false;
		var freeProductTranslation = 'Free!';
		var freeShippingTranslation = 'Free shipping!';
		var generated_date = 1413191597;
		var id_lang = 1;
		var img_dir = '/images/';
		var instantsearch = false;
		var isGuest = 0;
		var isLogged = 0;
		var loggin_required = 'You must be logged in to manage your wishlist.';
		var mywishlist_url = '';
		var page_name = 'index';
		var placeholder_blocknewsletter = 'Enter your e-mail';
		var priceDisplayMethod = 1;
		var priceDisplayPrecision = 2;
		var quickView = true;
		var removingLinkText = 'remove this product from my cart';
		var roundMode = 2;
		var search_url = '';
		var static_token = '';
		var token = '';
		var usingSecureMode = false;
		var wishlistProductsIds = false;
	</script>
	<?php
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/jquery-1.11.0.min.js');
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/jquery-migrate-1.2.1.min.js');
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/jquery.easing.js');
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/tools.js');
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/global.js');
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/10-bootstrap.min.js');
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/15-jquery.total-storage.min.js');
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/15-jquery.uniform-modified.js');
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/jquery.fancybox.js');
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/products-comparison.js');
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/ajax-cart.js');
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/jquery.scrollTo(1).js');
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/jquery.serialScroll.js');
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/treeManagement.js');
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/blocknewsletter.js');
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/colorpicker.js');
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/paneltool.js');
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/jquery.themepunch.plugins.min.js');
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/jquery.themepunch.revolution.min.js');
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/ajax-wishlist.js');
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/jquery.autocomplete.js');
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/blocksearch.js');
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/leocustomajax.js');
		echo Tag::javascriptInclude('assets/' . $shop->code . '/js/countdown.js');
	?>
		<!--[if IE 8]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
		<![endif]-->
</head>
<body id="index" class="index hide-left-column hide-right-column lang_en fullwidth">
	<section id="page" data-column="col-xs-12 col-sm-12 col-md-3" data-type="grid">
	<!-- Header -->
	<header id="header">
	<section class="header-container">
	<div id="topbar">
	<div class="banner">
		<div class="container">
			<div class="row">

			</div>

		</div>
	</div>
	<div class="nav">
	<div class="container">
	<div class="row">
	<nav><script type="text/javascript">
			/* Blockusreinfo */

			$(document).ready( function(){
				$(".leo-groupe").each( function(){
					var content = $(".groupe-content");
					$(".groupe-btn", this ).click( function(){
						content.toggleClass("eshow");
					}) ;
				} );

				$(window).resize(function() {
					if( $(window).width() > 600 ){
						$(".groupe-content").removeClass('eshow');
					}
				});
			});
		</script>
		<!-- Block user information module NAV -->
		<div class="leo-groupe g-dropdown">
			<a class="groupe-btn visible-xs">Quick link <span class="caret"></span></a>
			<div id="header_user_info" class="pull-left groupe-content hidden-xs">
				<ul class="links">
					<li><a href="" title="View my customer account" rel="nofollow"> Your Account</a>
					</li>
					<li><a href="" title="My wishlists">My wishlists</a>
					</li>
					<li><a href="" title="Login to your customer account" class="login" rel="nofollow">Sign in</a>
					</li>
					<li><a href="" title="Register account" class="register" rel="nofollow">Register</a>
					</li>
				</ul>
			</div>
		</div>
		<!-- /Block usmodule NAV -->
		<!-- Block languages module -->
		<div id="languages-block-top" class="languages-block">
			<div class="current">
				<img src="assets/<?php echo $shop->code ?>/images/1.jpg" alt="en" width="16" height="11">
				<span>English</span>
			</div>
			<ul id="first-languages" class="languages-block_ul toogle_content">
				<li class="selected">
					<img src="assets/<?php echo $shop->code ?>/images/1.jpg" alt="en" width="16" height="11">
					<span>English</span>
				</li>
				<li>
					<a href="" title="Français (French)">
						<img src="assets/<?php echo $shop->code ?>/images/2.jpg" alt="fr" width="16" height="11">
						<span>Français</span>
					</a>
				</li>
				<li>
					<a href="" title="Deutsch (German)">
						<img src="assets/<?php echo $shop->code ?>/images/3.jpg" alt="de" width="16" height="11">
						<span>Deutsch</span>
					</a>
				</li>
				<li>
					<a href="" title="Portuguese-Brazil">
						<img src="assets/<?php echo $shop->code ?>/images/4.jpg" alt="br" width="16" height="11">
						<span>Portuguese-Brazil</span>
					</a>
				</li>
				<li>
					<a href="" title="Italiano (Italian)">
						<img src="assets/<?php echo $shop->code ?>/images/5.jpg" alt="it" width="16" height="11">
						<span>Italiano</span>
					</a>
				</li>
				<li>
					<a href="" title="Español (Spanish)">
						<img src="assets/<?php echo $shop->code ?>/images/6.jpg" alt="es" width="16" height="11">
						<span>Español</span>
					</a>
				</li>
				<li>
					<a href="" title="Russian">
						<img src="assets/<?php echo $shop->code ?>/images/7.jpg" alt="ru" width="16" height="11">
						<span>Russian</span>
					</a>
				</li>
				<li>
					<a href="" title="Polish">
						<img src="assets/<?php echo $shop->code ?>/images/8.jpg" alt="pl" width="16" height="11">
						<span>Polish</span>
					</a>
				</li>
				<li>
					<a href="" title="Arabic">
						<img src="assets/<?php echo $shop->code ?>/images/9.jpg" alt="ar" width="16" height="11">
						<span>Arabic</span>
					</a>
				</li>
			</ul>
		</div>
		<!-- /Block languages module -->
		<!-- Block currencies module -->
		<div id="currencies-block-top" class="dropdown_topbar">
			<form id="setCurrency" action="index.htm" method="post">
				<div class="current">
					<input type="hidden" name="id_currency" id="id_currency" value="">
					<input type="hidden" name="SubmitCurrency" value=""> USD </div>
				<ul id="first-currencies" class="currencies_ul toogle_content">
					<li class="selected">
						<a href="javascript:setCurrency(1);" rel="nofollow" title="Dollar">
							$&nbsp;Dollar
						</a>
					</li>
					<li>
						<a href="javascript:setCurrency(2);" rel="nofollow" title="Euros">
							€&nbsp;Euros
						</a>
					</li>
				</ul>
			</form>
		</div>
		<!-- /Block currencies module -->
	</nav>
	<div id="header_right">
		<!-- MODULE Block cart -->
		<div class="pull-right cart-top clearfix">
			<div class="shopping_cart">
				<a href="" title="View my shopping cart" rel="nofollow">
					<span class="title_cart">Cart</span>
					<span class="ajax_cart_quantity">1</span>
					<span class="ajax_cart_product_txt">Item</span>
					<span class="ajax_cart_product_txt_s unvisible">Items</span>
 <span class="ajax_cart_total">$450.00
 </span>
 <span class="ajax_cart_no_product unvisible">
 0 <span>Item</span> <span class="price"> - $0.00</span>
 </span>
				</a>
				<div class="cart_block block exclusive" style="display: none;">
					<div class="block_content">
						<!-- block list of products -->
						<div class="cart_block_list">
							<dl class="products">
								<dt data-id="cart_block_product_11_64_0" class="first_item">
									<a class="cart-images" href="" title="Aenean"><img src="assets/<?php echo $shop->code ?>/images/176-cart_default.jpg" alt="Aenean"></a>
								<div class="cart-info">
									<div class="product-name">
										<span class="quantity-formated"><span class="quantity">1</span>&nbsp;x&nbsp;</span><a class="cart_block_product_name" href="#/size-s/color-yellow" title="Aenean">Aenean</a>
									</div>
									<div class="product-atributes">
										<a href="#/size-s/color-yellow" title="Product detail">Yellow, S</a>
									</div>
									<span class="price">$450.00</span>
								</div>
								<span class="remove_link"><a class="ajax_cart_block_remove_link" href="" rel="nofollow" title="remove this product from my cart">&nbsp;</a></span>
								</dt>
								<dd data-id="cart_block_combination_of_11_64_0" class="first_item">
									<!-- Customizable datas -->
								</dd>
							</dl>
							<p class="cart_block_no_products unvisible">
								No products
							</p>
							<div class="cart-prices">
								<div class="cart-prices-line first-line"><span class="price cart_block_shipping_cost ajax_cart_shipping_cost">$2.00</span>
									<span>Shipping</span>
								</div>
								<div class="cart-prices-line last-line">
									<span class="price cart_block_total ajax_block_cart_total">$452.00</span>
									<span>Total</span>
								</div>
							</div>
							<p class="cart-buttons">
								<a id="button_order_cart" class="btn btn-default button button-small" href="" title="Check out" rel="nofollow">
									<span>Check out<i class="icon-chevron-right right"></i></span>
								</a>
							</p>
						</div>
					</div>
				</div>
				<!-- .cart_block -->
			</div>
		</div>

		<div id="layer_cart">
			<div class="clearfix">
				<div class="layer_cart_product col-xs-12 col-md-6">
					<span class="cross" title="Close window"></span>
					<h2>
						<i class="icon-ok"></i>Product successfully added to your shopping cart
					</h2>
					<div class="product-image-container layer_cart_img">
					</div>
					<div class="layer_cart_product_info">
						<span id="layer_cart_product_title" class="product-name"></span>
						<span id="layer_cart_product_attributes"></span>
						<div>
							<strong class="dark">Quantity</strong>
							<span id="layer_cart_product_quantity"></span>
						</div>
						<div>
							<strong class="dark">Total</strong>
							<span id="layer_cart_product_price"></span>
						</div>
					</div>
				</div>
				<div class="layer_cart_cart col-xs-12 col-md-6">
					<h2>
						<!-- Plural Case [both cases are needed because page may be updated in Javascript] -->
					<span class="ajax_cart_product_txt_s unvisible">
						There are <span class="ajax_cart_quantity">0</span> items in your cart.
					</span>
						<!-- Singular Case [both cases are needed because page may be updated in Javascript] -->
					<span class="ajax_cart_product_txt ">
						There is 1 item in your cart.
					</span>
					</h2>

					<div class="layer_cart_row">
						<strong class="dark">
							Total products
							(tax excl.)
						</strong>
					<span class="ajax_block_products_total">
											</span>
					</div>

					<div class="layer_cart_row">
						<strong class="dark">
							Total shipping&nbsp;(tax excl.)</strong>
						<span class="ajax_cart_shipping_cost">Free shipping!</span>
					</div>
					<div class="layer_cart_row">
						<strong class="dark">
							Total
							(tax excl.)
						</strong>
						<span class="ajax_block_cart_total"></span>
					</div>
					<div class="button-container">
					<span class="continue btn btn-default button exclusive-medium" title="Continue shopping">
						<span>
							<i class="icon-chevron-left left"></i>Continue shopping
						</span>
					</span>
						<a class="btn btn-default button button-medium" href="" title="Proceed to checkout" rel="nofollow">
						<span>
							Proceed to checkout<i class="icon-chevron-right right"></i>
						</span>
						</a>
					</div>
				</div>
			</div>
			<div class="crossseling"></div>
		</div>
		<!-- #layer_cart -->
		<div class="layer_cart_overlay"></div>

		<!-- /MODULE Block cart -->
		<script type="text/javascript">
			$(document).ready(function() {
				//search
				$("#search_block_top")
					.each(function() {
						var content = $(".groupe");
						$(".groupe-btn", this)
							.click(function() {
								content.toggleClass("show");
							});
					});

			});
		</script>
		<!-- Block search module TOP -->
		<div id="search_block_top" class="pull-right clearfix">
			<a class="groupe-btn dropdown hidden-md hidden-lg" title="Search" href=""></a>
			<form id="searchbox" method="get" class="groupe">
				<input type="hidden" name="controller" value="search">
				<input type="hidden" name="orderby" value="position">
				<input type="hidden" name="orderway" value="desc">
				<input class="search_query form-control ac_input" type="text" id="search_query_top" name="search_query" placeholder="Search" value="" autocomplete="off">
				<button type="submit" name="submit_search" class="btn btn-default button-search">
					<span>Search</span>
				</button>
			</form>
		</div>
		<!-- /Block search module TOP -->
	</div>
	</div>
	</div>
	</div>
	</div>
	<div id="header-main">
		<div class="container">
			<div class="row">
				<div id="header_logo" class="pull-left">
					<a href="" title="Leo Fashion Store">
						<img class="logo img-responsive" src="assets/<?php echo $shop->code ?>/images/leo-mobile-1399525585.jpg" alt="Leo Fashion Store" width="155" height="95">
					</a>

				</div>

			</div>
		</div>
	</div>
	</section>
	</header>
	<div id="topnavigation" class="clearfix">
	<div class="container">
	<nav id="cavas_menu" class="navbar navbar-default" role="navigation">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
	</div>
	<!-- Collect the nav links, forms, and other content for toggling -->
	<div id="leo-top-menu" class="collapse navbar-collapse navbar-ex1-collapse">
	<ul class="nav navbar-nav megamenu">
	<li class="active">
		<a href="" target="_self" class="has-category"><span class="menu-title">Home</span></a>
	</li>
	<li class=" parent dropdown aligned-fullwidth ">
	<a href="" class="dropdown-toggle has-category" data-toggle="dropdown" target="_self"><span class="menu-title">Categories</span><b class="caret"></b></a>
	<div class="dropdown-sub dropdown-menu" style="width:680px">
	<div class="dropdown-menu-inner">
	<div class="row">
	<div class="mega-col col-sm-3">
		<div class="mega-col-inner ">
			<div class="leo-widget">
				<div class="widget-subcategories">
					<div class="widget-inner">
						<div class="menu-title">Categories</div>
						<ul>
							<li class="clearfix">
								<a href="" title="Outerwear" class="img">
									Outerwear
								</a>
							</li>
							<li class="clearfix">
								<a href="" title="Dresses" class="img">
									Dresses
								</a>
							</li>
							<li class="clearfix">
								<a href="" title="Accessories" class="img">
									Accessories
								</a>
							</li>
							<li class="clearfix">
								<a href="" title="New" class="img">
									New
								</a>
							</li>
							<li class="clearfix">
								<a href="" title="Clothes" class="img">
									Clothes
								</a>
							</li>
							<li class="clearfix">
								<a href="" title="Bootoms" class="img">
									Bootoms
								</a>
							</li>

						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="mega-col col-sm-3">
		<div class="mega-col-inner ">
			<div class="leo-widget"> </div>
			<div class="leo-widget">
				<div class="widget-products">
					<div class="menu-title">
						New product
					</div>
					<div class="widget-inner">

						<div class="product-block">

							<div class="product-container clearfix">
								<div class="image ">
									<a class="product_img_link" href="" title="Donec posuere metus" itemprop="url">
										<img class="replace-2x img-responsive" src="assets/<?php echo $shop->code ?>/images/187-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
									</a>
 <span class="new-box">
 <span class="new-label">New</span>
 </span>
								</div>
								<div class="product-meta">
									<h5 itemprop="name">
										<a class="product-name" href="" title="Donec posuere metus" itemprop="url">
											Donec posuere metus
										</a>
									</h5>
									<p class="product-desc" itemprop="description">
										Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet...
									</p>
									<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="content_price">
 <span itemprop="price" class="price product-price">
 $600.00										</span>
										<meta itemprop="priceCurrency" content="1">
									</div>
								</div>
							</div>



							<div class="product-container clearfix">
								<div class="image ">
									<a class="product_img_link" href="" title="Morbi vitae cons" itemprop="url">
										<img class="replace-2x img-responsive" src="assets/<?php echo $shop->code ?>/images/168-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
									</a>
 <span class="new-box">
 <span class="new-label">New</span>
 </span>
								</div>
								<div class="product-meta">
									<h5 itemprop="name">
										<a class="product-name" href="" title="Morbi vitae cons" itemprop="url">
											Morbi vitae cons
										</a>
									</h5>
									<p class="product-desc" itemprop="description">
										Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet...
									</p>
									<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="content_price">
										<span itemprop="price" class="price product-price">$550.00</span>
										<meta itemprop="priceCurrency" content="1">
									</div>
								</div>
							</div>



							<div class="product-container clearfix">
								<div class="image ">
									<a class="product_img_link" href="" title="Integer sit am" itemprop="url">
										<img class="replace-2x img-responsive" src="assets/<?php echo $shop->code ?>/images/170-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
									</a>
 <span class="new-box">
 <span class="new-label">New</span>
 </span>
								</div>
								<div class="product-meta">
									<h5 itemprop="name">
										<a class="product-name" href="" title="Integer sit am" itemprop="url">
											Integer sit am
										</a>
									</h5>
									<p class="product-desc" itemprop="description">
										Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet...
									</p>
									<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="content_price">
										<span itemprop="price" class="price product-price">$20.50</span>
										<meta itemprop="priceCurrency" content="1">
									</div>
								</div>
							</div>


						</div>



					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="mega-col col-sm-3">
		<div class="mega-col-inner ">
			<div class="leo-widget">
				<div class="widget-products">
					<div class="menu-title">
						New product
					</div>
					<div class="widget-inner">

						<div class="product-block">





							<div class="product-container clearfix">
								<div class="image ">
									<a class="product_img_link" href="" title="Donec posuere metus" itemprop="url">
										<img class="replace-2x img-responsive" src="assets/<?php echo $shop->code ?>/images/187-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
									</a>
 <span class="new-box">
 <span class="new-label">New</span>
 </span>
								</div>
								<div class="product-meta">
									<h5 itemprop="name">
										<a class="product-name" href="" title="Donec posuere metus" itemprop="url">
											Donec posuere metus
										</a>
									</h5>
									<p class="product-desc" itemprop="description">
										Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet...
									</p>
									<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="content_price">
 <span itemprop="price" class="price product-price">$600.00
 </span>
										<meta itemprop="priceCurrency" content="1">
									</div>
								</div>
							</div>



							<div class="product-container clearfix">
								<div class="image ">
									<a class="product_img_link" href="" title="Morbi vitae cons" itemprop="url">
										<img class="replace-2x img-responsive" src="assets/<?php echo $shop->code ?>/images/168-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
									</a>
 <span class="new-box">
 <span class="new-label">New</span>
 </span>
								</div>
								<div class="product-meta">
									<h5 itemprop="name">
										<a class="product-name" href="" title="Morbi vitae cons" itemprop="url">
											Morbi vitae cons
										</a>
									</h5>
									<p class="product-desc" itemprop="description">
										Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet...
									</p>
									<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="content_price">
										<span itemprop="price" class="price product-price">$550.00</span>
										<meta itemprop="priceCurrency" content="1">
									</div>
								</div>
							</div>



							<div class="product-container clearfix">
								<div class="image ">
									<a class="product_img_link" href="" title="Integer sit am" itemprop="url">
										<img class="replace-2x img-responsive" src="assets/<?php echo $shop->code ?>/images/170-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
									</a>
 <span class="new-box">
 <span class="new-label">New</span>
 </span>
								</div>
								<div class="product-meta">
									<h5 itemprop="name">
										<a class="product-name" href="" title="Integer sit am" itemprop="url">
											Integer sit am
										</a>
									</h5>
									<p class="product-desc" itemprop="description">
										Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet...
									</p>
									<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="content_price">
 <span itemprop="price" class="price product-price">$20.50
 </span>
										<meta itemprop="priceCurrency" content="1">
									</div>
								</div>
							</div>


						</div>



					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="mega-col col-sm-3">
		<div class="mega-col-inner ">
			<div class="leo-widget">
				<div class="widget-html">
					<div class="menu-title">
						Morbi ipsum
					</div>
					<div class="widget-inner">
						<div class="menu-content">
							<p><img src="assets/<?php echo $shop->code ?>/images/adv.jpg" alt="" width="207" height="118">
							</p>
							<p><a href="">Mauris in erat justo nullam ac urna eu felis dapibus condimentum sit amet a sed ut imperdiet nisi.</a>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>
	<div class="row"></div>
	</div>
	</div>
	</li>
	<li class=" parent dropdown aligned-left ">
		<a href="" class="dropdown-toggle has-category" data-toggle="dropdown" target="_self"><span class="menu-title">Community</span><b class="caret"></b></a>
		<div class="dropdown-sub dropdown-menu" style="width:684px">
			<div class="dropdown-menu-inner">
				<div class="row">
					<div class="mega-col col-sm-3">
						<div class="mega-col-inner ">
							<div class="leo-widget">
								<div class="widget-links">
									<div class="menu-title">
										Custom Link
									</div>
									<div class="widget-inner">
										<div id="tabs1060995877" class="panel-group">
											<ul class="nav-links">

												<li><a href="">Proin ac sapien ut</a>
												</li>

												<li><a href="">Headphones</a>
												</li>

												<li><a href="">Donec magna diam</a>
												</li>

												<li><a href="">Module Position</a>
												</li>

												<li><a href="">Fully Loaded</a>
												</li>

												<li><a href="">Donec magna diam</a>
												</li>

												<li>
													<a href=""></a>
												</li>

												<li>
													<a href=""></a>
												</li>

												<li>
													<a href=""></a>
												</li>

												<li>
													<a href=""></a>
												</li>
											</ul>
										</div>
									</div>
								</div>


							</div>
						</div>
					</div>
					<div class="mega-col col-sm-5">
						<div class="mega-col-inner ">
							<div class="leo-widget">
								<div class="widget-video">
									<div class="menu-title">
										Leo Framework
									</div>
									<div class="widget-inner">
										<iframe width="230" height="200" src="temp.html" frameborder="0" allowfullscreen=""></iframe>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="mega-col col-sm-4">
						<div class="mega-col-inner ">
							<div class="leo-widget">
								<div class="widget-links">
									<div class="menu-title">
										Link Guide
									</div>
									<div class="widget-inner">
										<div id="tabs2082739320" class="panel-group">
											<ul class="nav-links">

												<li><a href="">Leo Template Control Panel</a>
												</li>

												<li><a href="">Leo Mega Menu Module</a>
												</li>

												<li><a href="">Leo Slider Layer Module</a>
												</li>

												<li><a href="">Leo Framework</a>
												</li>

												<li><a href=""> Install Prestashop 1.6</a>
												</li>

												<li><a href="">Guide Theme</a>
												</li>

												<li>
													<a href=""></a>
												</li>

												<li>
													<a href=""></a>
												</li>

												<li>
													<a href=""></a>
												</li>

												<li>
													<a href=""></a>
												</li>
											</ul>
										</div>
									</div>
								</div>


							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</li>
	<li class=" parent dropdown aligned-fullwidth ">
	<a href="" class="dropdown-toggle has-category" data-toggle="dropdown" target="_self"><span class="menu-title">Shop</span><b class="caret"></b></a>
	<div class="dropdown-sub dropdown-menu" style="width:691px">
	<div class="dropdown-menu-inner">
	<div class="row">
	<div class="mega-col col-sm-3">
		<div class="mega-col-inner ">
			<div class="leo-widget">
				<div class="widget-links">
					<div class="menu-title">
						Block Link
					</div>
					<div class="widget-inner">
						<div id="tabs1928489512" class="panel-group">
							<ul class="nav-links">

								<li><a href="">Vivamus non nisl ut</a>
								</li>

								<li><a href="">Custom Module</a>
								</li>

								<li><a href="">Typography</a>
								</li>

								<li><a href="">Proin ac sapien ut</a>
								</li>

								<li><a href="">Typography</a>
								</li>

								<li><a href="">Donec magna diam</a>
								</li>

								<li>
									<a href=""></a>
								</li>

								<li>
									<a href=""></a>
								</li>

								<li>
									<a href=""></a>
								</li>

								<li>
									<a href=""></a>
								</li>
							</ul>
						</div>
					</div>
				</div>


			</div>
		</div>
	</div>
	<div class="mega-col col-sm-3">
		<div class="mega-col-inner ">
			<div class="leo-widget">
				<div class="widget-links">
					<div class="menu-title">
						Block Link
					</div>
					<div class="widget-inner">
						<div id="tabs810973445" class="panel-group">
							<ul class="nav-links">

								<li><a href="">Vivamus non nisl ut</a>
								</li>

								<li><a href="">Custom Module</a>
								</li>

								<li><a href="">Typography</a>
								</li>

								<li><a href="">Proin ac sapien ut</a>
								</li>

								<li><a href="">Typography</a>
								</li>

								<li><a href="">Donec magna diam</a>
								</li>

								<li>
									<a href=""></a>
								</li>

								<li>
									<a href=""></a>
								</li>

								<li>
									<a href=""></a>
								</li>

								<li>
									<a href=""></a>
								</li>
							</ul>
						</div>
					</div>
				</div>


			</div>
		</div>
	</div>
	<div class="mega-col col-sm-3">
		<div class="mega-col-inner ">
			<div class="leo-widget">
				<div class="widget-products">
					<div class="menu-title">
						New product
					</div>
					<div class="widget-inner">

						<div class="product-block">
							<div class="product-container clearfix">
								<div class="image ">
									<a class="product_img_link" href="" title="Donec posuere metus" itemprop="url">
										<img class="replace-2x img-responsive" src="assets/<?php echo $shop->code ?>/images/187-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
									</a>
 <span class="new-box">
 <span class="new-label">New</span>
 </span>
								</div>
								<div class="product-meta">
									<h5 itemprop="name">
										<a class="product-name" href="" title="Donec posuere metus" itemprop="url">
											Donec posuere metus
										</a>
									</h5>
									<p class="product-desc" itemprop="description">
										Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet...
									</p>
									<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="content_price">
										<span itemprop="price" class="price product-price">$600.00</span>
										<meta itemprop="priceCurrency" content="1">
									</div>
								</div>
							</div>



							<div class="product-container clearfix">
								<div class="image ">
									<a class="product_img_link" href="" title="Morbi vitae cons" itemprop="url">
										<img class="replace-2x img-responsive" src="assets/<?php echo $shop->code ?>/images/168-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
									</a>
 <span class="new-box">
 <span class="new-label">New</span>
 </span>
								</div>
								<div class="product-meta">
									<h5 itemprop="name">
										<a class="product-name" href="" title="Morbi vitae cons" itemprop="url">
											Morbi vitae cons
										</a>
									</h5>
									<p class="product-desc" itemprop="description">
										Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet...
									</p>
									<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="content_price">
 <span itemprop="price" class="price product-price">$550.00
 </span>
										<meta itemprop="priceCurrency" content="1">
									</div>
								</div>
							</div>



							<div class="product-container clearfix">
								<div class="image ">
									<a class="product_img_link" href="" title="Integer sit am" itemprop="url">
										<img class="replace-2x img-responsive" src="assets/<?php echo $shop->code ?>/images/170-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
									</a>
 <span class="new-box">
 <span class="new-label">New</span>
 </span>
								</div>
								<div class="product-meta">
									<h5 itemprop="name">
										<a class="product-name" href="" title="Integer sit am" itemprop="url">
											Integer sit am
										</a>
									</h5>
									<p class="product-desc" itemprop="description">
										Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet...
									</p>
									<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="content_price">
 <span itemprop="price" class="price product-price">$20.50
 </span>
										<meta itemprop="priceCurrency" content="1">
									</div>
								</div>
							</div>


						</div>



					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="mega-col col-sm-3">
		<div class="mega-col-inner ">
			<div class="leo-widget">
				<div class="widget-html">
					<div class="menu-title">
						Morbi ipsum
					</div>
					<div class="widget-inner">
						<div class="menu-content">
							<p><img src="assets/<?php echo $shop->code ?>/images/adv.jpg" alt="" width="207" height="118">
							</p>
							<p><a href="">Mauris in erat justo nullam ac urna eu felis dapibus condimentum sit amet a sed ut imperdiet nisi.</a>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>
	<div class="row">
		<div class="mega-col col-sm-12">
			<div class="mega-col-inner ">
				<div class="leo-widget">
					<div class="widget-manufacture">
						<div class="widget-inner">
							<div class="manu-logo">
								<a href="" title="view products">
									<img src="assets/<?php echo $shop->code ?>/images/11-leo_manu_menu.jpg" alt=""> </a>
								<a href="" title="view products">
									<img src="assets/<?php echo $shop->code ?>/images/12-leo_manu_menu.jpg" alt=""> </a>
								<a href="" title="view products">
									<img src="assets/<?php echo $shop->code ?>/images/5-leo_manu_menu.jpg" alt=""> </a>
								<a href="" title="view products">
									<img src="assets/<?php echo $shop->code ?>/images/6-leo_manu_menu.jpg" alt=""> </a>
								<a href="" title="view products">
									<img src="assets/<?php echo $shop->code ?>/images/7-leo_manu_menu.jpg" alt=""> </a>
								<a href="" title="view products">
									<img src="assets/<?php echo $shop->code ?>/images/9-leo_manu_menu.jpg" alt=""> </a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>
	</div>
	</li>
	<li class="parent dropdown "><a class="dropdown-toggle has-category" data-toggle="dropdown" href="" target="_self"><span class="menu-title">Delivery</span><b class="caret"></b></a>
		<div class="dropdown-menu level1" style="width:230px">
			<div class="dropdown-menu-inner">
				<div class="row">
					<div class="mega-col col-sm-12" data-type="menu">
						<div class="mega-col-inner ">
							<ul>
								<li class=" "><a href=""><span class="menu-title">Lorem ipsum dolor sit</span></a>
								</li>
								<li class="parent dropdown-submenu "><a class="dropdown-toggle" data-toggle="dropdown" href=""><span class="menu-title">Nulla quis felis at sapien</span><b class="caret"></b></a>
									<div class="dropdown-menu level2" style="width:250px">
										<div class="dropdown-menu-inner">
											<div class="row">
												<div class="mega-col col-sm-12" data-type="menu">
													<div class="mega-col-inner ">
														<ul>
															<li class=" "><a href=""><span class="menu-title">Lorem ipsum dolor sit</span></a>
															</li>
															<li class=" "><a href=""><span class="menu-title">Lorem ipsum dolor</span></a>
															</li>
															<li class=" "><a href=""><span class="menu-title">Proin ac sapien ut</span></a>
															</li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div>
								</li>
								<li class=" "><a href=""><span class="menu-title">Lorem ipsum dolor sit</span></a>
								</li>
								<li class=" "><a href=""><span class="menu-title">Vivamus non nisl ut</span></a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</li>
	<li class="">
		<a href="" target="_self" class="has-category"><span class="menu-title">About us</span></a>
	</li>
	</ul>
	</div>
	</nav>
	<script type="text/javascript">
		// <![CDATA[
		var current_link = "";
		//alert(request);
		var currentURL = window.location;
		currentURL = String(currentURL);
		currentURL = currentURL.replace("https://", "").replace("http://", "").replace("www.", "").replace(/#\w*/, "");
		current_link = current_link.replace("https://", "").replace("http://", "").replace("www.", "");
		isHomeMenu = 0;
		if ($("body").attr("id") == "index") isHomeMenu = 1;
		$(".megamenu > li > a").each(function() {
			menuURL = $(this).attr("href").replace("https://", "").replace("http://", "").replace("www.", "").replace(/#\w*/, "");
			if ((currentURL == menuURL) || (currentURL.replace(current_link, "") == menuURL) || isHomeMenu) {
				$(this).parent().addClass("active");
				return false;
			}
		});
		// ]]>
	</script>
	<script type="text/javascript">
		(function($) {
			$.fn.OffCavasmenu = function(opts) {
				// default configuration
				var config = $.extend({}, {
					opt1: null,
					text_warning_select: "Please select One to remove?",
					text_confirm_remove: "Are you sure to remove footer row?",
					JSON: null
				}, opts);
				// main function
				// initialize every element
				this.each(function() {
					var $btn = $('#cavas_menu .navbar-toggle');
					var $nav = null;
					if (!$btn.length)
						return;
					var $nav = $('<section id="off-canvas-nav"><nav class="offcanvas-mainnav" ><div id="off-canvas-button"><span class="off-canvas-nav"></span>Close</div></nav></sections>');
					var $menucontent = $($btn.data('target')).find('.megamenu').clone();
					$("body").append($nav);
					$("#off-canvas-nav .offcanvas-mainnav").append($menucontent);
					$("html")
						.addClass("off-canvas");
					$("#off-canvas-button").click(function() {
						$btn.click();
					});
					$btn.toggle(function() {
						$("body").removeClass("off-canvas-inactive").addClass("off-canvas-active");
					}, function() {
						$("body").removeClass("off-canvas-active").addClass("off-canvas-inactive");
					});
				});
				return this;
			}
		})(jQuery);
		$(document).ready(function() {
			jQuery("#cavas_menu").OffCavasmenu();
			$('#cavas_menu .navbar-toggle').click(function() {
				$('body,html').animate({
					scrollTop: 0
				}, 0);
				return false;
			});

			$(window).resize(function() {
				if ($(window).width() > 767) {
					$("body").removeClass("off-canvas-active").addClass("off-canvas-inactive");
				}
			});
		});
		$(document.body).on('click', '[data-toggle="dropdown"]', function() {
			if (!$(this).parent().hasClass('open') && this.href && this.href != '#') {
				window.location.href = this.href;
			}
		});
	</script>

	</div>
	</div>
		<?php echo $this->getContent(); ?>

	<!-- Footer -->
	<footer id="footer" class="footer-container">
	<section id="footertop" class="footer-top">
		<div class="container">
			<div class="row">
				<div class="widget col-lg-12 col-md-12 col-sm-12 col-xs-12 col-sp-12 hidden-md hidden-xs hidden-sm hidden-sp">
					<div class="widget-manufacture block">
						<div class="block_content">
							<div class="carousel slide" id="manucarousel">

								<a class="carousel-control left" href="#manucarousel" data-slide="prev">‹</a>
								<a class="carousel-control right" href="#manucarousel" data-slide="next">›</a>
								<div class="carousel-inner">
									<div class="item active">
										<div class="row">
											<div class="logo-manu col-md-2 col-xs-12">
												<a href="" title="view products">
													<img src="assets/<?php echo $shop->code ?>/images/11-manu_default.jpg" alt="">
												</a>
											</div>
											<div class="logo-manu col-md-2 col-xs-12">
												<a href="" title="view products">
													<img src="assets/<?php echo $shop->code ?>/images/12-manu_default.jpg" alt="">
												</a>
											</div>
											<div class="logo-manu col-md-2 col-xs-12">
												<a href="" title="view products">
													<img src="assets/<?php echo $shop->code ?>/images/5-manu_default.jpg" alt="">
												</a>
											</div>
											<div class="logo-manu col-md-2 col-xs-12">
												<a href="" title="view products">
													<img src="assets/<?php echo $shop->code ?>/images/6-manu_default.jpg" alt="">
												</a>
											</div>
											<div class="logo-manu col-md-2 col-xs-12">
												<a href="" title="view products">
													<img src="assets/<?php echo $shop->code ?>/images/7-manu_default.jpg" alt="">
												</a>
											</div>
											<div class="logo-manu col-md-2 col-xs-12">
												<a href="" title="view products">
													<img src="assets/<?php echo $shop->code ?>/images/9-manu_default.jpg" alt="">
												</a>
											</div>
										</div>
									</div>
									<div class="item ">
										<div class="row">
											<div class="logo-manu col-md-2 col-xs-12">
												<a href="" title="view products">
													<img src="assets/<?php echo $shop->code ?>/images/10-manu_default.jpg" alt="">
												</a>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>
	</section>
	<!-- #footertop -->
	<section id="footercenter" class="footer-center">
		<div class="container">
			<div class="footercenter_container">
				<div class="row">
					<script type="text/javascript">
						var leoOption = {
							productNumber: 1,
							productInfo: 1,
							productTran: 1,
							productCdown: 1,
							productColor: 1,
						}
						$(document)
							.ready(function() {
								var leoCustomAjax = new $.LeoCustomAjax();
								leoCustomAjax.processAjax();
							});
					</script>
					<div class="widget col-lg-9 col-md-9 col-sm-12 col-xs-9-6 col-sp-12">
						<div class="widget-html block">
							<div class="block_content">
								<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
									<div class="box logo-ft"><img src="assets/<?php echo $shop->code ?>/images/logo_footer.png" alt="logo-footer" width="144" height="98">
									</div>
								</div>
								<div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
									<h3 class="title_block">About The Shop</h3>
									<div class="about">
										<p>Sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio.</p>
									</div>
								</div>
							</div>
						</div>
					</div>

					<section id="social_block" class="col-md-3 col-sm-12">
						<h4>FOLLOW US ON SOCIAL</h4>
						<ul>
							<li class="facebook">
								<a target="_blank" href="http://www.facebook.com/prestashop">
									<span>Facebook</span>
								</a>
							</li>
							<li class="twitter">
								<a target="_blank" href="http://www.twitter.com/prestashop">
									<span>Twitter</span>
								</a>
							</li>
							<li class="rss">
								<a target="_blank" href="http://www.prestashop.com/blog/en/feed/">
									<span>RSS</span>
								</a>
							</li>
							<li class="youtube">
								<a href="https://www.youtube.com/">
									<span>Youtube</span>
								</a>
							</li>
							<li class="google-plus">
								<a href="https://plus.google.com/">
									<span>Google Plus</span>
								</a>
							</li>
						</ul>
					</section>
					<div class="clearfix"></div>

				</div>
			</div>
		</div>
	</section>
	<!-- #footercenter -->
	<section id="footerbottom" class="footer-bottom">
		<div class="container">
			<div class="row ">
				<div class="widget col-lg-3 col-md-3 col-sm-6 col-xs-12 col-sp-12">
					<div class="widget-html block">
						<h4 class="title_block">
							About us
						</h4>
						<div class="block_content">
							<div class="block_content">
								<ul class="widget-items">
									<li class="widget-text">
										<div class="box-services">
											<p>Monday - Friday .................. 8.00 to 18.00</p>
											<p>Saturday ......................... 9.00 to 21.00</p>
											<p>Sunday ........................... 10.00 to 21.00</p>
											<span class="iconbox pull-left"><span class="fa fa-phone">&nbsp;</span></span>
											<div class="media-body">Call us:&nbsp;<span class="h4">0123 456 789</span>
											</div>
										</div>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="widget col-lg-2 col-md-2 col-sm-6 col-xs-12 col-sp-12">
					<div class="widget-links block">
						<h4 class="title_block">
							Information
						</h4>
						<div class="block_content">
							<div id="tabs995003407" class="panel-group">
								<ul class="nav-links">

									<li><a href="">Best sellers</a>
									</li>

									<li><a href="">Specials</a>
									</li>

									<li><a href="">New products</a>
									</li>

									<li><a href="">Our stores</a>
									</li>

									<li><a href="">Sitemap</a>
									</li>
								</ul>
							</div>
						</div>
					</div>


				</div>
				<div class="widget col-lg-2 col-md-2 col-sm-6 col-xs-12 col-sp-12">
					<div class="widget-links block">
						<h4 class="title_block">
							Information
						</h4>
						<div class="block_content">
							<div id="tabs1868157759" class="panel-group">
								<ul class="nav-links">

									<li><a href="">Best sellers</a>
									</li>

									<li><a href="">Specials</a>
									</li>

									<li><a href="">New products</a>
									</li>

									<li><a href="">Our stores</a>
									</li>

									<li><a href="">Sitemap</a>
									</li>
								</ul>
							</div>
						</div>
					</div>


				</div>
				<div class="widget col-lg-2 col-md-2 col-sm-6 col-xs-12 col-sp-12">
					<div class="widget-links block">
						<h4 class="title_block">
							My account
						</h4>
						<div class="block_content">
							<div id="tabs69106804" class="panel-group">
								<ul class="nav-links">

									<li><a href="">My orders</a>
									</li>

									<li><a href="">My credit slips</a>
									</li>

									<li><a href="">My addresses</a>
									</li>

									<li><a href="">My personal info</a>
									</li>

									<li><a href="">My vouchers</a>
									</li>
								</ul>
							</div>
						</div>
					</div>


				</div>
				<div class="widget col-lg-3 col-md-3 col-sm-6 col-xs-12 col-sp-12">
					<div class="widget-html block">
						<h4 class="title_block">
							Address
						</h4>
						<div class="block_content">
							<address><strong>Warehouse Offices</strong><br>12345 Street name, California, USA<br>0123 456 789 / 0123 456 788</address><address><strong>Retail Store</strong><br>54321 Street name, California, USA<br>0123 456 789 / 0123 456 788</address>
						</div>
					</div>
				</div>
			</div>


		</div>
	</section>
	<!-- #footerbottom -->
	<section id="footernav" class="footer-nav">
		<div class="container">
			<div class="inner">
				<div class="row">
					<div id="poweredby" class="col-md-12 col-xs-12">
						Copyright 2014 Powered by PrestaShop. All Rights Reserved.
						<br>Designed By <span>LeoTheme</span>
					</div>
					<!-- #poweredby -->
				</div>
			</div>
		</div>
	</section>
	</footer>
	</section>
	<section id="off-canvas-nav"><nav class="offcanvas-mainnav"><div id="off-canvas-button"><span class="off-canvas-nav"></span>Close</div><ul class="nav navbar-nav megamenu">
	<li class="active">
		<a href="" target="_self" class="has-category"><span class="menu-title">Home</span></a>
	</li>
	<li class=" parent dropdown aligned-fullwidth ">
	<a href="" class="dropdown-toggle has-category" data-toggle="dropdown" target="_self"><span class="menu-title">Categories</span><b class="caret"></b></a>
	<div class="dropdown-sub dropdown-menu" style="width:680px">
	<div class="dropdown-menu-inner">
	<div class="row">
	<div class="mega-col col-sm-3">
		<div class="mega-col-inner ">
			<div class="leo-widget">
				<div class="widget-subcategories">
					<div class="widget-inner">
						<div class="menu-title">Categories</div>
						<ul>
							<li class="clearfix">
								<a href="" title="Outerwear" class="img">
									Outerwear
								</a>
							</li>
							<li class="clearfix">
								<a href="" title="Dresses" class="img">
									Dresses
								</a>
							</li>
							<li class="clearfix">
								<a href="" title="Accessories" class="img">
									Accessories
								</a>
							</li>
							<li class="clearfix">
								<a href="" title="New" class="img">
									New
								</a>
							</li>
							<li class="clearfix">
								<a href="" title="Clothes" class="img">
									Clothes
								</a>
							</li>
							<li class="clearfix">
								<a href="" title="Bootoms" class="img">
									Bootoms
								</a>
							</li>

						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="mega-col col-sm-3">
		<div class="mega-col-inner ">
			<div class="leo-widget"> </div>
			<div class="leo-widget">
				<div class="widget-products">
					<div class="menu-title">
						New product
					</div>
					<div class="widget-inner">

						<div class="product-block">

							<div class="product-container clearfix">
								<div class="image ">
									<a class="product_img_link" href="" title="Donec posuere metus" itemprop="url">
										<img class="replace-2x img-responsive" src="assets/<?php echo $shop->code ?>/images/187-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
									</a>
 <span class="new-box">
 <span class="new-label">New</span>
 </span>
								</div>
								<div class="product-meta">
									<h5 itemprop="name">
										<a class="product-name" href="" title="Donec posuere metus" itemprop="url">
											Donec posuere metus
										</a>
									</h5>
									<p class="product-desc" itemprop="description">
										Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet...
									</p>
									<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="content_price">
 <span itemprop="price" class="price product-price">
 $600.00										</span>
										<meta itemprop="priceCurrency" content="1">
									</div>
								</div>
							</div>



							<div class="product-container clearfix">
								<div class="image ">
									<a class="product_img_link" href="" title="Morbi vitae cons" itemprop="url">
										<img class="replace-2x img-responsive" src="assets/<?php echo $shop->code ?>/images/168-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
									</a>
 <span class="new-box">
 <span class="new-label">New</span>
 </span>
								</div>
								<div class="product-meta">
									<h5 itemprop="name">
										<a class="product-name" href="" title="Morbi vitae cons" itemprop="url">
											Morbi vitae cons
										</a>
									</h5>
									<p class="product-desc" itemprop="description">
										Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet...
									</p>
									<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="content_price">
										<span itemprop="price" class="price product-price">$550.00</span>
										<meta itemprop="priceCurrency" content="1">
									</div>
								</div>
							</div>



							<div class="product-container clearfix">
								<div class="image ">
									<a class="product_img_link" href="" title="Integer sit am" itemprop="url">
										<img class="replace-2x img-responsive" src="assets/<?php echo $shop->code ?>/images/170-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
									</a>
 <span class="new-box">
 <span class="new-label">New</span>
 </span>
								</div>
								<div class="product-meta">
									<h5 itemprop="name">
										<a class="product-name" href="" title="Integer sit am" itemprop="url">
											Integer sit am
										</a>
									</h5>
									<p class="product-desc" itemprop="description">
										Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet...
									</p>
									<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="content_price">
										<span itemprop="price" class="price product-price">$20.50</span>
										<meta itemprop="priceCurrency" content="1">
									</div>
								</div>
							</div>


						</div>



					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="mega-col col-sm-3">
		<div class="mega-col-inner ">
			<div class="leo-widget">
				<div class="widget-products">
					<div class="menu-title">
						New product
					</div>
					<div class="widget-inner">

						<div class="product-block">





							<div class="product-container clearfix">
								<div class="image ">
									<a class="product_img_link" href="" title="Donec posuere metus" itemprop="url">
										<img class="replace-2x img-responsive" src="assets/<?php echo $shop->code ?>/images/187-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
									</a>
 <span class="new-box">
 <span class="new-label">New</span>
 </span>
								</div>
								<div class="product-meta">
									<h5 itemprop="name">
										<a class="product-name" href="" title="Donec posuere metus" itemprop="url">
											Donec posuere metus
										</a>
									</h5>
									<p class="product-desc" itemprop="description">
										Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet...
									</p>
									<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="content_price">
 <span itemprop="price" class="price product-price">$600.00
 </span>
										<meta itemprop="priceCurrency" content="1">
									</div>
								</div>
							</div>



							<div class="product-container clearfix">
								<div class="image ">
									<a class="product_img_link" href="" title="Morbi vitae cons" itemprop="url">
										<img class="replace-2x img-responsive" src="assets/<?php echo $shop->code ?>/images/168-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
									</a>
 <span class="new-box">
 <span class="new-label">New</span>
 </span>
								</div>
								<div class="product-meta">
									<h5 itemprop="name">
										<a class="product-name" href="" title="Morbi vitae cons" itemprop="url">
											Morbi vitae cons
										</a>
									</h5>
									<p class="product-desc" itemprop="description">
										Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet...
									</p>
									<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="content_price">
										<span itemprop="price" class="price product-price">$550.00</span>
										<meta itemprop="priceCurrency" content="1">
									</div>
								</div>
							</div>



							<div class="product-container clearfix">
								<div class="image ">
									<a class="product_img_link" href="" title="Integer sit am" itemprop="url">
										<img class="replace-2x img-responsive" src="assets/<?php echo $shop->code ?>/images/170-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
									</a>
 <span class="new-box">
 <span class="new-label">New</span>
 </span>
								</div>
								<div class="product-meta">
									<h5 itemprop="name">
										<a class="product-name" href="" title="Integer sit am" itemprop="url">
											Integer sit am
										</a>
									</h5>
									<p class="product-desc" itemprop="description">
										Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet...
									</p>
									<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="content_price">
 <span itemprop="price" class="price product-price">$20.50
 </span>
										<meta itemprop="priceCurrency" content="1">
									</div>
								</div>
							</div>


						</div>



					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="mega-col col-sm-3">
		<div class="mega-col-inner ">
			<div class="leo-widget">
				<div class="widget-html">
					<div class="menu-title">
						Morbi ipsum
					</div>
					<div class="widget-inner">
						<div class="menu-content">
							<p><img src="assets/<?php echo $shop->code ?>/images/adv.jpg" alt="" width="207" height="118">
							</p>
							<p><a href="">Mauris in erat justo nullam ac urna eu felis dapibus condimentum sit amet a sed ut imperdiet nisi.</a>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>
	<div class="row"></div>
	</div>
	</div>
	</li>
	<li class=" parent dropdown aligned-left ">
		<a href="" class="dropdown-toggle has-category" data-toggle="dropdown" target="_self"><span class="menu-title">Community</span><b class="caret"></b></a>
		<div class="dropdown-sub dropdown-menu" style="width:684px">
			<div class="dropdown-menu-inner">
				<div class="row">
					<div class="mega-col col-sm-3">
						<div class="mega-col-inner ">
							<div class="leo-widget">
								<div class="widget-links">
									<div class="menu-title">
										Custom Link
									</div>
									<div class="widget-inner">
										<div id="tabs1060995877" class="panel-group">
											<ul class="nav-links">

												<li><a href="">Proin ac sapien ut</a>
												</li>

												<li><a href="">Headphones</a>
												</li>

												<li><a href="">Donec magna diam</a>
												</li>

												<li><a href="">Module Position</a>
												</li>

												<li><a href="">Fully Loaded</a>
												</li>

												<li><a href="">Donec magna diam</a>
												</li>

												<li>
													<a href=""></a>
												</li>

												<li>
													<a href=""></a>
												</li>

												<li>
													<a href=""></a>
												</li>

												<li>
													<a href=""></a>
												</li>
											</ul>
										</div>
									</div>
								</div>


							</div>
						</div>
					</div>
					<div class="mega-col col-sm-5">
						<div class="mega-col-inner ">
							<div class="leo-widget">
								<div class="widget-video">
									<div class="menu-title">
										Leo Framework
									</div>
									<div class="widget-inner">
										<iframe width="230" height="200" src="temp.html" frameborder="0" allowfullscreen=""></iframe>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="mega-col col-sm-4">
						<div class="mega-col-inner ">
							<div class="leo-widget">
								<div class="widget-links">
									<div class="menu-title">
										Link Guide
									</div>
									<div class="widget-inner">
										<div id="tabs2082739320" class="panel-group">
											<ul class="nav-links">

												<li><a href="">Leo Template Control Panel</a>
												</li>

												<li><a href="">Leo Mega Menu Module</a>
												</li>

												<li><a href="">Leo Slider Layer Module</a>
												</li>

												<li><a href="">Leo Framework</a>
												</li>

												<li><a href=""> Install Prestashop 1.6</a>
												</li>

												<li><a href="">Guide Theme</a>
												</li>

												<li>
													<a href=""></a>
												</li>

												<li>
													<a href=""></a>
												</li>

												<li>
													<a href=""></a>
												</li>

												<li>
													<a href=""></a>
												</li>
											</ul>
										</div>
									</div>
								</div>


							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</li>
	<li class=" parent dropdown aligned-fullwidth ">
	<a href="" class="dropdown-toggle has-category" data-toggle="dropdown" target="_self"><span class="menu-title">Shop</span><b class="caret"></b></a>
	<div class="dropdown-sub dropdown-menu" style="width:691px">
	<div class="dropdown-menu-inner">
	<div class="row">
	<div class="mega-col col-sm-3">
		<div class="mega-col-inner ">
			<div class="leo-widget">
				<div class="widget-links">
					<div class="menu-title">
						Block Link
					</div>
					<div class="widget-inner">
						<div id="tabs1928489512" class="panel-group">
							<ul class="nav-links">

								<li><a href="">Vivamus non nisl ut</a>
								</li>

								<li><a href="">Custom Module</a>
								</li>

								<li><a href="">Typography</a>
								</li>

								<li><a href="">Proin ac sapien ut</a>
								</li>

								<li><a href="">Typography</a>
								</li>

								<li><a href="">Donec magna diam</a>
								</li>

								<li>
									<a href=""></a>
								</li>

								<li>
									<a href=""></a>
								</li>

								<li>
									<a href=""></a>
								</li>

								<li>
									<a href=""></a>
								</li>
							</ul>
						</div>
					</div>
				</div>


			</div>
		</div>
	</div>
	<div class="mega-col col-sm-3">
		<div class="mega-col-inner ">
			<div class="leo-widget">
				<div class="widget-links">
					<div class="menu-title">
						Block Link
					</div>
					<div class="widget-inner">
						<div id="tabs810973445" class="panel-group">
							<ul class="nav-links">

								<li><a href="">Vivamus non nisl ut</a>
								</li>

								<li><a href="">Custom Module</a>
								</li>

								<li><a href="">Typography</a>
								</li>

								<li><a href="">Proin ac sapien ut</a>
								</li>

								<li><a href="">Typography</a>
								</li>

								<li><a href="">Donec magna diam</a>
								</li>

								<li>
									<a href=""></a>
								</li>

								<li>
									<a href=""></a>
								</li>

								<li>
									<a href=""></a>
								</li>

								<li>
									<a href=""></a>
								</li>
							</ul>
						</div>
					</div>
				</div>


			</div>
		</div>
	</div>
	<div class="mega-col col-sm-3">
		<div class="mega-col-inner ">
			<div class="leo-widget">
				<div class="widget-products">
					<div class="menu-title">
						New product
					</div>
					<div class="widget-inner">

						<div class="product-block">
							<div class="product-container clearfix">
								<div class="image ">
									<a class="product_img_link" href="" title="Donec posuere metus" itemprop="url">
										<img class="replace-2x img-responsive" src="assets/<?php echo $shop->code ?>/images/187-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
									</a>
 <span class="new-box">
 <span class="new-label">New</span>
 </span>
								</div>
								<div class="product-meta">
									<h5 itemprop="name">
										<a class="product-name" href="" title="Donec posuere metus" itemprop="url">
											Donec posuere metus
										</a>
									</h5>
									<p class="product-desc" itemprop="description">
										Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet...
									</p>
									<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="content_price">
										<span itemprop="price" class="price product-price">$600.00</span>
										<meta itemprop="priceCurrency" content="1">
									</div>
								</div>
							</div>



							<div class="product-container clearfix">
								<div class="image ">
									<a class="product_img_link" href="" title="Morbi vitae cons" itemprop="url">
										<img class="replace-2x img-responsive" src="assets/<?php echo $shop->code ?>/images/168-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
									</a>
 <span class="new-box">
 <span class="new-label">New</span>
 </span>
								</div>
								<div class="product-meta">
									<h5 itemprop="name">
										<a class="product-name" href="" title="Morbi vitae cons" itemprop="url">
											Morbi vitae cons
										</a>
									</h5>
									<p class="product-desc" itemprop="description">
										Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet...
									</p>
									<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="content_price">
 <span itemprop="price" class="price product-price">$550.00
 </span>
										<meta itemprop="priceCurrency" content="1">
									</div>
								</div>
							</div>



							<div class="product-container clearfix">
								<div class="image ">
									<a class="product_img_link" href="" title="Integer sit am" itemprop="url">
										<img class="replace-2x img-responsive" src="assets/<?php echo $shop->code ?>/images/170-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
									</a>
 <span class="new-box">
 <span class="new-label">New</span>
 </span>
								</div>
								<div class="product-meta">
									<h5 itemprop="name">
										<a class="product-name" href="" title="Integer sit am" itemprop="url">
											Integer sit am
										</a>
									</h5>
									<p class="product-desc" itemprop="description">
										Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet...
									</p>
									<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="content_price">
 <span itemprop="price" class="price product-price">$20.50
 </span>
										<meta itemprop="priceCurrency" content="1">
									</div>
								</div>
							</div>


						</div>



					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="mega-col col-sm-3">
		<div class="mega-col-inner ">
			<div class="leo-widget">
				<div class="widget-html">
					<div class="menu-title">
						Morbi ipsum
					</div>
					<div class="widget-inner">
						<div class="menu-content">
							<p><img src="assets/<?php echo $shop->code ?>/images/adv.jpg" alt="" width="207" height="118">
							</p>
							<p><a href="">Mauris in erat justo nullam ac urna eu felis dapibus condimentum sit amet a sed ut imperdiet nisi.</a>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>
	<div class="row">
		<div class="mega-col col-sm-12">
			<div class="mega-col-inner ">
				<div class="leo-widget">
					<div class="widget-manufacture">
						<div class="widget-inner">
							<div class="manu-logo">
								<a href="" title="view products">
									<img src="assets/<?php echo $shop->code ?>/images/11-leo_manu_menu.jpg" alt=""> </a>
								<a href="" title="view products">
									<img src="assets/<?php echo $shop->code ?>/images/12-leo_manu_menu.jpg" alt=""> </a>
								<a href="" title="view products">
									<img src="assets/<?php echo $shop->code ?>/images/5-leo_manu_menu.jpg" alt=""> </a>
								<a href="" title="view products">
									<img src="assets/<?php echo $shop->code ?>/images/6-leo_manu_menu.jpg" alt=""> </a>
								<a href="" title="view products">
									<img src="assets/<?php echo $shop->code ?>/images/7-leo_manu_menu.jpg" alt=""> </a>
								<a href="" title="view products">
									<img src="assets/<?php echo $shop->code ?>/images/9-leo_manu_menu.jpg" alt=""> </a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>
	</div>
	</li>
	<li class="parent dropdown "><a class="dropdown-toggle has-category" data-toggle="dropdown" href="" target="_self"><span class="menu-title">Delivery</span><b class="caret"></b></a>
		<div class="dropdown-menu level1" style="width:230px">
			<div class="dropdown-menu-inner">
				<div class="row">
					<div class="mega-col col-sm-12" data-type="menu">
						<div class="mega-col-inner ">
							<ul>
								<li class=" "><a href=""><span class="menu-title">Lorem ipsum dolor sit</span></a>
								</li>
								<li class="parent dropdown-submenu "><a class="dropdown-toggle" data-toggle="dropdown" href=""><span class="menu-title">Nulla quis felis at sapien</span><b class="caret"></b></a>
									<div class="dropdown-menu level2" style="width:250px">
										<div class="dropdown-menu-inner">
											<div class="row">
												<div class="mega-col col-sm-12" data-type="menu">
													<div class="mega-col-inner ">
														<ul>
															<li class=" "><a href=""><span class="menu-title">Lorem ipsum dolor sit</span></a>
															</li>
															<li class=" "><a href=""><span class="menu-title">Lorem ipsum dolor</span></a>
															</li>
															<li class=" "><a href=""><span class="menu-title">Proin ac sapien ut</span></a>
															</li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div>
								</li>
								<li class=" "><a href=""><span class="menu-title">Lorem ipsum dolor sit</span></a>
								</li>
								<li class=" "><a href=""><span class="menu-title">Vivamus non nisl ut</span></a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</li>
	<li class="">
		<a href="" target="_self" class="has-category"><span class="menu-title">About us</span></a>
	</li>
	</ul></nav></section>
</body>
</html>