<?php use Phalcon\Tag as Tag; ?>
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7 " lang="en"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8 ie7" lang="en"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9 ie8" lang="en"><![endif]-->
<!--[if gt IE 8]> <html class="no-js ie9" lang="en"><![endif]-->
<html lang="en" class="">

<head>
	<meta charset='utf-8'>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta http-equiv="Content-Language" content="en">
	<meta name="description" content="">
	<meta name="generator" content="">
	<meta name="robots" content="index,follow">
	<meta name="viewport" content="width=device-width, minimum-scale=0.25, maximum-scale=1.6, initial-scale=1.0">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<?php
	Tag::setTitle('Leo Fashion Store');
	echo Tag::getTitle();
	echo Tag::stylesheetLink('http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/bootstrap(1).css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/global.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/highdpi.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/responsive-tables.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/uniform.default.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/jquery.fancybox.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/blockcart.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/blockcategories.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/blockcurrencies.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/blocklanguages.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/blocknewsletter.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/blockspecials.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/blocktags.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/blockuserinfo.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/blockviewed.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/paneltool.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/colorpicker.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/megamenu.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/typo.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/styles.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/hooks.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/blockwishlist.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/productcomments.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/jquery.autocomplete.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/product_list.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/blocksearch.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/leocustomajax.css');
	echo Tag::stylesheetLink('assets/' . $shop->code . '/css/comparator.css');
	?>
	<script type="text/javascript">
		var CUSTOMIZE_TEXTFIELD = 1;
		var FancyboxI18nClose = 'Close';
		var FancyboxI18nNext = 'Next';
		var FancyboxI18nPrev = 'Previous';
		var added_to_wishlist = 'Added to your wishlist.';
		var ajax_allowed = true;
		var ajaxsearch = true;
		var baseDir = '/';
		var baseUri = '/index.php';
		var blocksearch_type = 'top';
		var contentOnly = false;
		var customizationIdMessage = 'Customization #';
		var delete_txt = 'Delete';
		var displayList = false;
		var freeProductTranslation = 'Free!';
		var freeShippingTranslation = 'Free shipping!';
		var generated_date = 1413191597;
		var id_lang = 1;
		var img_dir = '/images/';
		var instantsearch = false;
		var isGuest = 0;
		var isLogged = 0;
		var loggin_required = 'You must be logged in to manage your wishlist.';
		var mywishlist_url = '';
		var page_name = 'index';
		var placeholder_blocknewsletter = 'Enter your e-mail';
		var priceDisplayMethod = 1;
		var priceDisplayPrecision = 2;
		var quickView = true;
		var removingLinkText = 'remove this product from my cart';
		var roundMode = 2;
		var search_url = '';
		var static_token = '';
		var token = '';
		var usingSecureMode = false;
		var wishlistProductsIds = false;
	</script>
	<?php
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/jquery-1.11.0.min.js');
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/jquery-migrate-1.2.1.min.js');
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/jquery.easing.js');
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/tools.js');
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/global.js');
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/10-bootstrap.min.js');
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/15-jquery.total-storage.min.js');
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/15-jquery.uniform-modified.js');
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/jquery.fancybox.js');
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/products-comparison.js');
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/ajax-cart.js');
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/jquery.scrollTo(1).js');
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/jquery.serialScroll.js');
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/treeManagement.js');
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/blocknewsletter.js');
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/colorpicker.js');
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/paneltool.js');
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/jquery.themepunch.plugins.min.js');
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/jquery.themepunch.revolution.min.js');
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/ajax-wishlist.js');
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/jquery.autocomplete.js');
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/blocksearch.js');
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/leocustomajax.js');
	echo Tag::javascriptInclude('assets/' . $shop->code . '/js/countdown.js');
	?>
	<!--[if IE 8]>
	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
	<![endif]-->
</head>
<body id="index" class="index hide-left-column hide-right-column lang_en fullwidth">
<section id="page" data-column="col-xs-12 col-sm-12 col-md-3" data-type="grid">
	<!-- Header -->
	<?php $this->partial('partials/header'); ?>

	<!-- Top Navigation -->
	<?php $this->partial('partials/topnavigation', array('categories' => $categories, 'newProducts' => $newProducts)); ?>

		<?php echo $this->getContent(); ?>

<!-- Footer -->
	<?php $this->partial('partials/footer'); ?>
<!-- .footer-container -->
</section>
<!-- #page -->
</body>

</html>