<footer id="footer" class="footer-container">
<section id="footertop" class="footer-top">
	<div class="container">
		<div class="row">
			<div class="widget col-lg-12 col-md-12 col-sm-12 col-xs-12 col-sp-12 hidden-md hidden-xs hidden-sm hidden-sp">
				<div class="widget-manufacture block">
					<div class="block_content">
						<div class="carousel slide" id="manucarousel">

							<a class="carousel-control left" href="#manucarousel" data-slide="prev">‹</a>
							<a class="carousel-control right" href="#manucarousel" data-slide="next">›</a>
							<div class="carousel-inner">
								<div class="item active">
									<div class="row">
										<div class="logo-manu col-md-2 col-xs-12">
											<a href="" title="view products">
												<?=$this->tag->image(array(
													'assets/'.$shop->code.'/images/11-manu_default.jpg',
												));?>
											</a>
										</div>
										<div class="logo-manu col-md-2 col-xs-12">
											<a href="" title="view products">
												<?=$this->tag->image(array(
													'assets/'.$shop->code.'/images/12-manu_default.jpg',
												));?>
											</a>
										</div>
										<div class="logo-manu col-md-2 col-xs-12">
											<a href="" title="view products">
												<?=$this->tag->image(array(
													'assets/'.$shop->code.'/images/5-manu_default.jpg',
												));?>
											</a>
										</div>
										<div class="logo-manu col-md-2 col-xs-12">
											<a href="" title="view products">
												<?=$this->tag->image(array(
													'assets/'.$shop->code.'/images/6-manu_default.jpg',
												));?>
											</a>
										</div>
										<div class="logo-manu col-md-2 col-xs-12">
											<a href="" title="view products">
												<?=$this->tag->image(array(
													'assets/'.$shop->code.'/images/7-manu_default.jpg',
												));?>
											</a>
										</div>
										<div class="logo-manu col-md-2 col-xs-12">
											<a href="" title="view products">
												<?=$this->tag->image(array(
													'assets/'.$shop->code.'/images/9-manu_default.jpg',
												));?>
											</a>
										</div>
									</div>
								</div>
								<div class="item ">
									<div class="row">
										<div class="logo-manu col-md-2 col-xs-12">
											<a href="" title="view products">
												<?=$this->tag->image(array(
													'assets/'.$shop->code.'/images/10-manu_default.jpg',
												));?>
											</a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
</section>
<!-- #footertop -->
<section id="footercenter" class="footer-center">
	<div class="container">
		<div class="footercenter_container">
			<div class="row">
				<script type="text/javascript">
					var leoOption = {
						productNumber: 1,
						productInfo: 1,
						productTran: 1,
						productCdown: 1,
						productColor: 1
					}
					$(document)
						.ready(function() {
//							var leoCustomAjax = new $.LeoCustomAjax();
//							leoCustomAjax.processAjax();
						});
				</script>
				<div class="widget col-lg-9 col-md-9 col-sm-12 col-xs-9-6 col-sp-12">
					<div class="widget-html block">
						<div class="block_content">
							<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
								<div class="box logo-ft">
									<?=$this->tag->image(array(
										'assets/'.$shop->code.'/images/logo_footer.png',
									));?>
								</div>
							</div>
							<div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
								<h3 class="title_block">About The Shop</h3>
								<div class="about">
									<p>Sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio.</p>
								</div>
							</div>
						</div>
					</div>
				</div>

				<section id="social_block" class="col-md-3 col-sm-12">
					<h4>FOLLOW US ON SOCIAL</h4>
					<ul>
						<li class="facebook">
							<a target="_blank" href="http://www.facebook.com/prestashop">
								<span>Facebook</span>
							</a>
						</li>
						<li class="twitter">
							<a target="_blank" href="http://www.twitter.com/prestashop">
								<span>Twitter</span>
							</a>
						</li>
						<li class="rss">
							<a target="_blank" href="http://www.prestashop.com/blog/en/feed/">
								<span>RSS</span>
							</a>
						</li>
						<li class="youtube">
							<a href="https://www.youtube.com/">
								<span>Youtube</span>
							</a>
						</li>
						<li class="google-plus">
							<a href="https://plus.google.com/">
								<span>Google Plus</span>
							</a>
						</li>
					</ul>
				</section>
				<div class="clearfix"></div>

			</div>
		</div>
	</div>
</section>
<!-- #footercenter -->
<section id="footerbottom" class="footer-bottom">
	<div class="container">
		<div class="row ">
			<div class="widget col-lg-3 col-md-3 col-sm-6 col-xs-12 col-sp-12">
				<div class="widget-html block">
					<h4 class="title_block">
						About us
					</h4>
					<div class="block_content">
						<div class="block_content">
							<ul class="widget-items">
								<li class="widget-text">
									<div class="box-services">
										<p>Monday - Friday .................. 8.00 to 18.00</p>
										<p>Saturday ......................... 9.00 to 21.00</p>
										<p>Sunday ........................... 10.00 to 21.00</p>
										<span class="iconbox pull-left"><span class="fa fa-phone">&nbsp;</span></span>
										<div class="media-body">Call us:&nbsp;<span class="h4">0123 456 789</span>
										</div>
									</div>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<div class="widget col-lg-2 col-md-2 col-sm-6 col-xs-12 col-sp-12">
				<div class="widget-links block">
					<h4 class="title_block">
						Information
					</h4>
					<div class="block_content">
						<div id="tabs995003407" class="panel-group">
							<ul class="nav-links">

								<li><a href="">Best sellers</a>
								</li>

								<li><a href="">Specials</a>
								</li>

								<li><a href="">New products</a>
								</li>

								<li><a href="">Our stores</a>
								</li>

								<li><a href="">Sitemap</a>
								</li>
							</ul>
						</div>
					</div>
				</div>


			</div>
			<div class="widget col-lg-2 col-md-2 col-sm-6 col-xs-12 col-sp-12">
				<div class="widget-links block">
					<h4 class="title_block">
						Information
					</h4>
					<div class="block_content">
						<div id="tabs1868157759" class="panel-group">
							<ul class="nav-links">

								<li><a href="">Best sellers</a>
								</li>

								<li><a href="">Specials</a>
								</li>

								<li><a href="">New products</a>
								</li>

								<li><a href="">Our stores</a>
								</li>

								<li><a href="">Sitemap</a>
								</li>
							</ul>
						</div>
					</div>
				</div>


			</div>
			<div class="widget col-lg-2 col-md-2 col-sm-6 col-xs-12 col-sp-12">
				<div class="widget-links block">
					<h4 class="title_block">
						My account
					</h4>
					<div class="block_content">
						<div id="tabs69106804" class="panel-group">
							<ul class="nav-links">

								<li><a href="">My orders</a>
								</li>

								<li><a href="">My credit slips</a>
								</li>

								<li><a href="">My addresses</a>
								</li>

								<li><a href="">My personal info</a>
								</li>

								<li><a href="">My vouchers</a>
								</li>
							</ul>
						</div>
					</div>
				</div>


			</div>
			<div class="widget col-lg-3 col-md-3 col-sm-6 col-xs-12 col-sp-12">
				<div class="widget-html block">
					<h4 class="title_block">
						Address
					</h4>
					<div class="block_content">
						<address><strong>Warehouse Offices</strong><br>12345 Street name, California, USA<br>0123 456 789 / 0123 456 788</address><address><strong>Retail Store</strong><br>54321 Street name, California, USA<br>0123 456 789 / 0123 456 788</address>
					</div>
				</div>
			</div>
		</div>


	</div>
</section>
<!-- #footerbottom -->
<section id="footernav" class="footer-nav">
	<div class="container">
		<div class="inner">
			<div class="row">
				<div id="poweredby" class="col-md-12 col-xs-12">
					Copyright 2014 Powered by PrestaShop. All Rights Reserved.
					<br>Designed By <span>LeoTheme</span>
				</div>
				<!-- #poweredby -->
			</div>
		</div>
	</div>
</section>
</footer>