<header id="header">
<section class="header-container">
<div id="topbar">
<div class="banner">
	<div class="container">
		<div class="row">

		</div>

	</div>
</div>
<div class="nav">
<div class="container">
<div class="row">
<nav><script type="text/javascript">
		/* Blockusreinfo */

		$(document).ready( function(){
			$(".leo-groupe").each( function(){
				var content = $(".groupe-content");
				$(".groupe-btn", this ).click( function(){
					content.toggleClass("eshow");
				}) ;
			} );

			$(window).resize(function() {
				if( $(window).width() > 600 ){
					$(".groupe-content").removeClass('eshow');
				}
			});
		});
	</script>
	<!-- Block user information module NAV -->
	<div class="leo-groupe g-dropdown">
		<a class="groupe-btn visible-xs">Quick link <span class="caret"></span></a>
		<div id="header_user_info" class="pull-left groupe-content hidden-xs">
			<ul class="links">
				<li><a href="" title="View my customer account" rel="nofollow"> Your Account</a>
				</li>
				<li><a href="" title="My wishlists">My wishlists</a>
				</li>
				<li><a href="" title="Login to your customer account" class="login" rel="nofollow">Sign in</a>
				</li>
				<li><a href="" title="Register account" class="register" rel="nofollow">Register</a>
				</li>
			</ul>
		</div>
	</div>
	<!-- /Block usmodule NAV -->
	<!-- Block languages module -->
	<div id="languages-block-top" class="languages-block">
		<?php if(!empty($languages)): ?>
			<div class="current">
				<?=$this->tag->image(array('assets/'.$shop->code.'/images/'.$language.'.jpg', "alt" => $language));?>
				<span><?=$languages[$language];?></span>
			</div>
			<ul id="first-languages" class="languages-block_ul toogle_content">
				<?foreach($languages as $code => $name): ?>
					<li <?=($code == $language) ? 'class="selected"' : ''?> onclick="Common.redirect('/language/<?=$code;?>');">
						<?=$this->tag->image(array('assets/'.$shop->code.'/images/'.$code.'.jpg', "alt" => $name));?>
						<span><?=$name;?></span>
					</li>
				<?php endforeach; ?>
			</ul>
		<?endif;?>
	</div>
	<!-- /Block languages module -->
	<!-- Block currencies module -->
	<div id="currencies-block-top" class="dropdown_topbar">
		<form id="setCurrency" action="index.htm" method="post">
			<div class="current">
				<input type="hidden" name="id_currency" id="id_currency" value="">
				<input type="hidden" name="SubmitCurrency" value=""> USD </div>
			<ul id="first-currencies" class="currencies_ul toogle_content">
				<li class="selected">
					<a href="javascript:setCurrency(1);" rel="nofollow" title="Dollar">
						$&nbsp;Dollar
					</a>
				</li>
				<li>
					<a href="javascript:setCurrency(2);" rel="nofollow" title="Euros">
						€&nbsp;Euros
					</a>
				</li>
			</ul>
		</form>
	</div>
	<!-- /Block currencies module -->
</nav>
<div id="header_right">
	<!-- MODULE Block cart -->
	<div class="pull-right cart-top clearfix">
		<div class="shopping_cart">
			<a href="" title="View my shopping cart" rel="nofollow">
				<span class="title_cart">Cart</span>
				<span class="ajax_cart_quantity">1</span>
				<span class="ajax_cart_product_txt">Item</span>
				<span class="ajax_cart_product_txt_s unvisible">Items</span>
 <span class="ajax_cart_total">$450.00
 </span>
 <span class="ajax_cart_no_product unvisible">
 0 <span>Item</span> <span class="price"> - $0.00</span>
 </span>
			</a>
			<div class="cart_block block exclusive" style="display: none;">
				<div class="block_content">
					<!-- block list of products -->
					<div class="cart_block_list">
						<dl class="products">
							<dt data-id="cart_block_product_11_64_0" class="first_item">
								<a class="cart-images" href="" title="Aenean"><img src="assets/<?php echo $shop->code ?>/images/176-cart_default.jpg" alt="Aenean"></a>
							<div class="cart-info">
								<div class="product-name">
									<span class="quantity-formated"><span class="quantity">1</span>&nbsp;x&nbsp;</span><a class="cart_block_product_name" href="#/size-s/color-yellow" title="Aenean">Aenean</a>
								</div>
								<div class="product-atributes">
									<a href="#/size-s/color-yellow" title="Product detail">Yellow, S</a>
								</div>
								<span class="price">$450.00</span>
							</div>
							<span class="remove_link"><a class="ajax_cart_block_remove_link" href="" rel="nofollow" title="remove this product from my cart">&nbsp;</a></span>
							</dt>
							<dd data-id="cart_block_combination_of_11_64_0" class="first_item">
								<!-- Customizable datas -->
							</dd>
						</dl>
						<p class="cart_block_no_products unvisible">
							No products
						</p>
						<div class="cart-prices">
							<div class="cart-prices-line first-line"><span class="price cart_block_shipping_cost ajax_cart_shipping_cost">$2.00</span>
								<span>Shipping</span>
							</div>
							<div class="cart-prices-line last-line">
								<span class="price cart_block_total ajax_block_cart_total">$452.00</span>
								<span>Total</span>
							</div>
						</div>
						<p class="cart-buttons">
							<a id="button_order_cart" class="btn btn-default button button-small" href="" title="Check out" rel="nofollow">
								<span>Check out<i class="icon-chevron-right right"></i></span>
							</a>
						</p>
					</div>
				</div>
			</div>
			<!-- .cart_block -->
		</div>
	</div>

	<div id="layer_cart">
		<div class="clearfix">
			<div class="layer_cart_product col-xs-12 col-md-6">
				<span class="cross" title="Close window"></span>
				<h2>
					<i class="icon-ok"></i>Product successfully added to your shopping cart
				</h2>
				<div class="product-image-container layer_cart_img">
				</div>
				<div class="layer_cart_product_info">
					<span id="layer_cart_product_title" class="product-name"></span>
					<span id="layer_cart_product_attributes"></span>
					<div>
						<strong class="dark">Quantity</strong>
						<span id="layer_cart_product_quantity"></span>
					</div>
					<div>
						<strong class="dark">Total</strong>
						<span id="layer_cart_product_price"></span>
					</div>
				</div>
			</div>
			<div class="layer_cart_cart col-xs-12 col-md-6">
				<h2>
					<!-- Plural Case [both cases are needed because page may be updated in Javascript] -->
					<span class="ajax_cart_product_txt_s unvisible">
						There are <span class="ajax_cart_quantity">0</span> items in your cart.
					</span>
					<!-- Singular Case [both cases are needed because page may be updated in Javascript] -->
					<span class="ajax_cart_product_txt ">
						There is 1 item in your cart.
					</span>
				</h2>

				<div class="layer_cart_row">
					<strong class="dark">
						Total products
						(tax excl.)
					</strong>
					<span class="ajax_block_products_total">
											</span>
				</div>

				<div class="layer_cart_row">
					<strong class="dark">
						Total shipping&nbsp;(tax excl.)</strong>
					<span class="ajax_cart_shipping_cost">Free shipping!</span>
				</div>
				<div class="layer_cart_row">
					<strong class="dark">
						Total
						(tax excl.)
					</strong>
					<span class="ajax_block_cart_total"></span>
				</div>
				<div class="button-container">
					<span class="continue btn btn-default button exclusive-medium" title="Continue shopping">
						<span>
							<i class="icon-chevron-left left"></i>Continue shopping
						</span>
					</span>
					<a class="btn btn-default button button-medium"	href="" title="Proceed to checkout" rel="nofollow">
						<span>
							Proceed to checkout<i class="icon-chevron-right right"></i>
						</span>
					</a>
				</div>
			</div>
		</div>
		<div class="crossseling"></div>
	</div>
	<!-- #layer_cart -->
	<div class="layer_cart_overlay"></div>

	<!-- /MODULE Block cart -->
	<script type="text/javascript">
		$(document).ready(function() {
			//search
			$("#search_block_top")
				.each(function() {
					var content = $(".groupe");
					$(".groupe-btn", this)
						.click(function() {
							content.toggleClass("show");
						});
				});
		});
	</script>
	<!-- Block search module TOP -->
	<div id="search_block_top" class="pull-right clearfix">
		<a class="groupe-btn dropdown hidden-md hidden-lg" title="Search" href=""></a>
		<form id="searchbox" method="get"  class="groupe">
			<input type="hidden" name="controller" value="search">
			<input type="hidden" name="orderby" value="position">
			<input type="hidden" name="orderway" value="desc">
			<input class="search_query form-control ac_input" type="text" id="search_query_top" name="search_query" placeholder="Search" value="" autocomplete="off">
			<button type="submit" name="submit_search" class="btn btn-default button-search">
				<span>Search</span>
			</button>
		</form>
	</div>
	<!-- /Block search module TOP -->
</div>
</div>
</div>
</div>
</div>
<div id="header-main">
	<div class="container">
		<div class="row">
			<div id="header_logo" class="pull-left">
				<a href="<?php echo Helpers\LocationUrls::location('/'); ?>" title="Leo Fashion Store">
					<?=$this->tag->image(array(
						'assets/'.$shop->code.'/images/leo-mobile-1399525585.jpg',
						'alt' 	=> 	$shop->name,
						'title'	=>	$shop->name,
						'class'	=>	'logo img-responsive',
						'width'	=>	155,
						'height'=>	95,
					));?>
				</a>
			</div>
		</div>
	</div>
</div>
</section>
</header>