<div id="topnavigation" class="clearfix">
<div class="container">
<nav id="cavas_menu" class="navbar navbar-default" role="navigation">
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
		<span class="sr-only">Toggle navigation</span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
	</button>
</div>
<!-- Collect the nav links, forms, and other content for toggling -->
<div id="leo-top-menu" class="collapse navbar-collapse navbar-ex1-collapse">
<ul class="nav navbar-nav megamenu">
<li class="active">
	<a href="" target="_self" class="has-category"><span class="menu-title">Home</span></a>
</li>
<li class=" parent dropdown aligned-fullwidth ">
	<a href="" class="dropdown-toggle has-category" data-toggle="dropdown" target="_self"><span class="menu-title">Categories</span><b class="caret"></b></a>
	<div class="dropdown-sub dropdown-menu" style="width:680px">
		<div class="dropdown-menu-inner">
			<div class="row">
				<div class="mega-col col-sm-3">
					<div class="mega-col-inner ">
						<div class="leo-widget">
							<div class="widget-subcategories">
								<div class="widget-inner">
									<div class="menu-title">Categories</div>
									<ul>
										<?php if(!empty($categories)) { ?>
											<?php foreach($categories as $category) { ?>
												<li class="clearfix">
													<a href="" title="Outerwear" class="img">
														<?php echo $category->name; ?>
													</a>
												</li>
											<?php } ?>
										<?php } ?>

									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="mega-col col-sm-3">
					<div class="mega-col-inner ">
						<div class="leo-widget"> </div>
						<div class="leo-widget">
							<div class="widget-products">
								<div class="menu-title">
									New product
								</div>
								<div class="widget-inner">

									<div class="product-block">
										<?php foreach($newProducts as $key => $product) { ?>
											<div class="product-container clearfix">
												<div class="image ">
													<a class="product_img_link" href="" title="Donec posuere metus" itemprop="url">
														<img class="replace-2x img-responsive" src="assets/<?php echo $shop->code ?>/images/187-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
													</a>
 <span class="new-box">
 <span class="new-label">New</span>
 </span>
												</div>
												<div class="product-meta">
													<h5 itemprop="name">
														<a class="product-name" href="" title="Donec posuere metus" itemprop="url">
															<?php echo $product->name; ?>
														</a>
													</h5>
													<p class="product-desc" itemprop="description">
														<?php echo $product->description; ?>
													</p>
													<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="content_price">
 <span itemprop="price" class="price product-price">
<?php echo $product->price; ?>
								</span>
														<meta itemprop="priceCurrency" content="1">
													</div>
												</div>
											</div>

											<?php unset($newProducts[$key]); ?>
											<?php if($key == 2)break; ?>
										<?php } ?>


									</div>



								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="mega-col col-sm-3">
					<div class="mega-col-inner ">
						<div class="leo-widget">
							<div class="widget-products">
								<div class="menu-title">
									New product
								</div>
								<div class="widget-inner">

									<div class="product-block">




										<?php foreach($newProducts as $key => $product) { ?>
											<div class="product-container clearfix">
												<div class="image ">
													<a class="product_img_link" href="" title="Donec posuere metus" itemprop="url">
														<img class="replace-2x img-responsive" src="assets/<?php echo $shop->code ?>/images/187-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
													</a>
 <span class="new-box">
 <span class="new-label">New</span>
 </span>
												</div>
												<div class="product-meta">
													<h5 itemprop="name">
														<a class="product-name" href="" title="Donec posuere metus" itemprop="url">
															<?php echo $product->name; ?>
														</a>
													</h5>
													<p class="product-desc" itemprop="description">
														<?php $product->description; ?>
													</p>
													<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="content_price">
 <span itemprop="price" class="price product-price"><?php echo $product->price; ?>
 </span>
														<meta itemprop="priceCurrency" content="1">
													</div>
												</div>
											</div>

										<?php } ?>



									</div>



								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="mega-col col-sm-3">
					<div class="mega-col-inner ">
						<div class="leo-widget">
							<div class="widget-html">
								<div class="menu-title">
									Morbi ipsum
								</div>
								<div class="widget-inner">
									<div class="menu-content">
										<p><img src="assets/<?php echo $shop->code ?>/images/adv.jpg" alt="" width="207" height="118">
										</p>
										<p><a href="">Mauris in erat justo nullam ac urna eu felis dapibus condimentum sit amet a sed ut imperdiet nisi.</a>
										</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="row"></div>
		</div>
	</div>
</li>
<li class=" parent dropdown aligned-left ">
	<a href="" class="dropdown-toggle has-category" data-toggle="dropdown" target="_self"><span class="menu-title">Community</span><b class="caret"></b></a>
	<div class="dropdown-sub dropdown-menu" style="width:684px">
		<div class="dropdown-menu-inner">
			<div class="row">
				<div class="mega-col col-sm-3">
					<div class="mega-col-inner ">
						<div class="leo-widget">
							<div class="widget-links">
								<div class="menu-title">
									Custom Link
								</div>
								<div class="widget-inner">
									<div id="tabs1060995877" class="panel-group">
										<ul class="nav-links">

											<li><a href="">Proin ac sapien ut</a>
											</li>

											<li><a href="">Headphones</a>
											</li>

											<li><a href="">Donec magna diam</a>
											</li>

											<li><a href="">Module Position</a>
											</li>

											<li><a href="">Fully Loaded</a>
											</li>

											<li><a href="">Donec magna diam</a>
											</li>

											<li>
												<a href=""></a>
											</li>

											<li>
												<a href=""></a>
											</li>

											<li>
												<a href=""></a>
											</li>

											<li>
												<a href=""></a>
											</li>
										</ul>
									</div>
								</div>
							</div>


						</div>
					</div>
				</div>
				<div class="mega-col col-sm-5">
					<div class="mega-col-inner ">
						<div class="leo-widget">
							<div class="widget-video">
								<div class="menu-title">
									Leo Framework
								</div>
								<div class="widget-inner">
									<iframe width="230" height="200" src="temp.html" frameborder="0" allowfullscreen=""></iframe>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="mega-col col-sm-4">
					<div class="mega-col-inner ">
						<div class="leo-widget">
							<div class="widget-links">
								<div class="menu-title">
									Link Guide
								</div>
								<div class="widget-inner">
									<div id="tabs2082739320" class="panel-group">
										<ul class="nav-links">

											<li><a href="">Leo Template Control Panel</a>
											</li>

											<li><a href="">Leo Mega Menu Module</a>
											</li>

											<li><a href="">Leo Slider Layer Module</a>
											</li>

											<li><a href="">Leo Framework</a>
											</li>

											<li><a href=""> Install Prestashop 1.6</a>
											</li>

											<li><a href="">Guide Theme</a>
											</li>

											<li>
												<a href=""></a>
											</li>

											<li>
												<a href=""></a>
											</li>

											<li>
												<a href=""></a>
											</li>

											<li>
												<a href=""></a>
											</li>
										</ul>
									</div>
								</div>
							</div>


						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</li>
<li class=" parent dropdown aligned-fullwidth ">
<a href="" class="dropdown-toggle has-category" data-toggle="dropdown" target="_self"><span class="menu-title">Shop</span><b class="caret"></b></a>
<div class="dropdown-sub dropdown-menu" style="width:691px">
<div class="dropdown-menu-inner">
<div class="row">
<div class="mega-col col-sm-3">
	<div class="mega-col-inner ">
		<div class="leo-widget">
			<div class="widget-links">
				<div class="menu-title">
					Block Link
				</div>
				<div class="widget-inner">
					<div id="tabs1928489512" class="panel-group">
						<ul class="nav-links">

							<li><a href="">Vivamus non nisl ut</a>
							</li>

							<li><a href="">Custom Module</a>
							</li>

							<li><a href="">Typography</a>
							</li>

							<li><a href="">Proin ac sapien ut</a>
							</li>

							<li><a href="">Typography</a>
							</li>

							<li><a href="">Donec magna diam</a>
							</li>

							<li>
								<a href=""></a>
							</li>

							<li>
								<a href=""></a>
							</li>

							<li>
								<a href=""></a>
							</li>

							<li>
								<a href=""></a>
							</li>
						</ul>
					</div>
				</div>
			</div>


		</div>
	</div>
</div>
<div class="mega-col col-sm-3">
	<div class="mega-col-inner ">
		<div class="leo-widget">
			<div class="widget-links">
				<div class="menu-title">
					Block Link
				</div>
				<div class="widget-inner">
					<div id="tabs810973445" class="panel-group">
						<ul class="nav-links">

							<li><a href="">Vivamus non nisl ut</a>
							</li>

							<li><a href="">Custom Module</a>
							</li>

							<li><a href="">Typography</a>
							</li>

							<li><a href="">Proin ac sapien ut</a>
							</li>

							<li><a href="">Typography</a>
							</li>

							<li><a href="">Donec magna diam</a>
							</li>

							<li>
								<a href=""></a>
							</li>

							<li>
								<a href=""></a>
							</li>

							<li>
								<a href=""></a>
							</li>

							<li>
								<a href=""></a>
							</li>
						</ul>
					</div>
				</div>
			</div>


		</div>
	</div>
</div>
<div class="mega-col col-sm-3">
	<div class="mega-col-inner ">
		<div class="leo-widget">
			<div class="widget-products">
				<div class="menu-title">
					New product
				</div>
				<div class="widget-inner">

					<div class="product-block">
						<div class="product-container clearfix">
							<div class="image ">
								<a class="product_img_link" href="" title="Donec posuere metus" itemprop="url">
									<img class="replace-2x img-responsive" src="assets/<?php echo $shop->code ?>/images/187-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
								</a>
 <span class="new-box">
 <span class="new-label">New</span>
 </span>
							</div>
							<div class="product-meta">
								<h5 itemprop="name">
									<a class="product-name" href="" title="Donec posuere metus" itemprop="url">
										Donec posuere metus
									</a>
								</h5>
								<p class="product-desc" itemprop="description">
									Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet...
								</p>
								<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="content_price">
									<span itemprop="price" class="price product-price">$600.00</span>
									<meta itemprop="priceCurrency" content="1">
								</div>
							</div>
						</div>



						<div class="product-container clearfix">
							<div class="image ">
								<a class="product_img_link" href="" title="Morbi vitae cons" itemprop="url">
									<img class="replace-2x img-responsive" src="assets/<?php echo $shop->code ?>/images/168-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
								</a>
 <span class="new-box">
 <span class="new-label">New</span>
 </span>
							</div>
							<div class="product-meta">
								<h5 itemprop="name">
									<a class="product-name" href="" title="Morbi vitae cons" itemprop="url">
										Morbi vitae cons
									</a>
								</h5>
								<p class="product-desc" itemprop="description">
									Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet...
								</p>
								<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="content_price">
 <span itemprop="price" class="price product-price">$550.00
 </span>
									<meta itemprop="priceCurrency" content="1">
								</div>
							</div>
						</div>



						<div class="product-container clearfix">
							<div class="image ">
								<a class="product_img_link" href="" title="Integer sit am" itemprop="url">
									<img class="replace-2x img-responsive" src="assets/<?php echo $shop->code ?>/images/170-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
								</a>
 <span class="new-box">
 <span class="new-label">New</span>
 </span>
							</div>
							<div class="product-meta">
								<h5 itemprop="name">
									<a class="product-name" href="" title="Integer sit am" itemprop="url">
										Integer sit am
									</a>
								</h5>
								<p class="product-desc" itemprop="description">
									Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet...
								</p>
								<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="content_price">
 <span itemprop="price" class="price product-price">$20.50
 </span>
									<meta itemprop="priceCurrency" content="1">
								</div>
							</div>
						</div>


					</div>



				</div>
			</div>
		</div>
	</div>
</div>
<div class="mega-col col-sm-3">
	<div class="mega-col-inner ">
		<div class="leo-widget">
			<div class="widget-html">
				<div class="menu-title">
					Morbi ipsum
				</div>
				<div class="widget-inner">
					<div class="menu-content">
						<p><img src="assets/<?php echo $shop->code ?>/images/adv.jpg" alt="" width="207" height="118">
						</p>
						<p><a href="">Mauris in erat justo nullam ac urna eu felis dapibus condimentum sit amet a sed ut imperdiet nisi.</a>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
<div class="row">
	<div class="mega-col col-sm-12">
		<div class="mega-col-inner ">
			<div class="leo-widget">
				<div class="widget-manufacture">
					<div class="widget-inner">
						<div class="manu-logo">
							<a href="" title="view products">
								<img src="assets/<?php echo $shop->code ?>/images/11-leo_manu_menu.jpg" alt=""> </a>
							<a href="" title="view products">
								<img src="assets/<?php echo $shop->code ?>/images/12-leo_manu_menu.jpg" alt=""> </a>
							<a href="" title="view products">
								<img src="assets/<?php echo $shop->code ?>/images/5-leo_manu_menu.jpg" alt=""> </a>
							<a href="" title="view products">
								<img src="assets/<?php echo $shop->code ?>/images/6-leo_manu_menu.jpg" alt=""> </a>
							<a href="" title="view products">
								<img src="assets/<?php echo $shop->code ?>/images/7-leo_manu_menu.jpg" alt=""> </a>
							<a href="" title="view products">
								<img src="assets/<?php echo $shop->code ?>/images/9-leo_manu_menu.jpg" alt=""> </a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
</div>
</li>
<li class="parent dropdown "><a class="dropdown-toggle has-category" data-toggle="dropdown" href="" target="_self"><span class="menu-title">Delivery</span><b class="caret"></b></a>
	<div class="dropdown-menu level1" style="width:230px">
		<div class="dropdown-menu-inner">
			<div class="row">
				<div class="mega-col col-sm-12" data-type="menu">
					<div class="mega-col-inner ">
						<ul>
							<li class=" "><a href=""><span class="menu-title">Lorem ipsum dolor sit</span></a>
							</li>
							<li class="parent dropdown-submenu "><a class="dropdown-toggle" data-toggle="dropdown" href=""><span class="menu-title">Nulla quis felis at sapien</span><b class="caret"></b></a>
								<div class="dropdown-menu level2" style="width:250px">
									<div class="dropdown-menu-inner">
										<div class="row">
											<div class="mega-col col-sm-12" data-type="menu">
												<div class="mega-col-inner ">
													<ul>
														<li class=" "><a href=""><span class="menu-title">Lorem ipsum dolor sit</span></a>
														</li>
														<li class=" "><a href=""><span class="menu-title">Lorem ipsum dolor</span></a>
														</li>
														<li class=" "><a href=""><span class="menu-title">Proin ac sapien ut</span></a>
														</li>
													</ul>
												</div>
											</div>
										</div>
									</div>
								</div>
							</li>
							<li class=" "><a href=""><span class="menu-title">Lorem ipsum dolor sit</span></a>
							</li>
							<li class=" "><a href=""><span class="menu-title">Vivamus non nisl ut</span></a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</li>
<li class="">
	<a href="" target="_self" class="has-category"><span class="menu-title">About us</span></a>
</li>
</ul>
</div>
</nav>
<script type="text/javascript">
	// <![CDATA[
	var current_link = "";
	//alert(request);
	var currentURL = window.location;
	currentURL = String(currentURL);
	currentURL = currentURL.replace("https://", "").replace("http://", "").replace("www.", "").replace(/#\w*/, "");
	current_link = current_link.replace("https://", "").replace("http://", "").replace("www.", "");
	isHomeMenu = 0;
	if ($("body").attr("id") == "index") isHomeMenu = 1;
	$(".megamenu > li > a").each(function() {
		menuURL = $(this).attr("href").replace("https://", "").replace("http://", "").replace("www.", "").replace(/#\w*/, "");
		if ((currentURL == menuURL) || (currentURL.replace(current_link, "") == menuURL) || isHomeMenu) {
			$(this).parent().addClass("active");
			return false;
		}
	});
	// ]]>
</script>
<script type="text/javascript">
	(function($) {
		$.fn.OffCavasmenu = function(opts) {
			// default configuration
			var config = $.extend({}, {
				opt1: null,
				text_warning_select: "Please select One to remove?",
				text_confirm_remove: "Are you sure to remove footer row?",
				JSON: null
			}, opts);
			// main function
			// initialize every element
			this.each(function() {
				var $btn = $('#cavas_menu .navbar-toggle');
				var $nav = null;
				if (!$btn.length)
					return;
				var $nav = $('<section id="off-canvas-nav"><nav class="offcanvas-mainnav" ><div id="off-canvas-button"><span class="off-canvas-nav"></span>Close</div></nav></sections>');
				var $menucontent = $($btn.data('target')).find('.megamenu').clone();
				$("body").append($nav);
				$("#off-canvas-nav .offcanvas-mainnav").append($menucontent);
				$("html")
					.addClass("off-canvas");
				$("#off-canvas-button").click(function() {
					$btn.click();
				});
				$btn.toggle(function() {
					$("body").removeClass("off-canvas-inactive").addClass("off-canvas-active");
				}, function() {
					$("body").removeClass("off-canvas-active").addClass("off-canvas-inactive");
				});
			});
			return this;
		}
	})(jQuery);
	$(document).ready(function() {
		jQuery("#cavas_menu").OffCavasmenu();
		$('#cavas_menu .navbar-toggle').click(function() {
			$('body,html').animate({
				scrollTop: 0
			}, 0);
			return false;
		});

		$(window).resize(function() {
			if ($(window).width() > 767) {
				$("body").removeClass("off-canvas-active").addClass("off-canvas-inactive");
			}
		});
	});
	$(document.body).on('click', '[data-toggle="dropdown"]', function() {
		if (!$(this).parent().hasClass('open') && this.href && this.href != '#') {
			window.location.href = this.href;
		}
	});
</script>

</div>
</div>