<tr style="height:100px;">
	<td>
		<div class="footer">
			<table>
				<tr>
					<td colspan="2" class="catalogue">
						<!-- Нижнее меню навигации -->
						<?php echo $navigation->toHtml('bottom'); ?>
						<!-- Нижнее меню навигации -->
					</td>
				</tr>
				<tr>
					<td class="copyright" width="25%">© 2007—2014 <a href="/" class="green"><?=$shop['name'];?></a></td>
					<td class="menu">
						<table>
							<tr>

								<td width="25%">
									<div class="footer-menu-item">
										<?=$this->tag->linkTo([['for' => 'about'], 'О магазине']); ?>
										<div class="submenu">
											<div class="footer-menu-item">
												<?=$this->tag->linkTo([['for' => 'about-discounts'], 'Скидки']); ?>
											</div>
											<div class="footer-menu-item">
												<?=$this->tag->linkTo([['for' => 'about-delivery'], 'Доставка']); ?>
											</div>
											<div class="footer-menu-item">
												<?=$this->tag->linkTo([['for' => 'about-return'], 'Возврат']); ?>
											</div>
											<div class="footer-menu-item">
												<?=$this->tag->linkTo([['for' => 'about-opt'], 'Опт']); ?>
											</div>
										</div>
									</div>
								</td>
								<td width="25%">
								</td>
								<td width="25%">
									<a class="green" href="#feedback">Обратная связь</a>
									<div class="phones">
										Телефоны<div style="font-size:1em; color:white;">круглосуточно, без выходных</div>														<div><span>8 800</span>100-76-34</div>
										<div><span>+7 495</span>664-23-85</div>
										<div><span>+7 812</span>309-41-84</div>
									</div>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>
	</td>
</tr>