<div class="hotline">
	<div id="hot_line_buttons">
		<div class="button" onclick="catalogue.hotLinePrev();">&#x2191;</div>
		<div class="button" onclick="catalogue.hotLineNext();">&#x2193;</div>
	</div>
	<div id="hot_line">
		<!-- inner data -->

		<!-- /inner data -->
	</div>
	<div class="micro-cart" style="display: none;" onclick="basket.get_small_basket();"><?=$layoutTranslate['CART'];?></div>
	<div class="micro-customer" onclick="global.go({url:'/customer/'})"></div>
</div>
