<!-- Облако тегов -->
<div id="tags_block_left" class="block tags_block black nobackground">
	<div class="close" onclick="$(this).parent().parent().toggleClass('hidden'); $('#tags_filter_button').removeClass('hidden');" title="Закрыть фильтры"></div>
	<div class="filters">
		<?php if(isset($request_uri)):?>
			<a class="link page isAjax reset" href="<?=$request_uri;?>">Сбросить все</a>
		<?php endif;?>

		<!-- Показываю размеры, если есть -->
		<?php if(isset($tagsCloud['sizes']) && !empty($tagsCloud['sizes'])): ?>
			<div class="group" onclick="$('.parent-of-sizes').toggle();">Размеры</div>
			<?php foreach($tagsCloud['sizes'] as $key => $val): ?>
				<div class="tag parent-of-sizes" style="display: inline-block; min-width: 20%;">
					<?php
						$url = (isset($query) && !empty($query)) ? array_merge($query, ['tags['.$val['id'].']' => $val['id']]) : ['tags['.$val['id'].']' => $val['id']];
					?>
					<label>
						<input type="checkbox" value="<?=$val['id'];?>" <?=(!empty($query['tags']) && in_array($val['id'], $query['tags'])) ? 'checked': '';?>>
							<a style="color: #777" rel="<?=$val['id'];?>" class="link page isAjax" href="?<?=urldecode(http_build_query($url)); ?>"><?=$val['name'];?>
						(<?=$val['count_products'];?>)
						</a>
					</label>
				</div>
			<?php unset($url); endforeach; ?>
		<?php endif; ?>
		<!-- /Показываю размеры, если есть -->

		<!-- Показываю теги, если есть -->
		<?php if(isset($tagsCloud['tags']) && !empty($tagsCloud['tags'])): ?>
			<?php foreach($tagsCloud['tags'] as $tags): ?>
				<?php if(!empty($tags['childs'])): ?>
					<div class="group" onclick="$('.parent-of-<?=$tags['id'];?>').toggle();"><?=$tags['name'];?></div>
					<?php foreach($tags['childs'] as $tag): ?>
						<?php if(is_array($tag)): ?>
							<div class="tag parent-of-<?=$tags['id'];?>">
								<?php
									$url = (isset($query) && !empty($query)) ? array_merge($query, ['tags['.$tag['id'].']' => $tag['id']]) : ['tags['.$tag['id'].']' => $tag['id']];
								?>
								<label>
									<input type="checkbox" value="<?=$tag['id'];?>" <?=(!empty($query['tags']) && in_array($tag['id'], $query['tags'])) ? 'checked': '';?>>
										<a style="color: #777" rel="<?=$tag['id'];?>" class="link page isAjax" href="?<?=urldecode(http_build_query($url)); ?>"><?=$tag['name'];?>
											(<?=$tag['count_products'];?>)
										</a>
								</label>
							</div>
						<?php endif; ?>
					<?php unset($url); endforeach; ?>
				<?php endif; ?>
			<?php endforeach; ?>
		<?php endif; ?>
		<!-- /Показываю теги, если есть -->

		<!-- Показываю бренды, если есть -->
			<?php if(isset($tagsCloud['brands']) && !empty($tagsCloud['brands'])): ?>
				<div class="group" onclick="$('.parent-of-brands').toggle();">Бренды</div>
				<?php foreach($tagsCloud['brands'] as $brand): ?>
					<?php if(is_array($brand)): ?>
						<div class="tag parent-of-brands">
							<label>
								<label>
									<?php
										$url = (isset($query) && !empty($query)) ? array_merge($query, ['brands['.$brand['id'].']' => $brand['id']]) : ['brands['.$brand['id'].']' => $brand['id']];
									?>
									<input type="checkbox" value="<?=$brand['id'];?>" <?=(!empty($query['brands']) && in_array($brand['id'], $query['brands'])) ? 'checked': '';?>>
									<a style="color: #777" rel="<?=$brand['id'];?>" class="link page isAjax" href="?<?=urldecode(http_build_query($url)); ?>"><?=$brand['name'];?>
											(<?=$brand['count_products'];?>)
										</a>
								</label>
						</div>
					<?php endif; ?>
				<?php unset($url); endforeach; ?>
			<?php endif; ?>
		<!-- /Показываю бренды, если есть -->
	</div>
</div>
<!-- /Облако тегов -->

<script>
	$(function() {

		$("a.link.page.isAjax").on('click', function(e) {

			e.preventDefault();
			global.showStatus('common.loading');

			// делаю отметки при клике на ссылку чекбокса
			var checkBoxes = $(this).prev(),
				rel = $(this).attr('rel'),
				currentURL	= window.location.pathname +$(this).attr('href');

				checkBoxes.prop("checked", !checkBoxes.prop("checked"));

			if(!checkBoxes.is(':checked'))	// снимаю галочку
			{
				currentURL = document.URL;
				var currentArrayUrl = URLToArray(currentURL);
				console.log(currentArrayUrl);
				clearUrl(currentArrayUrl, rel);
				console.log(currentArrayUrl);
				currentQueryString = ArrayToURL(currentArrayUrl);
				console.log(currentQueryString);
				currentURL = window.location.pathname+'?'+currentQueryString;
				console.log(currentURL);
			}

			$.getJSON(currentURL, function(data) {
				if(data.response.length)
					$(renderItems).html(data.response);
				window.history.pushState("","", currentURL);
				global.hideStatus('common.loading');
			});
		});
	});


	function URLToArray(url) {
		var request = {};
		var pairs = url.substring(url.indexOf('?') + 1).split('&');
		for (var i = 0; i < pairs.length; i++) {
			var pair = pairs[i].split('=');
			request[decodeURIComponent(pair[0])] = decodeURIComponent(pair[1]);
		}
		return request;
	}

	function ArrayToURL(array) {
		var pairs = [];
		for (var key in array)
			if (array.hasOwnProperty(key))
				pairs.push(key + '=' + array[key]);
		return pairs.join('&');
	}

	function clearUrl(urlArray, value) {
		for(var prop in urlArray) {
			if(urlArray.hasOwnProperty(prop)) {
				if(urlArray[prop] === value) {
					delete urlArray[prop];
					return urlArray;
				}
			}
		}
		return false;
	}

	function parseURL(url) {
		var parser = document.createElement('a'),
			searchObject = {},
			queries, split, i;
		// Let the browser do the work
		parser.href = url;
		// Convert query string to object
		queries = parser.search.replace(/^\?/, '').split('&');
		for( i = 0; i < queries.length; i++ ) {
			split = queries[i].split('=');
			searchObject[split[0]] = split[1];
		}
		return {
			protocol: parser.protocol,
			host: parser.host,
			hostname: parser.hostname,
			port: parser.port,
			pathname: parser.pathname,
			search: parser.search,
			searchObject: searchObject,
			hash: parser.hash
		};
	}
</script>