<div id="tags_block_left" class="block tags_block black nobackground">
	<div class="close" onclick="$(this).parent().parent().toggleClass('hidden'); $('#tags_filter_button').removeClass('hidden');" title="Закрыть фильтры"></div>
	<div class="filters">
		<a class="reset " href="#" onclick="if ($(this).hasClass('active')) { catalogue.reset_filters(); } return false;">Сбросить все</a>

		<!-- Показываю размеры, если есть -->
		<?php if(isset($tagsCloud['sizes'])): ?>
			<div class="group" onclick="$('.parent-of-sizes').toggle();">Размеры</div>
			<?php foreach($tagsCloud['sizes'] as $key => $val): ?>
				<div class="tag parent-of-sizes" style="display: inline-block; min-width: 20%;">
					<label>
						<input type="checkbox" name="sizes[]" value="<?=$val['id'];?>" onchange="catalogue.filter();"><?=$val['name'];?> (<?=$val['count_products'];?>)
					</label>
				</div>
			<?php endforeach; ?>

		<?php endif; ?>
		<!-- Показываю размеры, если есть -->

		<!-- Показываю теги, если есть -->
		<?php if(isset($tagsCloud['tags'])): ?>
			<?php foreach($tagsCloud['tags'] as $tags): ?>
				<?php if(!empty($tags['childs'])): ?>
					<div class="group" onclick="$('.parent-of-<?=$tags['id'];?>').toggle();"><?=$tags['name'];?></div>
					<?php foreach($tags['childs'] as $tag): ?>
						<?php if(is_array($tag)): ?>
							<div class="tag parent-of-<?=$tags['id'];?>">
								<label>
									<input type="checkbox" name="tags[]" value="<?=$tag['alias'];?>" onchange="catalogue.filter();"><?=$tag['name'];?> <span class="count">(<?=$tag['count_products'];?>)</span>
								</label>
								<a href="/catalogue/woman/dresses/tags/povsednevnoe/" onclick=""></a>
							</div>
						<?php endif; ?>
					<?php endforeach; ?>
				<?php endif; ?>
			<?php endforeach; ?>
		<?php endif; ?>
		<!-- Показываю теги, если есть -->
	</div>
</div>