<?php if(isset($discounts) && ($discounts['current'] > 0 || $discounts['next'] > 0)): // расчет цены исходя из скидок магазина ?>
	<div class="Hint">
	<h4><?=$viewTranslate['SALES_REMEMBER'];?>:</h4>
		<?php if(!isset($discounts['next'])): // если скидка максимальная ?>
			<?printf($viewTranslate['DISCOUNT_SHOP_MAX'], $discounts['current']);?>
		<?php else:  // если есть куда расти ?>
			<?php if($discounts['type'] == 'count'): // скидка по количеству?>
				<div>
					<?printf($viewTranslate['DISCOUNT_SHOP_COUNT_INFO'], $discounts['next'], $discounts['board'][$discounts['next']], \Helpers\Catalogue::declOfNum($discounts['board'][$discounts['next']], ['вещь', 'вещи', 'вещей'], false));?>
				</div>
			<?php else: // скидка по сумме покупке?>
				<div>
					<?printf($viewTranslate['DISCOUNT_SHOP_SUM_INFO'], $discounts['next'], $discounts['board'][$discounts['next']], $shop['currency_symbol']);?>
				</div>
			<?php endif; ?>
		<?php endif; ?>
	</div>
<?php endif;?>






