<?php if(isset($discounts['count']))  { ?>
	<?php if($totalCount > 0 && $totalCount < 5) { ?>
		<tr>
			<td>Скидка <?php echo $discounts['count'][$totalCount] ?>% (<?=$this->tag->linkTo([['for' => 'about-discounts'], $viewTranslate['ABOUT_DISCOUNTS'], 'target' => '_blank']);?>)</td>
			<td class="number discount"><?php echo ($total*$discounts['count'][$totalCount]/100); ?> <?php echo $shop['currency_symbol'] ?></td>
		</tr>
		<tr>
			<td>С учетом скидки</td>
			<td class="number"><?php echo $total - ($total*$discounts['count'][$totalCount]/100); ?> <?php echo $shop['currency_symbol'] ?></td>
		</tr>
	<?php } ?>
	<?php if($totalCount >= 5) { ?>
		<tr>
			<td>Скидка <?php echo end($discounts['count']); ?>% (<?=$this->tag->linkTo([['for' => 'about-discounts'], $viewTranslate['ABOUT_DISCOUNTS'], 'target' => '_blank']);?>)</td>
			<td class="number discount"><?php echo ($total*end($discounts['count'])/100); ?> <?php echo $shop['currency_symbol'] ?></td>
		</tr>
		<tr>
			<td>С учетом скидки</td>
			<td class="number"><?php echo $total - ($total*end($discounts['count'])/100); ?> <?php echo $shop['currency_symbol'] ?></td>
		</tr>
	<?php } ?>
<?php } else if(isset($discounts['sum'])) { ?>
	<tr>
		<td>Скидка <?php echo end($discounts['sum']); ?>% (<?=$this->tag->linkTo([['for' => 'about-discounts'], $viewTranslate['ABOUT_DISCOUNTS'], 'target' => '_blank']);?>)</td>
		<td class="number discount"><?php echo ($total*end($discounts['sum'])/100); ?> <?php echo $shop['currency_symbol'] ?></td>
	</tr>
	<tr>
		<td>С учетом скидки</td>
		<td class="number"><?php echo $total - ($total*end($discounts['sum'])/100); ?> <?php echo $shop['currency_symbol'] ?></td>
	</tr>
<?php } ?>