<?php if(isset($discounts['count'])) { ?>
	<?php if($discounts['count'][1] == 0) { ?>

	<?php } else { ?>
		<?php $last_key = key( array_slice( $discounts['count'], -1, 1, TRUE ) ); ?>
		<div class="Hint">
			<h4>Напомним о скидках:</h4>
			<?php if ($totalCount >= $last_key) { ?>
				<div>Вы получили максимальную скидку!</div>
			<?php } else { ?>
				<?php $itemCount = 0; ?>
				<?php foreach($discounts['count'] as $count => $amount ) { ?>

					<?php if (intval($count) > intval($totalCount)) { ?>
						<div>Чтобы получить скидку <b><?php echo $amount; ?>%</b>, вам нужно заказать еще <b><?php echo ++$itemCount; ?></b> вещ<?php echo ($itemCount==1)?'ь' :'и'; ?>			</div>
					<?php } ?>
				<?php } ?>
			<?php } ?>
		</div>
	<?php } ?>

<?php } ?>

<?php if(isset($discounts['sum'])) { ?>
	<?php $last_key = key( array_slice( $discounts['sum'], -1, 1, TRUE ) ); ?>
	<div class="Hint">
		<h4>Напомним о скидках:</h4>
		<?php if ($totalSum >= $last_key) { ?>
			<div>Вы получили максимальную скидку!</div>
		<?php } else { ?>
			<?php $itemsSum = 0; ?>
			<?php foreach($discounts['sum'] as $sum => $percent) { ?>
				<?php if (intval($sum- $totalSum) > intval($itemsSum)) { ?>
					<div>Чтобы получить скидку <b><?php echo $percent; ?>%</b>, вам нужно заказать еще на<b> <?php echo $sum - $totalSum; ?></b> <?php echo $shop['currency_symbol']; ?></div>
				<?php } ?>
			<?php } ?>
		<?php } ?>
	</div>
<?php } ?>




