<?php if(empty($basket) || null === $basket || empty($basket['items'])) { ?>
<h2 class="basket">В корзине пусто</h2>
<div style="padding: 10 0 20 0;">
	Вы можете исправить это посетив <a href="/catalogue/">Каталог</a>
</div>
<?php } else { ?>

<?php
	$totalCount = 0;
	foreach($basket['items'] as $counter => $item) {

		if(!empty($item))
		{
			foreach($item['sizes'] as $size => $count) {
				$totalCount = ($totalCount+$count);
			}
		}
	}
?>
<h2 class="basket">Сейчас в корзине:</h2>
<table border="0" cellspacing="0" cellpadding="0" class="small-basket">
	<tbody>
		<?php $total = 0; ?>

			<?php foreach($basket['items'] as $counter => $item) { ?>
				<tr class="item-row" id="basket_row_<?php echo $item['product_id']; ?>">
					<td class="image" preview_id="<?php echo $item['product_id']; ?>">

						<div style="z-index: 2;" class="basket-preview">
							<div style="display: none;"  class="basket-preview-big" id="preview_<?php echo $item['product_id']; ?>">
								<img rel="<?php echo $item['product_id']; ?>" src="http://z95.ru/f/p/150x225/catalogue/<?php echo $item['product_id']; ?>/<?php echo $item['images'][0]; ?>">
							</div>
						</div>
						<div style="z-index: 0;" class="basket-preview">
							<div class="basket-preview-small">
								<img data-prevs="<?php echo $item['product_id']; ?>" src="http://z95.ru/f/p/50x75/catalogue/<?php echo $item['product_id']; ?>/<?php echo $item['images'][0]; ?>">
							</div>
						</div>

					</td>
		<td preview_id="<?php echo $item['product_id']; ?>" class="title">
			<div class="counter"><?php echo ++$counter; ?></div>


			<a href="/catalogue/<?php echo $item['articul']; ?>">
				<span class="capitalize"><?php echo $item['product_name'] ?></span> <?php echo $item['brand']; ?></a><br>
			(<?php echo $item['articul']; ?>)<br>

		</td>
				<?php if(isset($item['sizes'])) { ?>
					<td class="sizes">
						<table align="right" class="small-basket-sizes">
							<tbody>
							<?php foreach($item['sizes'] as $size => $count) { ?>

								<?php $price = ($item['discount']) ?(int)$item['discount'] :(int)$item['price']; ?>
								<tr>
								<td width="50" class="number size">
									<?php echo $size; ?>
								</td>
								<td width="115" class="input">
									<button onclick="var ov = $(this).next().val(); var nv = Math.max(0, parseInt(ov)-1); if (nv &lt; ov) { $(this).next().val(nv); basket.recount('<?php echo $item['product_id']; ?>', '<?php echo $size; ?>', $(this).next().val(), 'small'); }" class="button sign">−</button>
									<input type="text" onchange="basket.recount('<?php echo $item['product_id']; ?>', '<?php echo $size; ?>', this.value, 'small')" onkeyup="basket.recount('<?php echo $item['product_id']; ?>', '<?php echo $size; ?>', this.value, 'small')" value="<?php echo $count; ?>" id="<?php echo $item['product_id']; ?>_<?php echo $size; ?>" size="2">
									<button onclick="var ov = $(this).prev().val(); var nv = Math.min(10, parseInt(ov)+1); if (nv &gt; ov) { $(this).prev().val(nv); basket.recount('<?php echo $item['product_id']; ?>', '<?php echo $size; ?>', $(this).prev().val(), 'small'); }" class="button sign">+</button>
									<div style="position:relative;"></div>
								</td>
								<td width="10" class="number">x</td>
								<td width="45" class="number"><?php echo $price; ?></td>
								<td width="10" class="number">=</td>
								<td width="70" class="number recount"><?php echo $price * $count; ?> <?php echo $shop['currency_symbol']; ?></td>
								<td width="20" align="right">
									<button onclick="basket.recount('<?php echo $item['product_id']; ?>', '<?php echo $size ?>', 0, 'small', 0)" class="button delete sign" title="удалить">x</button>
								</td>
							</tr>
								<?php $total = $total + $price * $count; ?>
							<?php } ?>


							</tbody>
						</table>
					</td>
				<?php } ?>
		</tr>
			<?php } ?>

		<tr>
			<td class="total" colspan="4">
				<table align="right" class="total">
					<tbody><tr>
						<td>Всего заказали на</td>
						<td class="number"><?php echo $total; ?> <?php echo $shop['currency_symbol']; ?></td>
					</tr>
					<?php if(isset($discounts)) { ?>
						<?php if(isset($discounts['count']))  { ?>
							<?php if($totalCount > 0 && $totalCount < 5) { ?>
								<tr>
									<td>Скидка <?php echo $discounts['count'][$totalCount] ?>% (<a target="_blank" href="/discounts/">подробнее о скидках</a>)</td>
									<td class="number discount"><?php echo ($total*$discounts['count'][$totalCount]/100); ?> <?php echo $shop['currency_symbol'] ?></td>
								</tr>
								<tr>
									<td>С учетом скидки</td>
									<td class="number"><?php echo $total - ($total*$discounts['count'][$totalCount]/100); ?> <?php echo $shop['currency_symbol'] ?></td>
								</tr>
							<?php } ?>
							<?php if($totalCount >= 5) { ?>
								<tr>
									<td>Скидка <?php echo end($discounts['count']); ?>% (<a target="_blank" href="/discounts/">подробнее о скидках</a>)</td>
									<td class="number discount"><?php echo ($total*end($discounts['count'])/100); ?> <?php echo $shop['currency_symbol'] ?></td>
								</tr>
								<tr>
									<td>С учетом скидки</td>
									<td class="number"><?php echo $total - ($total*end($discounts['count'])/100); ?> <?php echo $shop['currency_symbol'] ?></td>
								</tr>
							<?php } ?>
						<?php } else { ?>
								Другой вид скидок
						<?php } ?>
					<?php } ?>
					<tr>
						<td>Бесплатная доставка</td>
						<td class="number"></td>
					</tr>


					</tbody>
				</table>
			</td>
		</tr>
		<tr>
			<td align="center" colspan="4">
				<button onclick="$('#SMALL_BASKET').hide();" class="button">Продолжить покупки</button>
				<button onclick="window.location.href = '/customer/cart';" class="button">Перейти в корзину</button>
			</td>
		</tr>
	</tbody>
</table>
<?php } ?>

<script type="text/javascript">
	var count = 0;
	$('.small-basket-sizes').find('input[type=text]').each(function(i,v){
		count = parseInt(count) + parseInt($(v).val());

	});

	$(document).ready(function(){

		$('tr.item-row td[preview_id]').each(function (i, el) {
			var $preview_id = $('#preview_'+$(el).attr('preview_id'));
			$(el).hover(
				function () {
					var img = $('img', $preview_id)[0];
					if (img.complete) {
						$preview_id.show();
					}
				},
				function () {
					$preview_id.hide();
				}
			)
		});
	});
</script>