<div class="column main-column">

	<div id="CONTENT">
		<h1>Корзина</h1>
		<ul class="Thermo"><li><a href="/">Главная</a></li><li>/&nbsp;<a href="/customer/">Личный кабинет</a></li><li>/&nbsp;Корзина</li></ul><div class="clear"></div><div class="_cart" id="SHOPPING_CART"><div class="Hint">
				<h4>Напомним о скидках:</h4>


				<div>Чтобы получить скидку<b>40%</b>, вам нужно заказать еще			<b>1</b> вещь			</div>
				<div>Чтобы получить скидку<b>50%</b>, вам нужно заказать еще			<b>2</b> вещи			</div>
				<div class="popup">
					<a target="_blank" href="/discounts/" class="red">Подробнее о скидках</a>
				</div>
			</div>
			<div class="hr"></div>	<table border="0" cellspacing="0" cellpadding="0" class="basket-basket">
				<tbody><tr class="item-row" id="basket_row_57453">
					<td preview_id="57453" class="image">
						<div style="z-index: 2;" class="basket-preview">
							<div style="display: none;" id="preview_57453" class="basket-preview-big"><img src="http://img2.z95.ge/f/p/150x225/catalogue/57453/IMG_7093-s.jpg"></div>
						</div>
						<div style="z-index: 0;" class="basket-preview">
							<div class="basket-preview-small"><img src="http://img2.z95.ge/f/p/50x75/catalogue/57453/IMG_7093-s.jpg"></div>
						</div>
					</td>
					<td preview_id="57453" class="title">
						<div class="counter">1</div>


						<a href="/catalogue/woman/sweaters-blouses/87237">
							<span class="capitalize">блузка</span> Just Cavalli</a><br>
						(87237)<br>

					</td>
					<td class="sizes">
						<table align="right" class="basket-basket-sizes">
							<tbody><tr>
								<td width="50" class="number size">
									M
								</td>
								<td width="115" class="input">
									<button onclick="var ov = $(this).next().val(); var nv = Math.max(0, parseInt(ov)-1); if (nv &lt; ov) { $(this).next().val(nv); basket.recount('57453', 'M', $(this).next().val(), 'basket'); }" class="button sign">−</button>
									<input type="text" onchange="basket.recount('57453', 'M', this.value, 'basket')" onkeyup="basket.recount('57453', 'M', this.value, 'basket')" value="3" id="57453_M" size="2">
									<button onclick="var ov = $(this).prev().val(); var nv = Math.min(10, parseInt(ov)+1); if (nv &gt; ov) { $(this).prev().val(nv); basket.recount('57453', 'M', $(this).prev().val(), 'basket'); }" class="button sign">+</button>
									<div style="position:relative;"></div>
								</td>
								<td width="10" class="number">x</td>
								<td width="45" class="number">1130</td>
								<td width="10" class="number">=</td>
								<td width="70" class="number recount">3390 лари</td>
								<td width="20" align="right">
									<button onclick="basket.recount('57453', 'M', 0, 'basket', 0)" class="button delete sign" title="удалить">x</button>
								</td>
							</tr>

							</tbody></table>
					</td>
				</tr>
				<tr>
					<td class="total" colspan="4">
						<table align="right" class="total">
							<tbody><tr>
								<td>Всего заказали на</td>
								<td class="number">3390 лари</td>
							</tr>
							<tr>
								<td>Скидка 30% (<a target="_blank" href="/discounts/">подробнее о скидках</a>)</td>
								<td class="number discount">1017 лари</td>
							</tr>
							<tr>
								<td>С учетом скидки</td>
								<td class="number">2373 лари</td>
							</tr>
							<tr>
								<td>Бесплатная доставка</td>
								<td class="number"></td>
							</tr>


							</tbody></table>
					</td>
				</tr>
				<tr>
					<td align="center" style="padding-top:30px;" colspan="4">
						<button onclick="window.location.href='/order/'" class="button big">Приступить к заказу</button>
					</td>
				</tr>
				</tbody></table>
			<script type="text/javascript">
				$('.basket-basket td[preview_id]').each(function (i, el) {
					var $preview_id = $('#preview_'+$(el).attr('preview_id'));
					$(el).hover(
						function () {
							var img = $('img', $preview_id)[0];
							if (img.complete) {
								$preview_id.show();
							}
						},
						function () {
							$preview_id.hide();
						}
					)
				});
			</script>
		</div>	</div>
	<div class="ITEMS_LIST">
		<div id="CATALOGUE_SEARCH_RESULT">
		</div>
	</div>
</div>