<section class="clearfix" id="breadcrumb">
	<div class="container">
		<div class="row">

			<!-- Breadcrumb -->
			<div class="breadcrumb clearfix">
				<a title="Return to Home" href="" class="home">Home</a>
				<span class="navigation-pipe">&gt;</span>
				<span class="navigation_page">Your shopping cart</span>
			</div>
			<!-- /Breadcrumb -->
		</div>
	</div>
</section>

<section id="columns" class="columns-container">
<div class="container">
<div id="slider_row" class="row">
	<div id="top_column" class="center_column col-xs-12 col-sm-12 col-md-12">

	</div>
</div>
<div class="row">


<!-- Center -->
<section id="center_column" class="col-md-12">



<h1 id="cart_title" class="page-heading">Shopping-cart summary
 <span class="heading-counter">Your shopping cart contains:
 <span id="summary_products_quantity">8 products</span>
 </span>
</h1>

<!-- Steps -->
<ul class="step clearfix" id="order_step">
	<li class="col-md-2-4 col-xs-12 step_current first">
		<span><em>01.</em> Summary</span>
	</li>
	<li class="col-md-2-4 col-xs-12 step_todo second">
		<span><em>02.</em> Sign in</span>
	</li>
	<li class="col-md-2-4 col-xs-12 step_todo third">
		<span><em>03.</em> Address</span>
	</li>
	<li class="col-md-2-4 col-xs-12 step_todo four">
		<span><em>04.</em> Shipping</span>
	</li>
	<li id="step_end" class="col-md-2-4 col-xs-12 step_todo last">
		<span><em>05.</em> Payment</span>
	</li>
</ul>
<!-- /Steps -->


<p style="display:none" id="emptyCartWarning" class="alert alert-warning">Your shopping cart is empty.</p>
<div class="cart_last_product">
	<div class="cart_last_product_header">
		<div class="left">Last product added</div>
	</div>
	<a class="cart_last_product_img" href="">
		<img src="images/170-small_default.jpg" alt="Integer sit am">
	</a>
	<div class="cart_last_product_content">
		<p class="product-name">
			<a href="">
				Integer sit am
			</a>
		</p>
		<small>
			<a href="">
				Color : Yellow, Size : S
			</a>
		</small>
	</div>
</div>


<div id="order-detail-content" class="table_block table-responsive">
<table id="cart_summary" class="table table-bordered stock-management-on">
<thead>
<tr>
	<th class="cart_product first_item">Product</th>
	<th class="cart_description item">Description</th>
	<th class="cart_avail item">Avail.</th>
	<th class="cart_unit item">Unit price</th>
	<th class="cart_quantity item">Qty</th>
	<th class="cart_total item">Total</th>
	<th class="cart_delete last_item">&nbsp;</th>
</tr>
</thead>
<tfoot>
<tr class="cart_total_price">
	<td rowspan="3" colspan="3" id="cart_voucher" class="cart_voucher">
	</td>
	<td colspan="3" class="text-right">Total products</td>
	<td colspan="2" class="price" id="total_product">$2,291.00</td>
</tr>
<tr style="display: none;">
	<td colspan="3" class="text-right">
		Total gift-wrapping cost: </td>
	<td colspan="2" class="price-discount price" id="total_wrapping">
		$0.00
	</td>
</tr>
<tr class="cart_total_delivery">
	<td colspan="3" class="text-right">Total shipping</td>
	<td colspan="2" class="price" id="total_shipping">$2.00</td>
</tr>
<tr class="cart_total_voucher" style="display:none">
	<td colspan="3" class="text-right">
		Total vouchers
	</td>
	<td colspan="2" class="price-discount price" id="total_discount">
		$0.00
	</td>
</tr>
<tr class="cart_total_price">
	<td colspan="3" class="total_price_container text-right">
		<span>Total</span>
	</td>
	<td colspan="2" class="price" id="total_price_container">
		<span id="total_price">$2,293.00</span>
	</td>
</tr>
</tfoot>
<tbody>

<tr id="product_8_46_0_0" class="cart_item first_item address_0 odd">
	<td class="cart_product">
		<a href=""><img src="images/168-small_default.jpg" alt="Vivamus condimentum" width="81" height="117"></a>
	</td>
	<td class="cart_description">
		<p class="product-name"><a href="">Vivamus condimentum</a></p>
		<small class="cart_ref">SKU : demo_8</small> <small><a href="">Color : Yellow, Size : S</a></small> </td>
	<td class="cart_avail"><span class="label label-success">In stock</span></td>
	<td class="cart_unit" data-title="Unit price">
 <span class="price" id="product_price_8_46_0">
 <span class="price">$250.00</span>
 </span>
	</td>

	<td class="cart_quantity text-center">

		<input type="hidden" value="2" name="quantity_8_46_0_0_hidden">
		<input size="2" type="text" autocomplete="off" class="cart_quantity_input form-control grey" value="2" name="quantity_8_46_0_0">
		<div class="cart_quantity_button clearfix">
			<a rel="nofollow" class="cart_quantity_down btn btn-default button-minus" id="cart_quantity_down_8_46_0_0" href="" title="Subtract">
				<span><i class="icon-minus"></i></span>
			</a>
			<a rel="nofollow" class="cart_quantity_up btn btn-default button-plus" id="cart_quantity_up_8_46_0_0" href="" title="Add"><span><i class="icon-plus"></i></span></a>
		</div>
	</td>
	<td class="cart_total" data-title="Total">
 <span class="price" id="total_product_price_8_46_0">
 $500.00 </span>
	</td>
	<td class="cart_delete text-center" data-title="Delete">
		<div>
			<a rel="nofollow" title="Delete" class="cart_quantity_delete" id="8_46_0_0" href=""><i class="icon-trash"></i></a>
		</div>
	</td>
</tr>



<tr id="product_9_52_0_0" class="cart_item address_0 even">
	<td class="cart_product">
		<a href=""><img src="images/168-small_default.jpg" alt="Donec posuere metus" width="81" height="117"></a>
	</td>
	<td class="cart_description">
		<p class="product-name"><a href="">Donec posuere metus</a></p>
		<small class="cart_ref">SKU : demo_9</small> <small><a href="">Color : Yellow, Size : S</a></small> </td>
	<td class="cart_avail"><span class="label label-success">In stock</span></td>
	<td class="cart_unit" data-title="Unit price">
 <span class="price" id="product_price_9_52_0">
 <span class="price">$350.00</span>
 </span>
	</td>

	<td class="cart_quantity text-center">

		<input type="hidden" value="1" name="quantity_9_52_0_0_hidden">
		<input size="2" type="text" autocomplete="off" class="cart_quantity_input form-control grey" value="1" name="quantity_9_52_0_0">
		<div class="cart_quantity_button clearfix">
			<a rel="nofollow" class="cart_quantity_down btn btn-default button-minus" id="cart_quantity_down_9_52_0_0" href="" title="Subtract">
				<span><i class="icon-minus"></i></span>
			</a>
			<a rel="nofollow" class="cart_quantity_up btn btn-default button-plus" id="cart_quantity_up_9_52_0_0" href="" title="Add"><span><i class="icon-plus"></i></span></a>
		</div>
	</td>
	<td class="cart_total" data-title="Total">
 <span class="price" id="total_product_price_9_52_0">
 $350.00 </span>
	</td>
	<td class="cart_delete text-center" data-title="Delete">
		<div>
			<a rel="nofollow" title="Delete" class="cart_quantity_delete" id="9_52_0_0" href=""><i class="icon-trash"></i></a>
		</div>
	</td>
</tr>



<tr id="product_12_70_0_0" class="cart_item address_0 odd">
	<td class="cart_product">
		<a href=""><img src="images/156-small_default.jpg" alt="Morbi vitae cons" width="81" height="117"></a>
	</td>
	<td class="cart_description">
		<p class="product-name"><a href="">Morbi vitae cons</a></p>
		<small class="cart_ref">SKU : demo_12</small> <small><a href="">Color : Yellow, Size : S</a></small> </td>
	<td class="cart_avail"><span class="label label-success">In stock</span></td>
	<td class="cart_unit" data-title="Unit price">
 <span class="price" id="product_price_12_70_0">
 <span class="price">$300.00</span>
 </span>
	</td>

	<td class="cart_quantity text-center">

		<input type="hidden" value="1" name="quantity_12_70_0_0_hidden">
		<input size="2" type="text" autocomplete="off" class="cart_quantity_input form-control grey" value="1" name="quantity_12_70_0_0">
		<div class="cart_quantity_button clearfix">
			<a rel="nofollow" class="cart_quantity_down btn btn-default button-minus" id="cart_quantity_down_12_70_0_0" href="" title="Subtract">
				<span><i class="icon-minus"></i></span>
			</a>
			<a rel="nofollow" class="cart_quantity_up btn btn-default button-plus" id="cart_quantity_up_12_70_0_0" href="" title="Add"><span><i class="icon-plus"></i></span></a>
		</div>
	</td>
	<td class="cart_total" data-title="Total">
 <span class="price" id="total_product_price_12_70_0">
 $300.00 </span>
	</td>
	<td class="cart_delete text-center" data-title="Delete">
		<div>
			<a rel="nofollow" title="Delete" class="cart_quantity_delete" id="12_70_0_0" href=""><i class="icon-trash"></i></a>
		</div>
	</td>
</tr>



<tr id="product_18_106_0_0" class="cart_item address_0 even">
	<td class="cart_product">
		<a href=""><img src="images/156-small_default.jpg" alt="Integer sit am" width="81" height="117"></a>
	</td>
	<td class="cart_description">
		<p class="product-name"><a href="">Integer sit am</a></p>
		<small class="cart_ref">SKU : demo_18</small> <small><a href="">Color : Yellow, Size : S</a></small> </td>
	<td class="cart_avail"><span class="label label-success">In stock</span></td>
	<td class="cart_unit" data-title="Unit price">
 <span class="price" id="product_price_18_106_0">
 <span class="price">$20.50</span>
 </span>
	</td>

	<td class="cart_quantity text-center">

		<input type="hidden" value="2" name="quantity_18_106_0_0_hidden">
		<input size="2" type="text" autocomplete="off" class="cart_quantity_input form-control grey" value="2" name="quantity_18_106_0_0">
		<div class="cart_quantity_button clearfix">
			<a rel="nofollow" class="cart_quantity_down btn btn-default button-minus" id="cart_quantity_down_18_106_0_0" href="" title="Subtract">
				<span><i class="icon-minus"></i></span>
			</a>
			<a rel="nofollow" class="cart_quantity_up btn btn-default button-plus" id="cart_quantity_up_18_106_0_0" href="" title="Add"><span><i class="icon-plus"></i></span></a>
		</div>
	</td>
	<td class="cart_total" data-title="Total">
 <span class="price" id="total_product_price_18_106_0">
 $41.00 </span>
	</td>
	<td class="cart_delete text-center" data-title="Delete">
		<div>
			<a rel="nofollow" title="Delete" class="cart_quantity_delete" id="18_106_0_0" href=""><i class="icon-trash"></i></a>
		</div>
	</td>
</tr>



<tr id="product_19_112_0_0" class="cart_item last_item address_0 odd">
	<td class="cart_product">
		<a href=""><img src="images/156-small_default.jpg" alt="Morbi vitae cons" width="81" height="117"></a>
	</td>
	<td class="cart_description">
		<p class="product-name"><a href="">Morbi vitae cons</a></p>
		<small class="cart_ref">SKU : demo_19</small> <small><a href="">Color : Yellow, Size : S</a></small> </td>
	<td class="cart_avail"><span class="label label-success">In stock</span></td>
	<td class="cart_unit" data-title="Unit price">
 <span class="price" id="product_price_19_112_0">
 <span class="price">$550.00</span>
 </span>
	</td>

	<td class="cart_quantity text-center">

		<input type="hidden" value="2" name="quantity_19_112_0_0_hidden">
		<input size="2" type="text" autocomplete="off" class="cart_quantity_input form-control grey" value="2" name="quantity_19_112_0_0">
		<div class="cart_quantity_button clearfix">
			<a rel="nofollow" class="cart_quantity_down btn btn-default button-minus" id="cart_quantity_down_19_112_0_0" href="" title="Subtract">
				<span><i class="icon-minus"></i></span>
			</a>
			<a rel="nofollow" class="cart_quantity_up btn btn-default button-plus" id="cart_quantity_up_19_112_0_0" href="" title="Add"><span><i class="icon-plus"></i></span></a>
		</div>
	</td>
	<td class="cart_total" data-title="Total">
 <span class="price" id="total_product_price_19_112_0">
 $1,100.00 </span>
	</td>
	<td class="cart_delete text-center" data-title="Delete">
		<div>
			<a rel="nofollow" title="Delete" class="cart_quantity_delete" id="19_112_0_0" href=""><i class="icon-trash"></i></a>
		</div>
	</td>
</tr>


</tbody>
</table>
</div> <!-- end order-detail-content -->





<div id="HOOK_SHOPPING_CART"></div>
<p class="cart_navigation clearfix">
	<a href="" class="button btn btn-default standard-checkout button-medium" title="Proceed to checkout">
		<span>Proceed to checkout<i class="icon-chevron-right right"></i></span>
	</a>
	<a href="" class="button-exclusive btn btn-default" title="Continue shopping">
		<i class="icon-chevron-left"></i>Continue shopping
	</a>
</p>

</section>


</div>
</div>
</section>