<?php echo Phalcon\Tag::javascriptInclude('assets/' . $shop->code . '/js/cart.js'); ?>
<section class="clearfix" id="breadcrumb">
	<div class="container">
		<div class="row">

			<!-- Breadcrumb -->
			<div class="breadcrumb clearfix">
				<a title="Return to Home" href="" class="home">Home</a>
				<span class="navigation-pipe">&gt;</span>
				<span class="navigation_page">Your shopping cart</span>
			</div>
			<!-- /Breadcrumb -->
		</div>
	</div>
</section>

<section id="columns" class="columns-container">
<div class="container">
<div id="slider_row" class="row">
	<div id="top_column" class="center_column col-xs-12 col-sm-12 col-md-12">

	</div>
</div>
<div class="row">


<!-- Center -->
<section id="center_column" class="col-md-12">



<h1 id="cart_title" class="page-heading">Shopping-cart summary
 <span class="heading-counter">Your shopping cart contains:
 <span id="summary_products_quantity">

	 <span>
		 <?php if(isset($products)) { ?>
			 <?php $count = 0; ?>
			 <?php foreach ($products as $product) { ?>
				<?php $count = $count + $product->quantity_wanted; ?>
			 <?php } ?>
			<?php echo $count; ?>
		 <?php } else { ?>
			 0
		 <?php } ?>
	 </span>
	 products
 </span>
 </span>
</h1>

<!-- Steps -->
<ul class="step clearfix" id="order_step">
	<li class="col-md-2-4 col-xs-12 step_current first">
		<span><em>01.</em> Summary</span>
	</li>
	<li class="col-md-2-4 col-xs-12 step_todo second">
		<span><em>02.</em> Sign in</span>
	</li>
	<li class="col-md-2-4 col-xs-12 step_todo third">
		<span><em>03.</em> Address</span>
	</li>
	<li class="col-md-2-4 col-xs-12 step_todo four">
		<span><em>04.</em> Shipping</span>
	</li>
	<li id="step_end" class="col-md-2-4 col-xs-12 step_todo last">
		<span><em>05.</em> Payment</span>
	</li>
</ul>
<!-- /Steps -->


<p style="display:none" id="emptyCartWarning" class="alert alert-warning">Your shopping cart is empty.</p>
<div class="cart_last_product">
	<div class="cart_last_product_header">
		<div class="left">Last product added</div>
	</div>
	<a class="cart_last_product_img" href="">
		<img src="images/170-small_default.jpg" alt="Integer sit am">
	</a>
	<div class="cart_last_product_content">
		<p class="product-name">
			<a href="">
				Integer sit am
			</a>
		</p>
		<small>
			<a href="">
				Color : Yellow, Size : S
			</a>
		</small>
	</div>
</div>


<div id="order-detail-content" class="table_block table-responsive">
	<?php if(isset($products)) { ?>
<table id="cart_summary" class="table table-bordered stock-management-on">
<thead>
<tr>
	<th class="cart_product first_item">Product</th>
	<th class="cart_description item">Description</th>
	<th class="cart_avail item">Avail.</th>
	<th class="cart_unit item">Unit price</th>
	<th class="cart_quantity item">Qty</th>
	<th class="cart_total item">Total</th>
	<th class="cart_delete last_item">&nbsp;</th>
</tr>
</thead>
<tfoot>
<tr class="cart_total_price">
	<td rowspan="3" colspan="3" id="cart_voucher" class="cart_voucher">
	</td>
	<td colspan="3" class="text-right">Total products</td>
	<td colspan="2" class="price" id="total_product">$<span>
			<?php if(null !== $products || !empty($products)) { ?>
				<?php $count = 0; ?>
				<?php foreach ($products as $product) { ?>
					<?php $count = $count + $product->price * $product->quantity_wanted; ?>
				<?php } ?>
				<?php echo $count; ?>.00
			<?php } else { ?>
				0
			<?php } ?></span></td>
</tr>
<tr style="display: none;">
	<td colspan="3" class="text-right">
		Total gift-wrapping cost: </td>
	<td colspan="2" class="price-discount price" id="total_wrapping">
		$0.00
	</td>
</tr>
<tr class="cart_total_delivery">
	<td colspan="3" class="text-right">Total shipping</td>
	<td colspan="2" class="price" id="total_shipping">$2.00</td>
</tr>
<tr class="cart_total_voucher" style="display:none">
	<td colspan="3" class="text-right">
		Total vouchers
	</td>
	<td colspan="2" class="price-discount price" id="total_discount">
		$0.00
	</td>
</tr>
<tr class="cart_total_price">
	<td colspan="3" class="total_price_container text-right">
		<span>Total</span>
	</td>
	<td colspan="2" class="price" id="total_price_container">
		<span id="total_price">$<span>
				<?php if(null !== $products || !empty($products)) { ?>
					<?php $count = 0; ?>
					<?php foreach ($products as $product) { ?>
						<?php $count = $count + $product->price * $product->quantity_wanted; ?>
					<?php } ?>
					<?php echo $count; ?>.00
				<?php } else { ?>
					0
				<?php } ?>
		</span></span>
	</td>
</tr>
</tfoot>
<tbody>

	<?php foreach ($products as $product) { ?>
	<tr id="product_<?php echo $product->articul; ?>" data-articul="<?php echo $product->articul; ?>" class="cart_item first_item address_0 odd">
	<td class="cart_product">
		<a href=""><img src="images/168-small_default.jpg" alt="<?php echo $product->brand; ?>&nbsp;<?php echo $product->product_name; ?>" width="81" height="117"></a>
	</td>
	<td class="cart_description">
		<p class="product-name"><a href=""><?php echo $product->brand; ?>&nbsp;<?php echo $product->product_name; ?> </a></p>
<!--		<small class="cart_ref">SKU : demo_8</small> -->
		<small><a href="" class="js-product_size">Size : <span><?php echo $product->sizes; ?></span></a></small> </td>
	<td class="cart_avail"><span class="label label-success">In stock</span></td>
	<td class="cart_unit" data-title="Unit price">
 <span class="" id="product_price_8_46_0">
 <span class="price"><?php echo $shop->currency_symbol; ?><span><?php echo $product->price; ?></span></span>
 </span>
	</td>

	<td class="cart_quantity text-center">

		<input type="hidden" value="2" name="quantity_8_46_0_0_hidden">
		<input size="2" type="text" autocomplete="off" class="cart_quantity_input form-control grey" value="<?php echo $product->quantity_wanted; ?>" name="quantity_8_46_0_0" onkeyup="cart.quantityKeyUp(this);" onkeypress="cart.quantityKeyPress(this);">
		<div class="cart_quantity_button clearfix">
			<a rel="nofollow" class="cart_quantity_down btn btn-default button-minus" id="cart_quantity_down_8_46_0_0" href="" title="Subtract">
				<span><i class="icon-minus"></i></span>
			</a>
			<a rel="nofollow" class="cart_quantity_up btn btn-default button-plus" id="cart_quantity_up_8_46_0_0" href="" title="Add"><span><i class="icon-plus"></i></span></a>
		</div>
	</td>
	<td class="cart_total" data-title="Total">
	 <span class="price" id="total_product_price_8_46_0">
		<?php echo $shop->currency_symbol; ?><span><?php echo $product->quantity_wanted * $product->price; ?>.00</span>
	 </span>
	</td>
	<td class="cart_delete text-center" data-title="Delete">
		<div>
			<a rel="nofollow" title="Delete" class="cart_quantity_delete" id="8_46_0_0" href="" data-articul="<?php echo $product->articul; ?>"><i class="icon-trash"></i></a>
		</div>
	</td>
</tr>
<?php } ?>



</tbody>
</table>
	<?php } ?>
</div> <!-- end order-detail-content -->





<div id="HOOK_SHOPPING_CART"></div>
<p class="cart_navigation clearfix">
	<a href="" class="button btn btn-default standard-checkout button-medium" title="Proceed to checkout" id="procced_to_back">
		<span>Proceed to checkout<i class="icon-chevron-right right"></i></span>
	</a>
	<a href="" class="button-exclusive btn btn-default" title="Continue shopping">
		<i class="icon-chevron-left"></i>Continue shopping
	</a>
</p>

</section>


</div>
</div>
</section>