<div class="column left-column">
	<ul class="catalogue-structure"><li><a href="/discounts/">Скидки</a></li><li><a href="/delivery">Доставка</a></li><li><a href="/return">Возврат</a></li><li><a href="/useful">Полезно</a></li><li><a href="/opt">Опт</a></li></ul>
</div>

<div class="column main-column">
	<div class="ITEMS_LIST">
		<div id="CATALOGUE_SEARCH_RESULT">
		</div>
	</div>

	<div id="CONTENT">
		<ul class="documents"><li><a href="/discounts">Скидки</a></li><li><a href="/delivery">Доставка</a></li><li><a href="/return">Возврат</a></li><li><a href="/opt">Опт</a></li></ul>
		<h1>Скидки</h1>		<ul class="Thermo"><li><a href="/">Главная</a></li><li>/&nbsp;<a href="/about">О магазине</a></li><li>/&nbsp;Скидки</li></ul><div class="clear"></div><div class="element-text"><p>Мы постоянно совершенствуем систему скидок, чтобы покупка всегда приносила радость и моральное удовлетворение. Мы ежедневно назначаем скидки на отдельные товары до 90%.</p>
			<p>Несколько раз в год мы устраиваем распродажи, а в обычное время действует несколько скидок и акций. Все скидки суммируются.</p>

			<h2>Скидка на товар</h2>
			<p>Ежедневно мы обновляем список товаров, которые продаются со скидкой. Все товары со скидкой собраны в разделе «<a href="/catalogue/sale/">Распродажа</a>»</p></div>
	</div>
</div>
<div class="clear"></div>