<div class="ITEMS_LIST" style="padding: 0 10px;">
	<div id="CATALOGUE_SEARCH_RESULT">
	</div>
</div>

<div id="CONTENT" >
<div class="clear"></div>
<table class="work-info">
	<tr>
		<td style="background:url(/assets/Z95/images/z95ru/icons/delivery.png) no-repeat 20px 10px; padding-left: 75px; " onclick="global.go({ url: '/about/delivery' })">
			<h3>Бесплатная доставка</h3>
			По всей России			</td>
		<td style="background:url(/assets/Z95/images/z95ru/icons/fitting.png) no-repeat 0px 10px;" onclick="global.go({ url: '/about/delivery' })">
			<h3>Не уверены в размере?</h3>
			Менеджер придет на помощь
		</td>
		<td style="background:url(/assets/Z95/images/z95ru/icons/247.png) no-repeat 0px 10px;" onclick="global.go({ url: '/about/' })">
			<h3>Отвечаем на звонки 24/7</h3>
			И по праздникам тоже			</td>
		<td style="background:url(/assets/Z95/images/z95ru/icons/return.png) no-repeat 0px 10px;" onclick="global.go({ url: '/about/return/' })">
			<h3>Легкий обмен</h3>
			В течение 14 суток			</td>
	</tr>
</table>
<div class="coupon-container"></div>
<div class="teaser"></div>
<script type="text/javascript">
	var teaserSettings = [
		<?php if(isset($banners['main'])) { ?>
			<?php foreach($banners['main'] as $banners) { ?>
				{src: '/f/t/<?php echo $banners->image; ?>', url: '/catalogue/sale', text: ''},
				{src: '/f/t/77009b1c703e1d3a2b073aceab4931aa.jpg', url: '/catalogue/sale', text: ''}
			<?php } ?>
		<?php } ?>
	];

	var teaser = new teaser(teaserSettings);
</script>

<div>
	<?php foreach($mainCategories as $category) { ?>
		<div class="catalogue-category" onclick="window.location.href= '/catalogue/<?php echo $category->parent_alias; ?>/<?php echo $category->alias; ?>/'">
			<div class="leader">
				<img class="image" src="http://img<?php echo rand(0,9); ?>.z95.ru/f/p/c_0_100_300_400/sep-tilt_shift/600x600/catalogue/<?php echo $category->preview['product_id'] ?>/<?php echo $category->preview['image'] ?>" />
			</div>
			<div class="title">
				<a href="/catalogue/<?php echo $category->parent_alias; ?>/<?php echo $category->alias; ?>/"><?php echo $category->name; ?></a>
				<span class="count"><?php echo $category->count; ?></span>
			</div>
		</div>
	<?php } ?>
</div>
<div class="clear"></div></div>