<div class="column left-column">
	<ul class="catalogue-structure"><li><a href="/discounts">Скидки</a></li><li><a href="/delivery/">Доставка</a></li><li><a href="/return">Возврат</a></li><li><a href="/useful">Полезно</a></li><li><a href="/opt">Опт</a></li></ul>
</div>

<div class="column main-column">
	<div class="ITEMS_LIST">
		<div id="CATALOGUE_SEARCH_RESULT">
		</div>
	</div>
	<div class="inner_teaser"><a title="" target="_blank" href="/catalogue/sale"><img alt="" src="/f/t/5ad05dbba33a7c986ffad79ff33dbd98.jpg"></a></div>
	<div id="CONTENT">
		<ul class="documents"><li><a href="/discounts">Скидки</a></li><li><a href="/delivery">Доставка</a></li><li><a href="/return">Возврат</a></li><li><a href="/opt">Опт</a></li></ul>
		<h1>Опт</h1>		<ul class="Thermo"><li><a href="/">Главная</a></li><li>/&nbsp;<a href="/about">О магазине</a></li><li>/&nbsp;Опт</li></ul><div class="clear"></div><div class="element-text"><p><i>Уважаемые клиенты!</i></p>
			<p>Наша компания рада предложить возможность оптовых закупок, представленной на нашем сайте продукции. Оптовые цены высылаются по запросу. Если вы заинтересованы в получении оптового прайса напишите по электронной почте <a href="mailto:opt@z95.ru?subject=About wholesale price">opt@z95.ru</a></p>
			<p>Просьба, учитывать, что для работы по оптовым ценам вы должны соблюдать следующие условия:</p>
			<ul>
				<li>Каждая закупка на сумму более <b>50,000</b> рублей.</li>
				<li>Обмен, возврат, примерка вещей из оптовых заказов невозможен.</li>
				<li>Обмен брака в течении <b>72 часов</b> после получения заказа.</li>
			</ul>
			<p>Мы осуществляем доставку оптовых заказов в любой город России за 3-4 дня!</p>
			<p>Все оптовые заказы можно осуществлять через специальный оптовый интернет-магазин и оплачивать банковским переводом.</p>
			<p>Мы предоставляем полный пакет документов сертификаты, протоколы гигиен. экспертизы, товарные накладные.</p>
			<p>Для оптовых закупок вам не обязательно иметь юридическое лицо  возможна закупка от имени физического лица.</p></div>	</div>
</div>
<div class="clear"></div>
