
<section id="slideshow" class="clearfix">
	<div class="container">
		<div class="row">
			<div class="layerslider-wrapper col-md-12 col-sm-12 col-xs-12">
				<div class="bannercontainer banner-boxed" style="margin: 0px 0px 18px;background-color:">
					<div id="sliderlayer" class="rev_slider boxedbanner" style="width:100%;height:585px; ">
						<ul>
							<li data-link="#" data-masterspeed="300" data-transition="random" data-slotamount="7"
								data-thumb="images/slider/ede0e95db8ca0de2d561d0eec1a3cdc0.jpg">
								<img
									src="assets/<?php echo $shop->code ?>/images/slider/ede0e95db8ca0de2d561d0eec1a3cdc0.jpg"
									alt=""/>

								<div class="caption noshadow text-center sfb easeOutExpo ltb"
									 data-x="328"
									 data-y="228"
									 data-speed="300"
									 data-start="1029"
									 data-easing="easeOutExpo" style="font-size:12px; text-align: left;">Lorem ipsum
									dolor sit amet, consectetur adipiscing elit. Nunc facilisis fringilla nisi euismod
									Morbi sed adipiscing eleifend, dolor risus congue mi aliquet dolor tellus
								</div>
								<div class="caption big_black fade easeOutExpo"
									 data-x="487"
									 data-y="306"
									 data-speed="300"
									 data-start="1600"
									 data-easing="easeOutExpo">Magasinez maintenant
								</div>
								<div class="caption large_text sft easeOutExpo stt"
									 data-x="306"
									 data-y="162"
									 data-speed="300"
									 data-start="400"
									 data-easing="easeOutExpo" style="font-size:36px">LOREM IPSUM DOLOR DOREST
								</div>
							</li>

							<li data-link="#" data-masterspeed="300" data-transition="random" data-slotamount="7"
								data-thumb="images/slider/ab0a75aa2a3ed15f70c04bb53aac19a2.jpg">
								<img
									src="assets/<?php echo $shop->code ?>/images/slider/ab0a75aa2a3ed15f70c04bb53aac19a2.jpg"
									alt=""/>

								<div class="caption large_text text-center lft easeOutExpo ltb"
									 data-x="316"
									 data-y="146"
									 data-speed="300"
									 data-start="199"
									 data-easing="easeOutExpo" style="font-size:36px">LOREM IPSUM DOLOR DOREST
								</div>
								<div class="caption noshadow text-center sft easeOutExpo stb"
									 data-x="334"
									 data-y="216"
									 data-speed="300"
									 data-start="728"
									 data-easing="easeOutExpo" style="font-size:12px; text-align: left;">Lorem ipsum
									dolor sit amet, consectetur adipiscing elit. Nunc facilisis fringilla nisi euismod
									Morbi sed adipiscing eleifend, dolor risus congue mi aliquet dolor tellus
								</div>
								<div class="caption big_black fade easeOutExpo"
									 data-x="495"
									 data-y="295"
									 data-speed="300"
									 data-start="1151"
									 data-easing="easeOutExpo" style="font-size:12px">Magasinez maintenant
								</div>
							</li>

							<li data-masterspeed="300" data-transition="random" data-slotamount="7"
								data-thumb="images/slider/857132a2e63f14ec64380d875d8f386e.jpg">
								<img
									src="assets/<?php echo $shop->code ?>/images/slider/857132a2e63f14ec64380d875d8f386e.jpg"
									alt=""/>

								<div class="caption noshadow text-center sft easeOutExpo ltb"
									 data-x="339"
									 data-y="240"
									 data-speed="300"
									 data-start="537"
									 data-easing="easeOutExpo" style="font-size:12px; text-align: left;">Lorem ipsum
									dolor sit amet, consectetur adipiscing elit. Nunc facilisis fringilla nisi euismod
									Morbi sed adipiscing eleifend, dolor risus congue mi aliquet dolor tellus et ante.
								</div>
								<div class="caption large_text sft easeOutExpo stt"
									 data-x="303"
									 data-y="167"
									 data-speed="300"
									 data-start="924"
									 data-easing="easeOutExpo" style="font-size:36px">LOREM IPSUM DOLOR DOREST
								</div>
								<div class="caption big_black lfb easeOutExpo stb"
									 data-x="492"
									 data-y="317"
									 data-speed="300"
									 data-start="1200"
									 data-easing="easeOutExpo">Magasinez maintenant
								</div>
							</li>
						</ul>

						<div class="tp-bannertimer tp-top"></div>
					</div>
				</div>
			</div>


		</div>
	</div>
</section>


<!-- Content -->
<section id="columns" class="columns-container">
<div class="container">
<div id="slider_row" class="row">
	<div id="top_column" class="center_column col-xs-12 col-sm-12 col-md-12">

	</div>
</div>
<div class="row">


<!-- Center -->
<section id="center_column" class="col-md-12">

<div class="clearfix">
<div class="row ">
	<div class="widget col-lg-4 col-md-4 col-sm-4 col-xs-12 col-sp-12">
		<div class="widget-html block">
			<div class="block_content">
				<div class="box">
					<a href=""><img src="assets/<?php echo $shop->code ?>/images/img-banner-1.jpg" alt="" width="378"
									height="250">
					</a>
				</div>
				<div class="box">
					<a href=""><img src="assets/<?php echo $shop->code ?>/images/img-banner-2.jpg" alt="" width="378"
									height="170"> </a>
				</div>
			</div>
		</div>
	</div>
	<div class="widget col-lg-4 col-md-4 col-sm-4 col-xs-12 col-sp-12">
		<div class="widget-html block">
			<div class="block_content">
				<div class="box">
					<a href=""><img src="assets/<?php echo $shop->code ?>/images/img-banner-3.jpg" alt="" width="378"
									height="438">
					</a>
				</div>
			</div>
		</div>
	</div>
	<div class="widget col-lg-4 col-md-4 col-sm-4 col-xs-12 col-sp-12">
		<div class="widget-html block">
			<div class="block_content">
				<div class="box">
					<a href=""><img src="assets/<?php echo $shop->code ?>/images/img-banner-4.jpg" alt="" width="378"
									height="250">
					</a>
				</div>
				<div class="box">
					<a href=""><img src="assets/<?php echo $shop->code ?>/images/img-banner-5.jpg" alt="" width="378"
									height="170">
					</a>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row ">
<div class="widget col-lg-12 col-md-12 col-sm-12 col-xs-12 col-sp-12">

<!-- MODULE Block specials -->
<div id="leoproducttab" class="block products_block exclusive" style="overflow: visible;">
<div class="block_content box-line h3">
<div class="content-nav-tabs">
	<ul class="nav nav-tabs">

		<li class="active"><a href="#leoproducttabnewproducts" data-toggle="tab"><span></span>New Arrivals</a>
		</li>

		<li><a href="#leoproducttabbestseller" data-toggle="tab"><span></span>Best Seller</a>
		</li>

		<li><a href="#leoproducttabfeatured" data-toggle="tab"><span></span>Featured Products</a>
		</li>
	</ul>
</div>
<div class="container_tab_content">
<div class="product_tab_content tab-content">


<!--**************************************************************************************************************************************-->
<div class="tab-pane active" id="leoproducttabnewproducts">
	<div class="carousel slide" id="leoproducttab-newproducts">

		<a class="carousel-control left" href="#leoproducttab-newproducts" data-slide="prev">prev</a>
		<a class="carousel-control right" href="#leoproducttab-newproducts" data-slide="next">next</a>


		<div class="carousel-inner">
			<div class="item active">
				<div class="product_list grid col-xs-12 col-md-12">
					<div class="row">
						<?php foreach ($latestProducts as $key => $latestProduct) { ?>
						<?php if ($key && $key % 4 == 0) { ?>
					</div>
				</div>
			</div>
			<div class="item">
				<div class="product_list grid col-xs-12 col-md-12">
					<div class="row">
						<?php } ?>
						<div class="ajax_block_product product_block col-md-3 col-xs-12 col-sm-12 first_item">

							<div class="product-container" itemscope="" itemtype="http://schema.org/Product">
								<div class="left-block">
									<div class="product-image-container">
										<div class="leo-more-info" data-idproduct="8">
											<div class="col-1">
												<!-- thumbnails -->
												<div class="views_block">
													<div class="thumbs_list thumbs_list_8">
														<ul class="thumbs_list_frame">
															<li>
																<a href="" rel="other-views"
																   class="thickbox-ajax-8 shown"
																   title="Donec magna diam">
																	<img
																		src="assets/<?php echo $shop->code ?>/images/155-medium_default.jpg"
																		alt="Donec magna diam" height="125" width="125"
																		class="leo-hover-image">
																</a>
															</li>
															<li>
																<a href="" rel="other-views" class="thickbox-ajax-8"
																   title="Donec magna diam">
																	<img
																		src="assets/<?php echo $shop->code ?>/images/154-medium_default.jpg"
																		alt="Donec magna diam" height="125" width="125"
																		class="leo-hover-image">
																</a>
															</li>
														</ul>
													</div>
												</div>
											</div>
										</div>
										<a class="product_img_link"
										   href="<?php echo Helpers\LocationUrls::location('/catalogue/' . $latestProduct->articul); ?>"
										   title="Vivamus condimentum" itemprop="url">
											<img class="replace-2x img-responsive"
												 src="assets/<?php echo $shop->code ?>/images/154-home_default.jpg"
												 alt="Donec magna diam"
												 title="Donec magna diam" itemprop="image">
											<span class="product-additional" data-idproduct="8"><img
													class="img-responsive" title="" alt=""
													src="assets/<?php echo $shop->code ?>/images/155-home_default.jpg"></span>
										</a>

						 <span class="new-box">
						 <span class="new-label product-label">New</span></span>
									</div>
									<div class="functional-buttons clearfix">
										<div class="button-container">
											<a class="button ajax_add_to_cart_button btn btn-default" href=""
											   rel="nofollow" title="Add to cart"
											   data-id-product="8">
												<i class="fa fa-shopping-cart"></i> Add to cart
											</a>
										</div>


										<div class="wishlist">
											<a class="addToWishlist btn wishlistProd_8" title="Wishlist" href=""
											   rel="8">

											</a>
										</div>

										<div class="view_detail">
											<a itemprop="url" class="lnk_view btn" href="" title="View">

											</a>
										</div>

									</div>

								</div>
								<div class="right-block">
									<h5 itemprop="name">
										<?php echo Phalcon\Tag::linkTo(array('catalogue/' . $latestProduct->articul, $latestProduct->brand . ', ' . ucfirst($latestProduct->name), 'class' => 'product-name', 'title' => $latestProduct->name)); ?>
									</h5>

									<div class="product-desc" itemprop="description">
										<?php echo $latestProduct->description; ?>
									</div>
									<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"
										 class="content_price">
						 <span itemprop="price" class="price product-price"><?php echo $latestProduct->price; ?>
						 </span>
										<meta itemprop="priceCurrency" content="USD">
									</div>


									<div class="comments_note clearfix" itemprop="aggregateRating" itemscope=""
										 itemtype="http://schema.org/AggregateRating">
										<div class="star_content clearfix">
											<div class="star"></div>
											<div class="star"></div>
											<div class="star"></div>
											<div class="star"></div>
											<div class="star"></div>
											<meta itemprop="worstRating" content="0">
											<meta itemprop="ratingValue" content="0">
											<meta itemprop="bestRating" content="5">
										</div>
										<span class="nb-comments"><span itemprop="reviewCount">0</span> Review(s)</span>
									</div>


						 <span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="availability">
						 <span class="available-now">
						 <link itemprop="availability" href="http://schema.org/InStock">In stock</span>
						 </span>

									<div class="product-flags">
									</div>

								</div>
								<div class="product_bottom hidden-xs">
									<a class="quick-view" href="">
										<i class="fa fa-plus"></i> Quick View
									</a>
								</div>
							</div>
							<!-- .product-container> -->


						</div>
						<?php } ?>
					</div>
				</div>
			</div>
		</div>


	</div>
</div>
<!--**************************************************************************************************************************************-->


<!--**************************************************************************************************************************************-->
<div class="tab-pane" id="leoproducttabbestseller">
	<div class="carousel slide" id="leoproducttab-bestseller">

		<a class="carousel-control left" href="#leoproducttab-bestseller" data-slide="prev">prev</a>
		<a class="carousel-control right" href="#leoproducttab-bestseller" data-slide="next">next</a>


		<div class="carousel-inner">
			<div class="item active">
				<div class="product_list grid col-xs-12 col-md-12">
					<div class="row">
						<?php foreach ($latestProducts as $key => $latestProduct) { ?>
						<?php if ($key && $key % 4 == 0) { ?>
					</div>
				</div>
			</div>
			<div class="item">
				<div class="product_list grid col-xs-12 col-md-12">
					<div class="row">
						<?php } ?>
						<div class="ajax_block_product product_block col-md-3 col-xs-12 col-sm-12 first_item">

							<div class="product-container" itemscope="" itemtype="http://schema.org/Product">
								<div class="left-block">
									<div class="product-image-container">
										<div class="leo-more-info" data-idproduct="8">
											<div class="col-1">
												<!-- thumbnails -->
												<div class="views_block">
													<div class="thumbs_list thumbs_list_8">
														<ul class="thumbs_list_frame">
															<li>
																<a href="" rel="other-views"
																   class="thickbox-ajax-8 shown"
																   title="Donec magna diam">
																	<img
																		src="assets/<?php echo $shop->code ?>/images/155-medium_default.jpg"
																		alt="Donec magna diam" height="125" width="125"
																		class="leo-hover-image">
																</a>
															</li>
															<li>
																<a href="" rel="other-views" class="thickbox-ajax-8"
																   title="Donec magna diam">
																	<img
																		src="assets/<?php echo $shop->code ?>/images/154-medium_default.jpg"
																		alt="Donec magna diam" height="125" width="125"
																		class="leo-hover-image">
																</a>
															</li>
														</ul>
													</div>
												</div>
											</div>
										</div>
										<a class="product_img_link"
										   href="<?php echo Helpers\LocationUrls::location('/catalogue/' . $latestProduct->articul); ?>"
										   title="Vivamus condimentum" itemprop="url">
											<img class="replace-2x img-responsive"
												 src="assets/<?php echo $shop->code ?>/images/154-home_default.jpg"
												 alt="Donec magna diam"
												 title="Donec magna diam" itemprop="image">
											<span class="product-additional" data-idproduct="8"><img
													class="img-responsive" title="" alt=""
													src="assets/<?php echo $shop->code ?>/images/155-home_default.jpg"></span>
										</a>

						 <span class="new-box">
						 <span class="new-label product-label">New</span></span>
									</div>
									<div class="functional-buttons clearfix">
										<div class="button-container">
											<a class="button ajax_add_to_cart_button btn btn-default" href=""
											   rel="nofollow" title="Add to cart"
											   data-id-product="8">
												<i class="fa fa-shopping-cart"></i> Add to cart
											</a>
										</div>


										<div class="wishlist">
											<a class="addToWishlist btn wishlistProd_8" title="Wishlist" href=""
											   rel="8">

											</a>
										</div>

										<div class="view_detail">
											<a itemprop="url" class="lnk_view btn" href="" title="View">

											</a>
										</div>

									</div>

								</div>
								<div class="right-block">
									<h5 itemprop="name">
										<?php echo Phalcon\Tag::linkTo(array('catalogue/' . $latestProduct->articul, $latestProduct->brand . ', ' . ucfirst($latestProduct->name), 'class' => 'product-name', 'title' => $latestProduct->name)); ?>
									</h5>

									<div class="product-desc" itemprop="description">
										<?php echo $latestProduct->description; ?>
									</div>
									<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"
										 class="content_price">
						 <span itemprop="price" class="price product-price"><?php echo $latestProduct->price; ?>
						 </span>
										<meta itemprop="priceCurrency" content="USD">
									</div>


									<div class="comments_note clearfix" itemprop="aggregateRating" itemscope=""
										 itemtype="http://schema.org/AggregateRating">
										<div class="star_content clearfix">
											<div class="star"></div>
											<div class="star"></div>
											<div class="star"></div>
											<div class="star"></div>
											<div class="star"></div>
											<meta itemprop="worstRating" content="0">
											<meta itemprop="ratingValue" content="0">
											<meta itemprop="bestRating" content="5">
										</div>
										<span class="nb-comments"><span itemprop="reviewCount">0</span> Review(s)</span>
									</div>


						 <span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="availability">
						 <span class="available-now">
						 <link itemprop="availability" href="http://schema.org/InStock">In stock</span>
						 </span>

									<div class="product-flags">
									</div>

								</div>
								<div class="product_bottom hidden-xs">
									<a class="quick-view" href="">
										<i class="fa fa-plus"></i> Quick View
									</a>
								</div>
							</div>
							<!-- .product-container> -->


						</div>
						<?php } ?>
					</div>
				</div>
			</div>
		</div>


	</div>
</div>
<!--**************************************************************************************************************************************-->


<!--**************************************************************************************************************************************-->
<div class="tab-pane" id="leoproducttabfeatured">
	<div class="carousel slide" id="leoproducttab-featured">

		<a class="carousel-control left" href="#leoproducttab-featured" data-slide="prev">prev</a>
		<a class="carousel-control right" href="#leoproducttab-featured" data-slide="next">next</a>


		<div class="carousel-inner">
			<div class="item active">
				<div class="product_list grid col-xs-12 col-md-12">
					<div class="row">
						<?php foreach ($latestProducts as $key => $latestProduct) { ?>
						<?php if ($key && $key % 4 == 0) { ?>
					</div>
				</div>
			</div>
			<div class="item">
				<div class="product_list grid col-xs-12 col-md-12">
					<div class="row">
						<?php } ?>
						<div class="ajax_block_product product_block col-md-3 col-xs-12 col-sm-12 first_item">

							<div class="product-container" itemscope="" itemtype="http://schema.org/Product">
								<div class="left-block">
									<div class="product-image-container">
										<div class="leo-more-info" data-idproduct="8">
											<div class="col-1">
												<!-- thumbnails -->
												<div class="views_block">
													<div class="thumbs_list thumbs_list_8">
														<ul class="thumbs_list_frame">
															<li>
																<a href="" rel="other-views"
																   class="thickbox-ajax-8 shown"
																   title="Donec magna diam">
																	<img
																		src="assets/<?php echo $shop->code ?>/images/155-medium_default.jpg"
																		alt="Donec magna diam" height="125" width="125"
																		class="leo-hover-image">
																</a>
															</li>
															<li>
																<a href="" rel="other-views" class="thickbox-ajax-8"
																   title="Donec magna diam">
																	<img
																		src="assets/<?php echo $shop->code ?>/images/154-medium_default.jpg"
																		alt="Donec magna diam" height="125" width="125"
																		class="leo-hover-image">
																</a>
															</li>
														</ul>
													</div>
												</div>
											</div>
										</div>
										<a class="product_img_link"
										   href="<?php echo Helpers\LocationUrls::location('/catalogue/' . $latestProduct->articul); ?>"
										   title="Vivamus condimentum" itemprop="url">
											<img class="replace-2x img-responsive"
												 src="assets/<?php echo $shop->code ?>/images/154-home_default.jpg"
												 alt="Donec magna diam"
												 title="Donec magna diam" itemprop="image">
											<span class="product-additional" data-idproduct="8"><img
													class="img-responsive" title="" alt=""
													src="assets/<?php echo $shop->code ?>/images/155-home_default.jpg"></span>
										</a>

						 <span class="new-box">
						 <span class="new-label product-label">New</span></span>
									</div>
									<div class="functional-buttons clearfix">
										<div class="button-container">
											<a class="button ajax_add_to_cart_button btn btn-default" href=""
											   rel="nofollow" title="Add to cart"
											   data-id-product="8">
												<i class="fa fa-shopping-cart"></i> Add to cart
											</a>
										</div>


										<div class="wishlist">
											<a class="addToWishlist btn wishlistProd_8" title="Wishlist" href=""
											   rel="8">

											</a>
										</div>

										<div class="view_detail">
											<a itemprop="url" class="lnk_view btn" href="" title="View">

											</a>
										</div>

									</div>

								</div>
								<div class="right-block">
									<h5 itemprop="name">
										<?php echo Phalcon\Tag::linkTo(array('catalogue/' . $latestProduct->articul, $latestProduct->brand . ', ' . ucfirst($latestProduct->name), 'class' => 'product-name', 'title' => $latestProduct->name)); ?>
									</h5>

									<div class="product-desc" itemprop="description">
										<?php echo $latestProduct->description; ?>
									</div>
									<div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer"
										 class="content_price">
						 <span itemprop="price" class="price product-price"><?php echo $latestProduct->price; ?>
						 </span>
										<meta itemprop="priceCurrency" content="USD">
									</div>


									<div class="comments_note clearfix" itemprop="aggregateRating" itemscope=""
										 itemtype="http://schema.org/AggregateRating">
										<div class="star_content clearfix">
											<div class="star"></div>
											<div class="star"></div>
											<div class="star"></div>
											<div class="star"></div>
											<div class="star"></div>
											<meta itemprop="worstRating" content="0">
											<meta itemprop="ratingValue" content="0">
											<meta itemprop="bestRating" content="5">
										</div>
										<span class="nb-comments"><span itemprop="reviewCount">0</span> Review(s)</span>
									</div>


						 <span itemprop="offers" itemscope="" itemtype="http://schema.org/Offer" class="availability">
						 <span class="available-now">
						 <link itemprop="availability" href="http://schema.org/InStock">In stock</span>
						 </span>

									<div class="product-flags">
									</div>

								</div>
								<div class="product_bottom hidden-xs">
									<a class="quick-view" href="">
										<i class="fa fa-plus"></i> Quick View
									</a>
								</div>
							</div>
							<!-- .product-container> -->


						</div>
						<?php } ?>
					</div>
				</div>
			</div>
		</div>


	</div>
</div>
<!--**************************************************************************************************************************************-->


</div>
</div>


</div>
</div>
<!-- /MODULE Block specials -->
<script>
	$(document).ready(function () {
		$('#leoproducttab .carousel').each(function () {
			$(this).carousel({
				pause: 'hover',
				interval: 8000
			});
		});

		$("#leoproducttab .nav-tabs li", this).first().addClass("active");
		$("#leoproducttab .tab-content .tab-pane", this).first().addClass("active");

	});
</script>
</div>
</div>
<div class="row ">
	<div class="widget col-lg-9 col-md-9 col-sm-12 col-xs-12 col-sp-12">
		<div class="widget-html block">
			<div class="block_content">
				<div class="box-line h3">
					<div>Latest News</div>
				</div>
				<div class="blogs">
					<div class="row">
						<div class="col-sm-6 col-md-4">
							<div class="thumbnail">
								<div class="caption">
									<div class="blog-title"><a href="">Lorem ipsum dolor</a>
									</div>
									<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi
										porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id
										elit.</p>

									<p><a class="link" href="">Read more</a>
									</p>
								</div>
							</div>
						</div>
						<div class="col-sm-6 col-md-4">
							<div class="thumbnail">
								<div class="caption">
									<div class="blog-title"><a href="">Phasellus non massa</a>
									</div>
									<p>Vivamus vel scelerisque urna, at rhoncus nibh. Morbi lobortisAliquam molestie
										nibh at mi ornare scelerisque. Nullam facilisis egestas nunc, vitae congue metus
										molestie..</p>

									<p><a class="link" href="">Read more</a>
									</p>
								</div>
							</div>
						</div>
						<div class="col-sm-6 col-md-4">
							<div class="thumbnail">
								<div class="caption">
									<div class="blog-title"><a href="">Duis in purus tristique</a>
									</div>
									<p>Donec convallis, nulla id eleifend lobortis, ligula ipsum mollis leo, vel
										vehicula urna velit facilisis purus. In est velit, suscipit sed lobortis ut.</p>

									<p><a class="link" href="">Read more</a>
									</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="widget col-lg-3 col-md-3 col-sm-12 col-xs-12 col-sp-12">
		<!-- Block Newsletter module-->
		<div id="newsletter_block_left" class="block col-md-12 col-sm-12">
			<h5>Newsletter</h5>

			<div class="block_content">
				<form method="post">
					<div class="form-group">
						<input class="inputNew form-control grey newsletter-input" id="newsletter-input" type="text"
							   name="email" size="18" value="Enter your e-mail">
						<button type="submit" name="submitNewsletter" class="btn btn-default button button-small">
							<span>subscrlbe</span>
						</button>
						<input type="hidden" name="action" value="0">
					</div>
				</form>
			</div>
		</div>
		<!-- /Block Newsletter module-->
	</div>
</div>
<div class="row ">
	<div class="widget col-lg-12 col-md-12 col-sm-12 col-xs-12 col-sp-12">
		<div class="widget-html block">
			<div class="block_content">
				<p><img src="assets/<?php echo $shop->code ?>/images/img-news.jpg" alt="" width="1147" height="165">
				</p>
			</div>
		</div>
	</div>
</div>
</div>
</section>
</div>
</div>
</section>