<div class="hotline">
	<div id="hot_line_buttons">
		<div class="button" onclick="catalogue.hotLinePrev();">&#x2191;</div>
		<div class="button" onclick="catalogue.hotLineNext();">&#x2193;</div>
	</div>
	<div id="hot_line"></div>
	<div class="micro-cart" style="display: none;" onclick="basket.get_small_basket()">Корзина</div>
	<div class="micro-customer" onclick="global.go({url:'/customer/'})"></div>
	<div class="search">
		<input class="search_field" type="text" id="CATALOGUE_SEARCH" onchange="catalogue.search(event, this)" onkeyup="catalogue.search(event, this)" onblur="catalogue.search_blur()" onfocus="catalogue.search_focus()" value=""/>
		<div id="hints_loading"><img src="/assets/<?php echo $shop['code']; ?>/images/z95ru/hints_loading.gif"/></div>
		<button id="CATALOGUE_SEARCH_BUTTON" style="display:none;" onclick="catalogue.start_search=true;catalogue.search();">Искать</button>
		<div style="height: 2px; font-size: 2px;">&nbsp;</div>
		<div id="CATALOGUE_SEARCH_HINT" style="display:none;" class="CATALOGUE_SEARCH Shadow" onmouseout="catalogue.search_hint_out()" onmouseover="catalogue.search_hint_over()" onmousemove="catalogue.search_hint_move()"></div>
	</div>
</div>

<table class="page_container" height="100%">
	<tr class="header" style="height:60px;">
		<td style="padding-top:40px;">
			<div class="logo">
				<a href="/"><img src="/assets/<?php echo $shop['code']; ?>/images/d-t.gif" /></a>

			</div>

			<div class="phone" style="white-space:nowrap;"><span>+7 495</span>664-23-85<br><span style="font-size: 0.6em; white-space: nowrap;">круглосуточно, без выходных</span></div>					<div class="helper">
				<div class="item">
					<?=$this->tag->linkTo('about', 'О магазине'); ?>
				</div>
				<div class="item">
					<?=$this->tag->linkTo('brands', 'Бренды'); ?>
				</div>

				<div class="sale">
					<div class="item">
						<?=$this->tag->linkTo('catalogue/sale', 'Распродажа'); ?>
					</div><br>
					<div class="percent">
						<div class="item">
							<?=$this->tag->linkTo('catalogue/sales?percent=20', '20<span>%</span>'); ?>
						</div>
						<div class="item">
							<?=$this->tag->linkTo('catalogue/sales?percent=50', '50<span>%</span>'); ?>
						</div>
						<div class="item">
							<?=$this->tag->linkTo('catalogue/sales?percent=70', '70<span>%</span>'); ?>
						</div>
					</div>
				</div>

				<div class="item new"><a href="/catalogue/new">Новинки</a></div>
			</div>
			<div class="top-cart">
				<div class="cart" onclick="basket.get_small_basket()"><img src="/assets/<?php echo $shop['code']; ?>/images/z95ru/icon-cart.png" /></div>
				<h3><a href="/customer/cart">Корзина</a></h3>
				<span id="BASKET_INFO"></span>
			</div>
		</td>
	</tr>
	<tr style="min-height: 600px;">
		<td>