<!-- Верхнее меню навигации -->
<?php echo $navigation->toHtml('top'); ?>
<!-- Верхнее меню навигации -->

<script type="text/javascript">
		$('.header-menu-item').each(function (i, el) {
			if ($('.submenu', el).length) {
				$(el).hover(function() {
					//$('.header-menu-item .submenu').hide();
					$('.header-menu-item > a').removeClass('s');
					$('.submenu', el).show();
					$('a', el).eq(0).addClass('s');
				});
				$(el).mouseleave(function() {
					$('.header-menu-item .submenu').hide();
					$('.header-menu-item a').removeClass('s');
				});
			}
		});
		$('body').click(function() {
			$('.header-menu-item .submenu').hide();
			$('.header-menu-item a').removeClass('s');
		});
</script>