<div id="hot_line_inner" style="position:absolute;left:0px;top:0px;">
	<?php if(isset($params) && !empty($params)): ?>
		<?php if($params['use_capital']): ?>
			<?php if($shop['country_code'] == $params['country']): ?>
				<?php $target = $viewTranslate['DELIVERY_FOR_CITY']; ?>
			<?php else: ?>
				<?php
					$targets = ['RU' => 'России','UA' => 'Украине','BY' => 'Беларуси','KZ' => 'Казахстану','GE' => 'Грузии'];
					$target = sprintf($viewTranslate['DELIVERY_FOR'], $targets[strtoupper($shop['country'])]);
				?>
			<?php endif; ?>
		<?php else: ?>
			<?php $target = sprintf($viewTranslate['DELIVERY_IN'], \Helpers\Catalogue::wordDeclension($params['city'])); ?>
		<?php endif; ?>

		<div style="height:20px;widht:100%;">
			<?=$this->tag->linkTo([['for' => 'about-delivery'], $target.' '.$viewTranslate['DELIVERY_FREE']]); ?>
		</div>
		<?php if($orders_count > 0): ?>
			<?php
				$count = intval($orders_count * $params['num_factor']);
				$city = ($params['use_capital'] || 'none' == mb_strtolower($params['city']) || empty($params['city'])) ? $params['capital_city'] : $params['city'];
			?>
			<div style="height:20px;widht:100%;">
				<?=$viewTranslate['FOR_MONTH'];?> <?=(preg_match('/^(В|в)/', $city) ? 'во' : 'в')?> <?=\Helpers\Catalogue::wordDeclension($city)?> <?=\Helpers\Catalogue::wordEnding($count, 'доставлен')?> <?=$count?> <?=\Helpers\Catalogue::wordEnding($count, 'заказ');?>
			</div>
			<?php foreach($buy_items as $id => $item): ?>
				<?php if(isset($items[$id])): ?>
					<?php
					$item['user_city'] = ('none' == mb_strtolower($item['user_city']) ? $params['capital_city'] : $item['user_city']);
					?>
					<div style="height:20px;widht:100%;">
						<?=$viewTranslate['BUYED_NOW'];?>:
						<a href="<?='/catalogue/'.$items[$id]['articul']?>"><?=$items[$id]['name'].' '.$items[$id]['brand_name']?></a>
						(<?=$items[$id]['articul']?>)

						<?php if(isset($categories[$id])): ?>
							(<a href="/catalogue/<?=$categories[$id]['parent_alias']?>/<?=$categories[$id]['category_alias']?>">
                                <?=$categories[$id]['category_name']?>
							</a>)
						<?php endif;?>
						<?=$viewTranslate['FOR'];?> <?=number_format($item['price'], 0, '.', ' ')?> <?=$shop['currency_symbol']?>
						<?=(strlen($item['user_city']) > 0 ? '(<span style="text-transform: capitalize;">'.trim(preg_replace('/^(г|Г|пгт|c|C)(\.|\s)/', '', $item['user_city'])).'</span>)' : '')?>
					</div>
				<? endif; ?>
			<?php endforeach; ?>
		<?php endif;?>
	<?php else:?>

	<?php endif;?>
</div>