<?php if(isset($discounts['shop_discounts']['type'])):?>
	<tr>
		<td><?=$viewTranslate['DISCOUNT'];?> <?=$discounts['shop_discounts']['current'];?>% (<?=$this->tag->linkTo([['for' => 'about-discounts'], $viewTranslate['ABOUT_DISCOUNTS'], 'target' => '_blank']);?>)</td>
		<td class="number discount"><?=number_format($discounts['sum']-$discounts['shop_discounts']['discount_sum'], 0, '.', ' ');?> <?php echo $shop['currency_symbol'] ?></td>
	</tr>
	<tr>
		<td><?=$viewTranslate['WITH_DISCOUNT'];?></td>
		<td class="number discount"><?=number_format($discounts['shop_discounts']['discount_sum'], 0, '.', ' '); ?> <?php echo $shop['currency_symbol'] ?></td>
	</tr>
<?php endif; ?>