<!-- Фильтры -->
<div class="paging">
	<div class="info"><?=$viewTranslate["SORT_BY"];?></div>

	<?php
		// определяю состояние по умолчанию

		if(!isset($query['sort']['rating']) || !in_array($query['sort']['rating'], ['asc', 'desc']))
			$sort['rating']	=	'desc';
		else if($query['sort']['rating'] == 'desc')
			$sort['rating']	=	'asc';
		else $sort['rating'] =	'desc';

		if(!isset($query['sort']['date_income']) || !in_array($query['sort']['date_income'], ['asc', 'desc']))
			$sort['date_income']	=	'desc';
		else if($query['sort']['date_income'] == 'desc')
			$sort['date_income']	=	'asc';
		else $sort['date_income'] =	'desc';

		if(!isset($query['sort']['price']) || !in_array($query['sort']['price'], ['asc', 'desc']))
			$sort['price']	=	'asc';
		else if($query['sort']['price'] == 'desc')
			$sort['price']	=	'asc';
		else $sort['price'] =	'desc';

		if(!isset($query['sort']['discount']) || !in_array($query['sort']['discount'], ['asc', 'desc']))
			$sort['discount']	=	'asc';
		else if($query['sort']['discount'] == 'desc')
			$sort['discount']	=	'asc';
		else $sort['discount'] =	'desc';
	?>

	<div class="link <?=(isset($query['sort']['rating'])) ? 'selected' : '';?>" onclick="$(this).child().click();">
		<?php if(!empty($query)): ?>
			<a class="isAjax" href="?<?=urldecode(http_build_query(array_merge($query, ['sort' => ['rating' => $sort['rating']]]))); ?>"><?=$viewTranslate["RATING_FIELD"];?></a>
		<?php else: ?>
			<a class="isAjax" href="?<?=urldecode(http_build_query(['sort' => ['rating' => $sort['rating']]])); ?>"><?=$viewTranslate["RATING_FIELD"];?></a>
		<?php endif;?>
		<?php if($sort['rating'] != 'desc'):?> <span>▼</span><?php else:?> <span>▲</span><?php endif;?>
	</div>

	<div class="link <?=(isset($query['sort']['date_income'])) ? 'selected' : '';?>" onclick="$(this).child().click();">
		<?php if(!empty($query)): ?>
			<a class="isAjax" href="?<?=urldecode(http_build_query(array_merge($query, ['sort' => ['date_income' => $sort['date_income']]]))); ?>"><?=$viewTranslate["NEW_FIELD"];?></a>
		<?php else: ?>
			<a class="isAjax" href="?<?=urldecode(http_build_query(['sort' => ['date_income' => $sort['date_income']]])); ?>"><?=$viewTranslate["NEW_FIELD"];?></a>
		<?php endif;?>
		<?php if($sort['date_income'] != 'desc'):?> <span>▼</span><?php else:?> <span>▲</span><?php endif;?>
	</div>

	<div class="link <?=(isset($query['sort']['price'])) ? 'selected' : '';?>" onclick="$(this).child().click();">
		<?php if(!empty($query)): ?>
			<a class="isAjax" href="?<?=urldecode(http_build_query(array_merge($query, ['sort' => ['price' => $sort['price']]]))); ?>"><?=$viewTranslate["PRICE_FIELD"];?></a>
		<?php else: ?>
			<a class="isAjax" href="?<?=urldecode(http_build_query(['sort' => ['price' => $sort['price']]])); ?>"><?=$viewTranslate["PRICE_FIELD"];?></a>
		<?php endif;?>
		<?php if($sort['price'] != 'desc'):?> <span>▼</span><?php else:?> <span>▲</span><?php endif;?>
	</div>

	<div class="link <?=(isset($query['sort']['discount'])) ? 'selected' : '';?>" onclick="$(this).child().click();">
		<?php if(!empty($query)): ?>
			<a class="isAjax" href="?<?=urldecode(http_build_query(array_merge($query, ['sort' => ['discount' => $sort['discount']]]))); ?>"><?=$viewTranslate["DISCOUNT_FIELD"];?></a>
		<?php else: ?>
			<a class="isAjax" href="?<?=urldecode(http_build_query(['sort' => ['discount' => $sort['discount']]])); ?>"><?=$viewTranslate["DISCOUNT_FIELD"];?></a>
		<?php endif;?>
		<?php if($sort['discount'] != 'asc'):?> <span>▼</span><?php else:?> <span>▲</span><?php endif;?>
	</div>
</div>
<div class="clear hr"></div>
<!-- Фильтры -->
