<?php if(!empty($pagination)): ?>
	<!-- Постраничная навигация -->
	<? $this->partial('partials/catalogue/pagination', ['pagination' => $pagination]); ?>
	<!-- /Постраничная навигация -->
<?php else:?>
	<div class="paging">
		<div class="info">Показаны все <?=$count;?></div>
	</div>
<?php endif;?>
<?
	//$this->partial('partials/catalogue/filters', ['pagination' => $pagination]);
	//$this->partial('partials/catalogue/sortbar', [
	//	'pagination' 	=> $pagination,
	//	'viewTranslate' => $viewTranslate,
	//]);
?>
<!-- Выдача товаров -->
<div class="CatalogueItems insert-filters">

	<!-- Сайдбар -->
	<div class="tags-filter Shadow" id="filterSidebar"></div>
	<!-- /Сайдбар -->

	<!-- Вывод палитры -->
	<?php if(isset($items) && !empty($items)): ?>
		<?php foreach($items as $item): ?>
			<?php
				if(isset($item['filter_size']) && $item['filter_size'])
				{
					$arraySize = explode(',',$item['filter_size']);
					uksort($arraySize, "\Helpers\Catalogue::itemCompareSize");
				}
				$img = array_values(json_decode($item['preview'], true))[0]; // images json decode
				$this->partial('partials/catalogue/item_short');		// render small product
			?>
		<?php endforeach; ?>
	<?php else: ?>
		<h2>Ничего не найдено</h2>
		<h4>Попробуйте изменить условия поиска</h4>
	<?php endif; ?>
	<!-- /Вывод палитры -->

</div>
<!-- /Выдача товаров -->
<div style="clear: both;"></div>
<?php if(!empty($pagination)): ?>
	<!-- Постраничная навигация -->
	<? $this->partial('partials/catalogue/pagination', ['pagination' => $pagination]); ?>
	<!-- /Постраничная навигация -->
<?php else:?>
	<div class="paging">
		<div class="info">Показаны все <?=$count;?></div>
	</div>
<?php endif;?>
<script>
	$(function() {

		var sideBar 	=	document.getElementById('filterSidebar');
		var renderItems =	document.getElementById('renderItems');

		var exludeSidebar = [
			'favorites',
			'brands'
			],
			currentPath	=	window.location.pathname.split('/').slice(-1)[0];

		if(!$.inArray(currentPath, exludeSidebar))
		{
			$(sideBar).hide();
		}
		else
		{
			// показую сайдбар
			$.getJSON("/json/tags", function(data) {
				if(data.response.length)
					$(sideBar).html(data.response);
			});
		}


		// обработка ajax для перерисовки выдачи

		$('a.isAjax').on('click', function(e) {

			e.preventDefault();

			global.showStatus('common.loading');

			var url =	window.location.pathname +$(this).attr('href');

			$.getJSON(url, function(data) {
				console.log(data);

				if(data.response.length)
					$(renderItems).html(data.response);
					window.history.pushState("","", url);
				global.hideStatus('common.loading');
			});
		});
	});
</script>
