<?php
	//@modify Stanislav добавление переменных в partial  шаблон
	//$this->partial('partials/catalogue/filters', ['pagination' => $pagination]);
	//$this->partial('partials/catalogue/sortbar', [
	//	'pagination' 	=> $pagination,
	//	'viewTranslate' => $viewTranslate,
	//]);
?>
<!-- Выдача товаров -->
<div class="CatalogueItems insert-filters">

	<!-- Сайдбар -->
	<div id="filterSidebar"></div>
	<!-- /Сайдбар -->

	<!-- Вывод палитры -->
	<?php if(isset($items) && !empty($items)): ?>
		<?php foreach($items as $item): ?>
			<?php

				if(isset($item['filter_size']) && $item['filter_size'])
				{
					$arraySize = explode(',',$item['filter_size']);
					uksort($arraySize, "\Helpers\Catalogue::itemCompareSize");
				}
				$img = array_values(json_decode($item['preview'], true))[0]; // images json decode
				$this->partial('partials/catalogue/item_short');		// render small product
			?>
		<?php endforeach; ?>
	<?php else: ?>
		В данном разделе товаров нет
	<?php endif; ?>
	<!-- /Вывод палитры -->

</div>
<!-- /Выдача товаров -->
<div style="clear: both;"></div>
<?php
	//@modify Stanislav добавление переменных в partial  шаблон
	//$this->partial('partials/catalogue/filters', ['pagination' => $pagination]);
	//$this->partial('partials/catalogue/sortbar', [
	//	'pagination' => $pagination,
	//	'viewTranslate' => $viewTranslate,
	//]);
?>
