<?php
	//@modify Stanislav добавление переменных в partial  шаблон
	//$this->partial('partials/catalogue/filters', ['pagination' => $pagination]);
	//$this->partial('partials/catalogue/sortbar', [
	//	'pagination' 	=> $pagination,
	//	'viewTranslate' => $viewTranslate,
	//]);
?>
<!-- Выдача товаров -->
<div class="CatalogueItems insert-filters">
	<!-- Сайдбар -->
	<div id="filterSidebar"></div>
	<!-- /Сайдбар -->
	<!-- Вывод палитры товаров -->
	<?php if(isset($items) && !empty($items)): ?>
		<?php foreach($items as $item): ?>

		<?php endforeach; ?>
	<?php endif; ?>
	<!-- /Вывод палитры товаров -->
</div>
<!-- /Выдача товаров -->

<div class="CatalogueItems insert-filters">
	<div id="filterSidebar"></div>

		<?php
		// декодорию превью
		$img = array_values(json_decode($item['images']))[0]; ?>
		<?php $this->partial('partials/catalogue/item_short');?>
	<?php endforeach; ?>
	<?php if(count($items)<=20):?>
		<a class="loader_items js_loader_items" href="" attr-ids="<?=implode(',',$itemsline);?>">Показать похожие</a>
		<div class="js_wrapper_loader_items"></div>
		<a class="loader_items js_loader_items_close" style="display: none;" href="" >Скрыть похожие</a>

		<script>
			$('.js_loader_items').click(function(e){
				e.preventDefault();
				global.showStatus('common.loading');

				$('html, body').animate({
					scrollTop: $(".js_loader_items").offset().top
				}, 1000);
				global.hideStatus('common.loading');
				$('.js_loader_items_close').show();
				$('.js_loader_items').toggle();

				$.ajax({
					type: 'POST',
					url: window.location.pathname,
					data: 'ids='+$('.js_loader_items').attr('attr-ids')+'&ajax=getRecommendedItems',
					dataType: "json",
					success: function(data) {
						$('html, body').animate({
							scrollTop: $(".js_loader_items").offset().top
						}, 1000);
						$('.js_wrapper_loader_items').html(data.html);
						global.hideStatus('common.loading');
						$('.js_loader_items_close').show();
						$('.js_loader_items').toggle();
					},
					dataType: 'json',
					timeout: 120000,
					error: function (data, textStatus, jqXHR) {
						global.showAjaxErrorStatus(textStatus);
					}
				});
			});
			$('.js_loader_items_close').click(function (e){
				e.preventDefault();
				$('.js_loader_items').toggle();
				$('.js_loader_items_close').show();
				$(this).hide();
				$('.js_wrapper_loader_items').empty();
				$('html, body').animate({
					scrollTop: $("#CONTENT").offset().top
				}, 1000);
			});
			<?php
				if(isset($_REQUEST['show']) && $_REQUEST['show']=='similar'){
					echo '$(".js_loader_items").click();';
				}
			?>
		</script>

	<?php endif;?>

</div>
<div style="clear: both;"></div>
<?php
	//@modify Stanislav добавление переменных в partial  шаблон
	$this->partial('partials/catalogue/filters', ['pagination' => $pagination]);
	$this->partial('partials/catalogue/sortbar', [
		'pagination' => $pagination,
		'viewTranslate' => $viewTranslate,
	]);
?>
