<div id="categories_block_left" class="block highlighted nopadding noborder">
	<h4 class="title_block">
		<?=(!isset($category['name'])) ? $viewTranslate['CATALOGUE']: $category['name']; ?>
	</h4>

	<div class="block_content list-block">
		<ul class="tree dynamized" style="display: block;">
			<li>
				<a href="#" class="accordion-link selected">
					<?=(!isset($category['name'])) ? $viewTranslate['CATALOGUE']: $category['name']; ?>
					<span class="leo-qty badge pull-right"><?=(isset($allcount)) ? $allcount : ''; ?></span>
				</a>

				<?php if(!empty($categoriesSide)): ?>
					<ul class="sub">
						<?php foreach($categoriesSide as $category): ?>
							<?php if($template == 'categories'): // для категорий?>
								<li>
									<a href="<? echo Helpers\LocationUrls::location($this->request->getURI().'/'.$category['alias']); ?>" title="<?=$category['name']; ?>">
										<?=$category['name']; ?>
									</a>
								</li>
							<?elseif($template == 'subcategories' || $template == 'products'): // для подкатегорий?>

								<?php if(isset($count[$category['id']]['product_count'])): ?>
								<li>
									<a href="<? echo Helpers\LocationUrls::location($this->request->getURI().'/'.$category['alias']); ?>" title="<?=$category['name']; ?>">
										<?=$category['name']; ?>
										<?php if($template != 'categories'): ?>
										<span style="" class="leo-qty badge pull-right"><?=$count[$category['id']]['product_count']?></span>
										<?php endif; ?>
									</a>
								</li>
								<?endif;?>
							<?php endif; ?>

						<?php endforeach; ?>
					</ul>
				<?endif;?>
			</li>
		</ul>
	</div>
</div>
<script type="text/javascript">
	$(document).ready(function() {


		$('a.accordion-link').on('click', function(e) {
			e.preventDefault();
			if($("ul.sub").is(":visible"))
			{
				//$(this).removeClass('OPEN').addClass('CLOSE');
				$("ul.sub").slideUp("slow");
			}
			else
			{
				//$(this).removeClass('CLOSE').addClass('OPEN');
				$("ul.sub").slideDown("slow");
			}
		});
	});
</script>
