<div class="content_sortPagiBar product-filter clearfix">
	<div class="sortPagiBar clearfix">
		<div class="col-sm-7 col-md-7 col-xs-12">
			<div class="sort">
				<ul class="display hidden-xs">
					<li class="display-title">Display:</li>
					<li class="selected" id="grid"><a rel="nofollow" href="" title="Grid"><i class="icon-th-large"></i><!--Grid-->
						</a></li>
					<li id="list"><a rel="nofollow" href="" title="List"><i class="icon-th-list"></i><!--List--></a>
					</li>
				</ul>

				<form id="productsSortForm" action="" class="productsSortForm">
					<div class="select selector1">
						<label for="selectProductSort"></label>
						<select id="selectProductSort" class="selectProductSort form-control">
							<option value="position:asc" selected="selected">Sort by</option>
							<option value="price:asc">Price: Lowest first</option>
							<option value="price:desc">Price: Highest first</option>
							<option value="name:asc">Product Name: A to Z</option>
							<option value="name:desc">Product Name: Z to A</option>
							<option value="quantity:desc">In stock</option>
							<option value="reference:asc">Reference: Lowest first</option>
							<option value="reference:desc">Reference: Highest first</option>
						</select>
					</div>
				</form>
				<!-- /Sort products -->


			</div>
		</div>
		<div class="col-sm-5 col-md-5 col-xs-12">
			<div class="product-compare">
				<form method="post" action="" class="compare-form">
					<button type="submit" class="btn btn-default button button-medium bt_compare bt_compare"
							disabled="disabled">
						<span>Compare (<strong class="total-compare-val">0</strong>)<i
								class="icon-chevron-right right"></i></span>
					</button>
					<input name="compare_product_count" class="compare_product_count" value="0" type="hidden">
					<input name="compare_product_list" class="compare_product_list" value="" type="hidden">
				</form>


			</div>
		</div>
	</div>
</div>
<div class="product_list row list">
	<?php if(sizeof($items) > 0): ?>
		<?php foreach($items as $item): ?>
			<div class="ajax_block_product col-sp-12 first-in-line last-item-of-tablet-line last-item-of-mobile-line col-xs-12">
				<div class="product-container">
					<div class="row">
						<div class="left-block col-xs-4 col-xs-5 col-md-4">
							<div class="product-image-container">
								<div class="leo-more-info" data-idproduct="<?=$item['id'];?>">
									<div class="col-1">
										<!-- thumbnails -->
										<div class="views_block">
											<div class="thumbs_list thumbs_list_<?=$item['id'];?>">
												<ul class="thumbs_list_frame">
													<li>
														<a href="" rel="other-views" class="thickbox-ajax-<?=$item['id'];?> shown"
														   title="<?=$item['name'].' '.$item['brand_name']?>">
															<?=$this->tag->image(array(
																'assets/'.$shop['code'].'/images/155-medium_default.jpg',
																'alt' 	=> $item['name'].' '.$item['brand_name'],
																'class'	=> 'leo-hover-image'
															));?>
														</a>
													</li>
													<li>
														<a href="" rel="other-views" class="thickbox-ajax-<?=$item['id'];?>"
														   title="Donec magna diam">
															<?=$this->tag->image(array(
																'assets/'.$shop['code'].'/images/154-medium_default.jpg',
																'alt' 	=> $item['name'].' '.$item['brand_name'],
																'class'	=> 'leo-hover-image'
															));?>
														</a>
													</li>
												</ul>
											</div>
										</div>
									</div>
								</div><? //echo Helpers\LocationUrls::location($this->request->getURI().'/'.$item->articul); ?>
								<a class="product_img_link" href="<? echo Helpers\LocationUrls::location('/catalogue/'.$item['articul']); ?>" title="Vivamus condimentum" itemprop="url">
									<?=$this->tag->image(array(
										'assets/'.$shop['code'].'/images/154-home_default.jpg',
										'alt' 		=> 	$item['name'].' '.$item['brand_name'],
										'title' 	=> 	$item['name'].' '.$item['brand_name'],
										'class'		=> 	'replace-2x img-responsive',
										'itemprop'	=>	'image'
									));?>
									<span class="product-additional" data-idproduct="<?=$item['id'];?>">
										<?=$this->tag->image(array(
											'assets/'.$shop['code'].'/images/155-home_default.jpg',
											'alt' 		=> 	$item['name'].' '.$item['brand_name'],
											'title' 	=> 	$item['name'].' '.$item['brand_name'],
											'class'		=> 	'img-responsive',
										));?>
									</span>
								</a>

								<span class="new-box">
									<span class="new-label product-label">New</span>
								</span>
							</div>

							<div class="functional-buttons  clearfix">
								<div class="button-container">
									<a class="button ajax_add_to_cart_button btn btn-default" href="" rel="nofollow"
									   title="Add to cart" data-id-product="<?=$item['id'];?>">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</a>
								</div>

								<div class="wishlist">
									<a class="addToWishlist btn wishlistProd_<?=$item['id'];?>" title="Wishlist" href="#" rel="<?=$item['id'];?>" onclick="">

									</a>
								</div>


								<div class="compare">
									<a class="add_to_compare btn" href="" data-id-product="<?=$item['id'];?>">
										<!--Add to Compare--></a>
								</div>
							</div>

						</div>
						<div class="center-block col-xs-4 col-xs-7 col-md-8">
							<h5 itemprop="name">
								<a class="product-name" href="" title="<?=$item['name'].' '.$item['brand_name'];?>" itemprop="url">
									<?=$item['name'].' '.$item['brand_name'];?>
								</a>
							</h5>

							<div itemprop="aggregateRating" itemscope="" class="comments_note">
								<div class="star_content clearfix">
									<div class="star"></div>
									<div class="star"></div>
									<div class="star"></div>
									<div class="star"></div>
									<div class="star"></div>
									<meta itemprop="worstRating" content="0">
									<meta itemprop="ratingValue" content="0">
									<meta itemprop="bestRating" content="5">
								</div>
								<span class="nb-comments"><span itemprop="reviewCount">0</span> Review(s)</span>
							</div>
							<p class="product-desc">
								<?=$item['description'];?>
							</p>

							<div class="right-block">
								<div class="right-block-content row">
									<div class="content_price col-xs-5 col-md-12">
										<span itemprop="price" class="price product-price">
											<?=$item['price'];?> <?=$shop['currency_symbol'];?>
										</span>
										<meta itemprop="priceCurrency" content="<?=$shop['currency'];?>">
									</div>
								</div>
								<div class="product-flags">
								</div>
									<span class="availability">
										<span class="available-now">
											<link itemprop="availability" href="">In stock</span>
										</span>

									<div class="product_bottom">
										<a class="quick-view" href="" rel="">
											<i class="fa fa-plus"></i>
												Quick View
										</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

			<div class="content_sortPagiBar">
				<div class="bottom-pagination-content clearfix">
					<form method="post" action="" class="compare-form">
						<button type="submit" class="btn btn-default button button-medium bt_compare bt_compare_bottom"
								disabled="disabled">
				<span>Compare (<strong class="total-compare-val">0</strong>)<i class="icon-chevron-right right"></i></span>
						</button>
						<input name="compare_product_count" class="compare_product_count" value="0" type="hidden">
						<input name="compare_product_list" class="compare_product_list" value="" type="hidden">
					</form>
		<?php endforeach; ?>
		<!-- Pagination -->
		<div id="pagination_bottom" class="pagination clearfix">
			<form class="showall" action="" method="get">
				<div>
					<button type="submit" class="btn btn-default button exclusive-medium">
						<span>Show all</span>
					</button>
					<input name="id_lang" value="1" type="hidden">
					<input name="id_category" value="12" type="hidden">
					<input name="controller" value="category" type="hidden">
					<input name="n" id="nb_item" class="hidden" value="12">
				</div>
			</form>

			<ul class="pagination">
				<?if($pager['current'] == 1):?>
					<li id="pagination_previous_bottom" class="disabled pagination_previous">
						<span>
							<i class="icon-chevron-left"></i> <b><?=$viewTranslate['PREVIOUS']; ?></b>
						</span>
					</li>
				<?php else: ?>
					<li id="pagination_previous_bottom" class="disabled pagination_previous">
						<a href="<? echo Helpers\LocationUrls::location($this->request->getQuery()['_url'].'?page='.($pager['current']-1)); ?>">
							<i class="icon-chevron-left"></i> <b><?=$viewTranslate['PREVIOUS']; ?></b>
						</a>
					</li>
				<?php endif; ?>
				<?php for($i = 1; $i< 10; $i++):  //$pager['allpages'];?>
					<?if($i == $pager['current']): ?>
						<li class="active current disabled">
										<span>
											<span><?=$i;?></span>
										</span>
						</li>
					<?else:?>
						<li>
							<a href="<? echo Helpers\LocationUrls::location($this->request->getQuery()['_url'].'?page='.$i); ?>">
								<span><?=$i;?></span>
							</a>
						</li>
					<?php endif; ?>
				<?php endfor; ?>
				<li id="pagination_next_bottom" class="<?=($pager['current'] == $pager['allpages']) ? 'disabled' : ''; ?> pagination_next">
					<a href="<? echo Helpers\LocationUrls::location($this->request->getQuery()['_url'].'?page='.($pager['current']+1)); ?>">
						<b><?=$viewTranslate['NEXT']; ?></b> <i class="icon-chevron-right"></i>
					</a>
				</li>
			</ul>
		</div>
		<div class="product-count">
			<?=printf($viewTranslate['SHOW_ITEMS'], $pager['offset'], $pager['show'], $pager['items']); ?>
		</div>
		<!-- /Pagination -->
		</div>
		</div>
	<?php else: ?>
		<?=$viewTranslate['ITEMS_NOT_FOUND']; ?>
	<?php endif; ?>
</div>
<!-- Products list -->