<div class="index-top-categories">
<?php if(!empty($salesGroup)): ?>
	<?php foreach($salesGroup as $gender => $values): $opacity = 1;?>
		<div class="category id_<?=$gender;?>">
			<h2><?=($gender == 1) ? 'Мужчинам' : 'Женщинам'?><span class="count"></span></h2>
			<div class="discount-tiles">
				<?php $values = array_reverse($values); foreach($values as $sales): ?>
					<?php if($sales['percent'] != 100): ?>
						<a href="<?=\Helpers\LocationUrls::location('/catalogue/sales?percent[]='.$sales['percent'].'&sex[]=0&sex[]='.$gender.'&sex[]=3'); ?>" class="tile" style="opacity: <?=$opacity;?>">
							<div class="value"><?=$sales['percent'];?>%</div>
							<div class="count">наименований — <span><?=$sales['count'];?></span></div>
						</a>
					<?php endif; ?>
				<? $opacity = sprintf("%f", ($opacity - 0.15)); endforeach; ?>
				<a href="<?=\Helpers\LocationUrls::location('/catalogue/sale?percent[]='.$values[0]['percent'].'&sex[]=0&sex[]=1&sex[]=2&sex[]=3'); ?>" class="tile" style="opacity: <?=$opacity;?>">
					<div class="value">Все</div>
					<div class="count">наименований — <span><?=$values[0]['count'];?></span></div>
				</a>
			</div>
		</div>
	<?php endforeach; ?>
<?php else: ?>
	Распродаж нет
<?php endif; ?>
</div>