<div class="paging">
	<div class="info"><?=$viewTranslate['SORT_BY'];?></div>

	<?php
		$sortby = $pagination['sortby'];
		$orderby = $pagination['orderby'];
		$pagination['page'] = 1;
		unset($pagination['count']);
	?>

	<?php
		$pagination['sortby'] = 'rating';
		$url = $_REQUEST['_url'] . '?' . http_build_query($pagination);
		$class = '';
		if($sortby =='rating'){
			$class = ' selected';
			if($orderby=='desc'){
				$order = '▼';
			} else {
				$order = '▲';
			}
			echo '<div class="link'.$class.'">'.$viewTranslate['RATING_FIELD'].' <span>'.$order.'</span></div>';
		} else {
			echo '<div class="link" onclick="$(this).find(\'a\')[0].click();"><a href="'.$url.'">'.$viewTranslate['RATING_FIELD'].' </a><span>▼</span></div>';
		}
	?>

	<?php
		$pagination['sortby'] = 'new';
		$url = $_REQUEST['_url'] . '?' . http_build_query($pagination);
		$class = '';
		if($sortby =='new'){
			$class = ' selected';
			if($orderby=='desc'){
				$order = '▼';
			} else {
				$order = '▲';
			}
			echo '<div class="link'.$class.'">'.$viewTranslate['NEW_FIELD'].' <span>'.$order.'</span></div>';
		} else {
			echo '<div class="link" onclick="$(this).find(\'a\')[0].click();"><a href="'.$url.'">'.$viewTranslate['NEW_FIELD'].'</a><span>▼</span></div>';
		}
	?>


	<?php
		$pagination['sortby'] = 'price';
		$url = $_REQUEST['_url'] . '?' . http_build_query($pagination);
	?>

	<?php
		$pagination['sortby'] = 'price';
		$class = '';
		if($sortby =='price'){
			$class = ' selected';
			if($orderby=='desc'){
				$pagination['orderby'] = 'asc';
				$order = '▼';
				$orderRevers = '▲';
			} else {
				$pagination['orderby'] = 'desc';
				$order = '▲';
				$orderRevers = '▼';
			}
			$url = $_REQUEST['_url'] . '?' . http_build_query($pagination);
			echo '<div class="link'.$class.'" onclick="$(this).find(\'a\')[0].click();"><a href="'.$url.'">'.$viewTranslate['PRICE_FIELD'].'</a><span>'.$order.'</span></div>';
		} else {
			echo '<div class="link'.$class.'" onclick="$(this).find(\'a\')[0].click();"><a href="'.$url.'">'.$viewTranslate['PRICE_FIELD'].'</a><span>'.$order.'</span></div>';
		}
	?>

	<?php
		$pagination['sortby'] = 'discount';
		$url = $_REQUEST['_url'] . '?' . http_build_query($pagination);
		$class = '';
		if($sortby =='discount'){
			$class = ' selected';
			if($orderby=='desc'){
				$order = '▼';
			} else {
				$order = '▲';
			}
			echo '<div class="link'.$class.'">'.$viewTranslate['DISCOUNT_FIELD'].' <span>'.$order.'</span></div>';
		} else {
			echo '<div class="link" onclick="$(this).find(\'a\')[0].click();"><a href="'.$url.'">'.$viewTranslate['DISCOUNT_FIELD'].'</a><span>▼</span></div>';
		}
	?>
</div>
<div id="sizes_filters" class="paging" style="border:0;">
	<div class="info">&nbsp;</div>
	<div id="tags_filter_button" class="link active hidden"
		 onclick="$('.tags-filter, #tags_filter_button').toggleClass('hidden');"><?=$viewTranslate['FILTER_FIELD'];?>
	</div>
</div>
<div class="clear hr"></div>