<div id="stores_block_left" class="block">
	<h4 class="title_block">
		<a href="#" title="Our stores">
			Our stores
		</a>
	</h4>

	<div style="" class="block_content blockstore">
		<p class="store_image">
			<a href="#" title="Our stores">
				<img class="img-responsive" src="images/store.jpg" alt="Our stores">
			</a>
		</p>

		<div>
			<a class="btn btn-default button button-small" href="#" title="Our stores">
				<span>Discover our stores<i class="icon-chevron-right right"></i></span>
			</a>
		</div>
	</div>
</div