<!-- Catalogue all subcategories template -->
<div class="element-catalogue_items">
	<div>
		<?php if(!empty($subcategories)): ?>
			<?php foreach($subcategories as $category): ?>
				<?php
					// decode image
					$images 	= json_decode($category['img'], true);
					$product_id	=	min(array_keys($images));
				?>
				<div class="catalogue-category" onclick="window.location.href= '<?=\Helpers\LocationUrls::location('/catalogue/'.$category['parent_alias'].'/'.$category['alias']);?>">
					<div class="leader">
						<img class="image" src="http://img3.z95.ru/f/p/c_0_100_300_400/sep-tilt_shift/600x600/catalogue/<?=$product_id;?>/<?=$images[$product_id][1];?>">
					</div>
					<div class="title">
						<a href="<?=\Helpers\LocationUrls::location('/catalogue/'.$category['parent_alias'].'/'.$category['alias']);?>"><?=$category['name'];?></a>
						<span class="count"><?=$category['count_prod'];?></span>
					</div>
				</div>
			<?php endforeach; ?>
		<?php else: ?>
			<?=$viewTranslate['CATEGORIES_NOT_FOUND']; ?>
		<?php endif; ?>
	</div>
	<div class="clear"></div>
</div>
<!-- Catalogue all subcategories template -->
