<?php
	if(isset($item['show_title']) && strlen($item['show_title'])>0)
		echo '</div><div style="clear:both;"></div><h2>'.$item['show_title'].'</h2><div style="clear:both;"></div><div class="CatalogueItems">';


	$photos = previews($item['preview'], $item['photos']);

	if (!empty($img_size)) {
		$resize = $img_size;
		//$resize = '225x275';
	} else {
		$resize = '225x275';
	}

	$sizes = $this->catalogue_model->parse_sizes($item['cat_sizes_count']);
	if( isset($shop['discount_id']) and $shop['discount_id'] == 2 ){
		$price = '<s>'.$item['discount_price'].'</s>&nbsp;'.$item['discount_price']*0.5;
	}else if( isset($shop['discount_id']) and $shop['discount_id'] == 5 ){
		$price = '<s>'.$item['discount_price'].'</s>&nbsp;'.$item['discount_price']*0.7;
	}else if( isset($shop['discount_id']) and $shop['discount_id'] == 10 ){
		$price = '<s>'.$item['discount_price'].'</s>&nbsp;'.$item['discount_price']*0.8;
	}else if( isset($shop['discount_id']) and $shop['discount_id'] == 11 ){
		$price = '<s>'.$item['discount_price'].'</s>&nbsp;'.$item['discount_price']*0.9;
	}else{
		if ($item['price'] != $item['discount_price']) {
			$price = '<s>'.$item['price'].'</s>&nbsp;'.$item['discount_price'];
		} else if (isset($item['price'])) {
			$price = $item['price'];
		} else {
			$price = 0;
		}
	}
	$flag = (isset($item['is_new']) && $item['is_new'] == 1) ? '<img src="/i/z95ru/new_flag.png" class="new_flag" />' : '';

	if(!isset($item['rating']))
		$item['rating'] = 0;
	if(!isset($item['sizes_count']))
		$item['sizes_count'] = 0;

	$cat_url = isset($categories['array'][$item['cat_parent']]) ? $categories['array'][$item['cat_parent']]['url'] : '';
	$href = '/catalogue'.$cat_url.'/'.$item['articul'].'/';

	/** Определим количества данного товара в корзине для каждого размера и общее */
	$basket_count = array();
	$total_basket_count = 0;

	foreach($sizes as $size=>$max_count) {
		$basket_count[$size] = (isset($basket_items[$item['cat_id']]) && isset($basket_items[$item['cat_id']]['sizes'][$size])) ? $basket_items[$item['cat_id']]['sizes'][$size] : 0;
		$total_basket_count += $basket_count[$size];
	}

?>
<div class="item">
	<div style="z-index: 2; position: relative;">

		<? if (count($sizes) && $item['discount_price'] > 0) { ?>
			<? $container_id = 'sizes_'.$item['cat_id']; ?>

			<div style="display: none;" id="<?=$container_id?>" class="sizes_win"
				 cat_id="<?=$item['cat_id']?>"
				 price="<?=$item['discount_price']?>"
				 quantity="<?=$quantity?>"
				 layout_mode="right"
				>
				<img onclick="$('#<?=$container_id?>').fadeOut();" class="close_png" src="/i/d-t.gif">
				<form autocomplete="off">
					<table>
						<tr>
							<? if (true || $quantity == 'multiple') { ?>

								<td id="leftPart" style="padding: 0px 10px 0px 0px; height: 320px;">
									<?=$flag?>
									<div style="height:275px;">
										<a href="<?=$href;?>"><img class="preview" src="<?=img('/f/catalogue/'.$item['cat_id'].'/'.$photos[0], $resize)?>"/></a>
									</div>
									<div class="info">
										<a href="<?=$href;?>">
											<? if(isset($no_brands) and !$no_brands){ ?>
												<b><?=$item['brand'];?></b>
											<? } ?>
											<?=$item['cat_title']?> <span class="articul"><?=$item['articul']?></span>
										</a>
									</div>
								</td>
							<? } ?>
							<td id="rightPart" class="rightPart">
								<div class="warning hidden" id="warning" onclick="$(this).fadeOut();"></div>
								<?php if($quantity == 'single'): ?>
							<?php if(!(isset($sizes[0]) && count($sizes) == 1)):?>
								<span>
							                    <?=lang('Выберите размер')?>:
						                    </span>
								<br clear="all"/>
							<?php endif;?>
								<div class="small-sizes">
									<?php else: ?>
									<table class="small-sizes">
										<tr>
											<th><?=lang('Размер')?></th>
											<th><?=lang('Кол-во')?></th>
											<th><?=lang('В корзине')?></th>
											<th><?=lang('На складе')?></th>
										</tr>
										<?php endif;?>
										<?php
											$button_disabled = true;
											foreach($sizes as $size=>$value['count']):
												if($quantity == 'single'): $style = '';
													if(isset($sizes[0]) && count($sizes) == 1):
														$style = 'style="display: none;" checked="checked"';
														$button_disabled = false;
													endif;
													?>
													<div class="size">
														<label <?=($basket_count[$size] == $value['count'] ? 'title="'.lang('Этот размер весь у вас в корзине!').'"' : '')?>>
															<input type="checkbox" data-check="<?php echo $item['item_id']; ?>" name="products[<?php echo $item['item_id']; ?>][sizes][<?php echo $size ?>]" class="setsize" value="1" <?php if($basket_count[$size] == $value['count']): ?> disabled="true" checked="checked" <?php endif; ?> />
															<br/>
															<?=($size !== 0 ? $size : lang('Универсальный размер'))?>
														</label>
													</div>
												<?php elseif($quantity == 'multiple'): ?>
													<tr>
														<td>
															<?=($size !== 0 ? $size : lang('Универ-<br/>сальный'))?>
														</td>
														<td>
															<input type="text" size="2" maxlength="3" class="setsize"
																   onkeydown="return Cart.isNumber(event);"
																   onkeyup="Cart.isValid($(this))"
																   pattern="/[0-9]+/"
																   data-input="<?php echo $item['item_id']; ?>"
																   value=""
																   data-params ='{"item_id" : "<?php echo $item['item_id'];?>", "size" : "<?php echo $size;?>"}'
																   name ="products[<?php echo $item['item_id']; ?>][sizes][<?php echo $size ?>]"
																   data-max="<?php echo $value['count'] ?>"
																   data-incart="<?php echo $basket_count[$size] ?>"
																<?php if($basket_count[$size] == $value['count']): ?>
																	disabled="true"
																	title="<?php echo lang('Этот размер весь у вас в корзине!') ?>"
																<?php endif; ?>/>
														</td>
														<td>
															<?=($basket_count[$size] > 0 ? $basket_count[$size] : '&mdash;')?>
														</td>
														<td>
															<span style="font-size: 7pt;"><?=($value['count'] > 5 ? lang('более').' 5' : $value['count'])?></span>
														</td>
													</tr>
												<?php endif; ?>
											<?php endforeach; ?>

										<?php  if($quantity == 'single' && !(isset($sizes[0]) && count($sizes) == 1)):?>
											<br clear="all"/><br/>
											<div class="left">
												<label>
													<input type="checkbox" data-check="<?php echo $item['item_id']; ?>" name="products[<?php echo $item['item_id']; ?>][sizes][?]" class="setsize" value="?" style="float: left; margin-right: 5px;"/>
													<?=lang('Не уверен в размере')?> — <br/><?=lang('хочу обсудить с менеджером')?>
												</label>
											</div>
										<?php endif; ?>
										<?php if($quantity == 'single'): ?>
								</div>
								<?php else: ?>
					</table>
					<?php endif;?>
					<br clear="all"/>
					<div class="add-button">
						<button id="add" class="add-button button" type="button" data-add="<?php echo $item['item_id']; ?>"><?php echo lang('Добавить в корзину') ?></button>
					</div>
					</td>
					</tr>
					</table>
				</form>
			</div>

		<? }
		?>
	</div>
	<? if( isset($photos[0]) && strlen($photos[0])>0 ) { ?>
		<div class="photo_hover" onmouseover="catalogue.startSlideShow('slide_show_<?=$item['cat_id'];?>');" onmouseout="catalogue.stopSlideShow('slide_show_<?=$item['cat_id'];?>');">
			<a href="<?=$href;?>">
				<img src="/i/d-t.gif" style="width:225px; height:275px;" />
			</a>
		</div>
		<div style="z-index: 0; position: relative; width:225px; height:275px;" id="slide_show_<?=$item['cat_id'];?>" >
			<?=$flag?>
			<? if (!empty($show_discount) && !empty($item['discount'])) { ?>
				<div class="item-discount <?=(!empty($flag) ? 'new-flag' : '')?>"><?=$item['discount']?></div>
			<? } ?>
			<ul>
				<? if( isset($photos[0]) && strlen($photos[0])>0 ) { ?>
					<li class="show"><a href="<?=$href;?>"><img class="preview" src="<?=img('/f/catalogue/'.$item['cat_id'].'/'.$photos[0], $resize)?>"/></a></li>
				<? } ?>
				<? if( isset($photos[1]) && strlen($photos[1])>0 ) { ?>
					<li><a href="<?=$href;?>"><img class="preview add" src="<?=img('/f/catalogue/'.$item['cat_id'].'/'.$photos[1], $resize)?>" /></a></li>
				<? } ?>
			</ul>
		</div>
	<? } else { ?>
		<a href="<?=$href;?>">
			<img src="/i/d-t.gif" style="width:225px; height:275px;"/>
		</a>
	<? } ?>
	<div class="info">
		<a href="<?=$href;?>">
			<? if(isset($no_brands) and !$no_brands){ ?>
				<b><?=$item['brand'];?></b>
			<? } ?>
			<?=$item['cat_title']?> <span class="articul"><?=$item['articul']?></span>
		</a>

		<? if (!isset($sizes[0])) {
			if (mb_strlen($item['cat_sizes']) > 30) {
				$item['cat_sizes'] = mb_substr($item['cat_sizes'], 0, mb_strpos($item['cat_sizes'], '/', 27)).'<br>'.mb_substr($item['cat_sizes'], mb_strpos($item['cat_sizes'], '/', 27)+1);
			}
			?>
			<div class="sizes"><span style="color:gray"><?=lang('Размеры')?>:</span> <span class="size-letters"><?=$item['cat_sizes'];?></span></div>
		<? } ?>

		<div class="price">
			<div><?=$price?>&nbsp;<span class="sign"><?=$shop['currency']?></span> </div>

			<?
				# Вернуть после распродажи
				if( isset($shop['discount_id']) and $shop['discount_id'] == 10 or isset($shop['discount_id']) and $shop['discount_id'] == 11 or isset($shop['discount_id']) and $shop['discount_id'] == 12 ){

				}else{
					$tt->load_template('catalogue/item_sale_price', array('item' => $item));
				}
			?>

			<? if (isset($sizes) && is_array($sizes) && count($sizes)>0 && $item['discount_price']>0) { ?>
				<div id="sizes_button_<?=$item['cat_id']?>" class="sizes-button<?=($total_basket_count ? ' on' : '')?>" onclick="basket.beforeAddToBasket('<?=$container_id?>');">
					<? if ($total_basket_count) { ?>
						<?=$total_basket_count?>
					<? } else { ?>
						&nbsp;
					<? } ?>
				</div>
			<? } ?>
			<img alt="<?=lang('Понравилось')?>" id="fav_icon_<?=$item['cat_id']?>" onclick="catalogue.addFavorites(<?=$item['cat_id']?>, this)" src="/i/d-t.gif" class="like_<?=(in_array($item['cat_id'],$favorites) ? 'on' : 'off')?>"/>
		</div>
	</div>
</div>