<div id="viewed-products_block_left" class="block nobackground nopadding">
	<h4 class="title_block">Viewed products</h4>

	<div class="block_content products-block" style="">
		<ul>
			<li class="clearfix first_item">
				<a class="products-block-image" href="" title="More about Morbi vitae cons">
					<img src="images/154-small_default.jpg" alt="Donec magna diam">
				</a>

				<div class="product-content">
					<h5>
						<a class="product-name" href="" title="More about Morbi vitae cons">
							Morbi vitae cons
						</a>
					</h5>

					<p class="product-description">Lorem psum dolor aet cosctetur...</p>
				</div>
			</li>
			<li class="clearfix last_item">
				<a class="products-block-image" href="" title="More about Vivamus condimentum">
					<img src="images/154-small_default.jpg" alt="Donec magna diam">
				</a>

				<div class="product-content">
					<h5>
						<a class="product-name" href="" title="More about Vivamus condimentum">
							Vivamus condimentum
						</a>
					</h5>

					<p class="product-description">Lorem psum dolor aet cosctetur...</p>
				</div>
			</li>
		</ul>
	</div>
</div>