<section id="center_column" class="col-md-9">
	<h1 class="page-heading product-listing"><span class="cat-name">Categories&nbsp;</span><span class="heading-counter"><?printf($viewTranslate['COUNT_PRODUCTS'], $products_count); ?></span></h1>
	<div class="content_scene_cat">
		<!-- Category image -->
			<div class="content_scene_cat_bg">
				<img class="img-responsive" src="images/12-category_default.jpg" alt="Categories" title="Categories" id="categoryImage">
					<div class="cat_desc">
					<div class="rte"><p>Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec convallis sem mauris facilisis, eros ut iaculis suscipit sollicitudin dignissim nunc urna eu.Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec.</p></div>
				</div>
			</div>
		</div>

<!-- Subcategories -->
<div id="subcategories" class="block">
	<h4 class="title_block subcategory-heading">Subcategories</h4>
	<div class="clearfix row">
		<div class="col-md-3 col-xs-6 col-sp-12">
			<div class="subcategories">
				<div class="subcategory-image">
					<a href="" title="Outerwear" class="img">
						<img class="replace-2x" src="images/13-category_default.jpg" alt="">
					</a>
				</div>
				<h5><a class="subcategory-name" href="">Outerwear</a></h5>
				<div class="cat_desc"><p>Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec convallis sem mauris facilisis, eros ut iaculis suscipit sollicitudin dignissim nunc urna eu.Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec</p></div>
			</div>
		</div>
		<div class="col-md-3 col-xs-6 col-sp-12">
			<div class="subcategories">
				<div class="subcategory-image">
					<a href="" title="Dresses" class="img">
						<img class="replace-2x" src="images/14-category_default.jpg" alt="">
					</a>
				</div>
				<h5><a class="subcategory-name" href="">Dresses</a></h5>
				<div class="cat_desc"><p>Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec convallis sem mauris facilisis, eros ut iaculis suscipit sollicitudin dignissim nunc urna eu.Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec</p></div>
			</div>
		</div>
		<div class="col-md-3 col-xs-6 col-sp-12">
			<div class="subcategories">
				<div class="subcategory-image">
					<a href="" title="Accessories" class="img">
						<img class="replace-2x" src="images/17-category_default.jpg" alt="">
					</a>
				</div>
				<h5><a class="subcategory-name" href="">Accessories</a></h5>
				<div class="cat_desc"><p>Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec convallis sem mauris facilisis, eros ut iaculis suscipit sollicitudin dignissim nunc urna eu.Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec.</p></div>
			</div>
		</div>
		<div class="col-md-3 col-xs-6 col-sp-12">
			<div class="subcategories">
				<div class="subcategory-image">
					<a href="" title="New" class="img">
						<img class="replace-2x" src="images/15-category_default.jpg" alt="">
					</a>
				</div>
				<h5><a class="subcategory-name" href="">New</a></h5>
				<div class="cat_desc"><p>Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec convallis sem mauris facilisis, eros ut iaculis suscipit sollicitudin dignissim nunc urna eu.Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec</p></div>
			</div>
		</div>
		<div class="col-md-3 col-xs-6 col-sp-12">
			<div class="subcategories">
				<div class="subcategory-image">
					<a href="" title="Clothes" class="img">
						<img class="replace-2x" src="images/22-category_default.jpg" alt="">
					</a>
				</div>
				<h5><a class="subcategory-name" href="">Clothes</a></h5>
				<div class="cat_desc"><p>Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec convallis sem mauris facilisis, eros ut iaculis suscipit sollicitudin dignissim nunc urna eu.Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec...</p></div>
			</div>
		</div>
		<div class="col-md-3 col-xs-6 col-sp-12">
			<div class="subcategories">
				<div class="subcategory-image">
					<a href="" title="Bootoms" class="img">
						<img class="replace-2x" src="images/16-category_default.jpg" alt="">
					</a>
				</div>
				<h5><a class="subcategory-name" href="">Bootoms</a></h5>
				<div class="cat_desc"><p>Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec convallis sem mauris facilisis, eros ut iaculis suscipit sollicitudin dignissim nunc urna eu.Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec</p></div>
			</div>
		</div>
	</div>
</div>
<div class="content_sortPagiBar product-filter clearfix">
	<div class="sortPagiBar clearfix">
		<div class="col-sm-7 col-md-7 col-xs-12">
			<div class="sort">
				<ul class="display hidden-xs">
					<li class="display-title">Display:</li>
					<li class="selected" id="grid"><a rel="nofollow" href="" title="Grid"><i class="icon-th-large"></i><!--Grid--></a></li>
					<li id="list"><a rel="nofollow" href="" title="List"><i class="icon-th-list"></i><!--List--></a></li>
				</ul>

				<form id="productsSortForm" action="" class="productsSortForm">
					<div class="select selector1">
						<label for="selectProductSort"></label>
						<select id="selectProductSort" class="selectProductSort form-control">
							<option value="position:asc" selected="selected">Sort by</option>
							<option value="price:asc">Price: Lowest first</option>
							<option value="price:desc">Price: Highest first</option>
							<option value="name:asc">Product Name: A to Z</option>
							<option value="name:desc">Product Name: Z to A</option>
							<option value="quantity:desc">In stock</option>
							<option value="reference:asc">Reference: Lowest first</option>
							<option value="reference:desc">Reference: Highest first</option>
						</select>
					</div>
				</form>
				<!-- /Sort products -->


			</div>
		</div>
		<div class="col-sm-5 col-md-5 col-xs-12">

			<div class="product-compare">
				<form method="post" action="" class="compare-form">
					<button type="submit" class="btn btn-default button button-medium bt_compare bt_compare" disabled="disabled">
						<span>Compare (<strong class="total-compare-val">0</strong>)<i class="icon-chevron-right right"></i></span>
					</button>
					<input name="compare_product_count" class="compare_product_count" value="0" type="hidden">
					<input name="compare_product_list" class="compare_product_list" value="" type="hidden">
				</form>





			</div>
		</div>
	</div>
</div>




<div class="product_list row list">




<div class="ajax_block_product col-sp-12 first-in-line     last-item-of-tablet-line      last-item-of-mobile-line col-xs-12"><div class="product-container"><div class="row"><div class="left-block col-xs-4 col-xs-5 col-md-4">
				<div class="product-image-container">
					<div class="leo-more-info" data-idproduct="8"><div class="col-1">
							<!-- thumbnails -->
							<div class="views_block">
								<div class="thumbs_list thumbs_list_8">
									<ul class="thumbs_list_frame">
										<li>
											<a href="" rel="other-views" class="thickbox-ajax-8 shown" title="Donec magna diam">
												<img src="images/155-medium_default.jpg" alt="Donec magna diam" height="125" width="125" rel="" class="leo-hover-image">
											</a>
										</li>
										<li>
											<a href="" rel="other-views" class="thickbox-ajax-8" title="Donec magna diam">
												<img src="images/154-medium_default.jpg" alt="Donec magna diam" height="125" width="125" rel="" class="leo-hover-image">
											</a>
										</li>
									</ul>
								</div>
							</div>
						</div></div>
					<a class="product_img_link" href="" title="Vivamus condimentum" itemprop="url">
						<img class="replace-2x img-responsive" src="images/154-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
						<span class="product-additional" data-idproduct="8"><img class="img-responsive" title="" alt="" src="images/155-home_default.jpg"></span>
					</a>

							<span class="new-box">
					<span class="new-label product-label">New</span>
				</span>
				</div>


				<div class="functional-buttons  clearfix">
					<div class="button-container">
						<a class="button ajax_add_to_cart_button btn btn-default" href="" rel="nofollow" title="Add to cart" data-id-product="8">
							<i class="fa fa-shopping-cart"></i>
							Add to cart
						</a>
					</div>



					<div class="wishlist">
						<a class="addToWishlist btn wishlistProd_8" title="Wishlist" href="#" rel="8" onclick="">

						</a>
					</div>


					<div class="compare">
						<a class="add_to_compare btn" href="" data-id-product="8">
							<!--Add to Compare--></a>
					</div>
				</div>

			</div><div class="center-block col-xs-4 col-xs-7 col-md-8"><h5 itemprop="name">
					<a class="product-name" href="" title="Vivamus condimentum" itemprop="url">
						Vivamus condimentum
					</a>
				</h5><div itemprop="aggregateRating" itemscope="" class="comments_note">
					<div class="star_content clearfix">
						<div class="star"></div>
						<div class="star"></div>
						<div class="star"></div>
						<div class="star"></div>
						<div class="star"></div>
						<meta itemprop="worstRating" content="0">
						<meta itemprop="ratingValue" content="0">
						<meta itemprop="bestRating" content="5">
					</div>
					<span class="nb-comments"><span itemprop="reviewCount">0</span> Review(s)</span>
				</div><p class="product-desc">
					Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec convallis sem mauris facilisis, eros ut iaculis suscipit sollicitudin dignissim nunc
				</p><div class="right-block"><div class="right-block-content row"><div class="content_price col-xs-5 col-md-12">
									<span itemprop="price" class="price product-price">
						$250.00					</span>
							<meta itemprop="priceCurrency" content="USD">


						</div></div><div class="product-flags">
					</div><span class="availability">
											<span class="available-now">
							<link itemprop="availability" href="">In stock						</span>
									</span><div class="product_bottom">
						<a class="quick-view" href="" rel="">
							<i class="fa fa-plus"></i>
							Quick View
						</a>
					</div></div></div></div></div></div>





<div class="ajax_block_product col-sp-12     last-item-of-tablet-line      last-item-of-mobile-line col-xs-12"><div class="product-container"><div class="row"><div class="left-block col-xs-4 col-xs-5 col-md-4">
				<div class="product-image-container">
					<div class="leo-more-info" data-idproduct="9"><div class="col-1">
							<!-- thumbnails -->
							<div class="views_block">
								<div class="thumbs_list thumbs_list_9">
									<ul class="thumbs_list_frame">
										<li>
											<a href="" rel="other-views" class="thickbox-ajax-9 shown" title="Donec magna diam">
												<img src="images/157-medium_default.jpg" alt="Donec magna diam" height="125" width="125" rel="" class="leo-hover-image">
											</a>
										</li>
										<li>
											<a href="" rel="other-views" class="thickbox-ajax-9" title="Donec magna diam">
												<img src="images/156-medium_default.jpg" alt="Donec magna diam" height="125" width="125" rel="" class="leo-hover-image">
											</a>
										</li>
									</ul>
								</div>
							</div>
						</div></div>
					<a class="product_img_link" href="" title="Donec posuere metus" itemprop="url">
						<img class="replace-2x img-responsive" src="images/156-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
						<span class="product-additional" data-idproduct="9"><img class="img-responsive" title="" alt="" src="images/157-home_default.jpg"></span>
					</a>

							<span class="new-box">
					<span class="new-label product-label">New</span>
				</span>
				</div>


				<div class="functional-buttons  clearfix">
					<div class="button-container">
						<a class="button ajax_add_to_cart_button btn btn-default" href="" rel="nofollow" title="Add to cart" data-id-product="9">
							<i class="fa fa-shopping-cart"></i>
							Add to cart
						</a>
					</div>



					<div class="wishlist">
						<a class="addToWishlist btn wishlistProd_9" title="Wishlist" href="#" rel="9" onclick="">

						</a>
					</div>


					<div class="compare">
						<a class="add_to_compare btn" href="" data-id-product="9">
							<!--Add to Compare--></a>
					</div>
				</div>

			</div><div class="center-block col-xs-4 col-xs-7 col-md-8"><h5 itemprop="name">
					<a class="product-name" href="" title="Donec posuere metus" itemprop="url">
						Donec posuere metus
					</a>
				</h5><div itemprop="aggregateRating" itemscope="" class="comments_note">
					<div class="star_content clearfix">
						<div class="star"></div>
						<div class="star"></div>
						<div class="star"></div>
						<div class="star"></div>
						<div class="star"></div>
						<meta itemprop="worstRating" content="0">
						<meta itemprop="ratingValue" content="0">
						<meta itemprop="bestRating" content="5">
					</div>
					<span class="nb-comments"><span itemprop="reviewCount">0</span> Review(s)</span>
				</div><p class="product-desc">
					Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec convallis sem mauris facilisis, eros ut iaculis suscipit sollicitudin dignissim nunc
				</p><div class="right-block"><div class="right-block-content row"><div class="content_price col-xs-5 col-md-12">
									<span itemprop="price" class="price product-price">
						$350.00					</span>
							<meta itemprop="priceCurrency" content="USD">


						</div></div><div class="product-flags">
					</div><span class="availability">
											<span class="available-now">
							<link itemprop="availability" href="">In stock						</span>
									</span><div class="product_bottom">
						<a class="quick-view" href="" rel="">
							<i class="fa fa-plus"></i>
							Quick View
						</a>
					</div></div></div></div></div></div>





<div class="ajax_block_product col-sp-12     last-item-of-tablet-line      last-item-of-mobile-line col-xs-12"><div class="product-container"><div class="row"><div class="left-block col-xs-4 col-xs-5 col-md-4">
				<div class="product-image-container">
					<div class="leo-more-info" data-idproduct="10"><div class="col-1">
							<!-- thumbnails -->
							<div class="views_block">
								<div class="thumbs_list thumbs_list_10">
									<ul class="thumbs_list_frame">
										<li>
											<a href="" rel="other-views" class="thickbox-ajax-10 shown" title="Donec magna diam">
												<img src="images/159-medium_default.jpg" alt="Donec magna diam" height="125" width="125" rel="" class="leo-hover-image">
											</a>
										</li>
										<li>
											<a href="" rel="other-views" class="thickbox-ajax-10" title="Donec magna diam">
												<img src="images/158-medium_default.jpg" alt="Donec magna diam" height="125" width="125" rel="" class="leo-hover-image">
											</a>
										</li>
									</ul>
								</div>
							</div>
						</div></div>
					<a class="product_img_link" href="" title="Donec magna diam" itemprop="url">
						<img class="replace-2x img-responsive" src="images/158-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
						<span class="product-additional" data-idproduct="10"><img class="img-responsive" title="" alt="" src="images/159-home_default.jpg"></span>
					</a>

							<span class="new-box">
					<span class="new-label product-label">New</span>
				</span>
				</div>


				<div class="functional-buttons  clearfix">
					<div class="button-container">
						<a class="button ajax_add_to_cart_button btn btn-default" href="" rel="nofollow" title="Add to cart" data-id-product="10">
							<i class="fa fa-shopping-cart"></i>
							Add to cart
						</a>
					</div>



					<div class="wishlist">
						<a class="addToWishlist btn wishlistProd_10" title="Wishlist" href="#" rel="10" onclick="">

						</a>
					</div>


					<div class="compare">
						<a class="add_to_compare btn" href="" data-id-product="10">
							<!--Add to Compare--></a>
					</div>
				</div>

			</div><div class="center-block col-xs-4 col-xs-7 col-md-8"><h5 itemprop="name">
					<a class="product-name" href="" title="Donec magna diam" itemprop="url">
						Donec magna diam
					</a>
				</h5><div itemprop="aggregateRating" itemscope="" class="comments_note">
					<div class="star_content clearfix">
						<div class="star"></div>
						<div class="star"></div>
						<div class="star"></div>
						<div class="star"></div>
						<div class="star"></div>
						<meta itemprop="worstRating" content="0">
						<meta itemprop="ratingValue" content="0">
						<meta itemprop="bestRating" content="5">
					</div>
					<span class="nb-comments"><span itemprop="reviewCount">0</span> Review(s)</span>
				</div><p class="product-desc">
					Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec convallis sem mauris facilisis, eros ut iaculis suscipit sollicitudin dignissim nunc
				</p><div class="right-block"><div class="right-block-content row"><div class="content_price col-xs-5 col-md-12">
									<span itemprop="price" class="price product-price">
						$350.00					</span>
							<meta itemprop="priceCurrency" content="USD">


						</div></div><div class="product-flags">
					</div><span class="availability">
											<span class="available-now">
							<link itemprop="availability" href="">In stock						</span>
									</span><div class="product_bottom">
						<a class="quick-view" href="" rel="">
							<i class="fa fa-plus"></i>
							Quick View
						</a>
					</div></div></div></div></div></div>





<div class="ajax_block_product col-sp-12 last-in-line        last-item-of-tablet-line      last-item-of-mobile-line col-xs-12"><div class="product-container"><div class="row"><div class="left-block col-xs-4 col-xs-5 col-md-4">
				<div class="product-image-container">
					<div class="leo-more-info" data-idproduct="11"><div class="col-1">
							<!-- thumbnails -->
							<div class="views_block">
								<div class="thumbs_list thumbs_list_11">
									<ul class="thumbs_list_frame">
										<li>
											<a href="" rel="other-views" class="thickbox-ajax-11 shown" title="Donec magna diam">
												<img src="images/177-medium_default.jpg" alt="Donec magna diam" height="125" width="125" rel="" class="leo-hover-image">
											</a>
										</li>
										<li>
											<a href="" rel="other-views" class="thickbox-ajax-11" title="Donec magna diam">
												<img src="images/176-medium_default.jpg" alt="Donec magna diam" height="125" width="125" rel="" class="leo-hover-image">
											</a>
										</li>
									</ul>
								</div>
							</div>
						</div></div>
					<a class="product_img_link" href="" title="Aenean" itemprop="url">
						<img class="replace-2x img-responsive" src="images/176-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
						<span class="product-additional" data-idproduct="11"><img class="img-responsive" title="" alt="" src="images/177-home_default.jpg"></span>
					</a>

							<span class="new-box">
					<span class="new-label product-label">New</span>
				</span>
				</div>


				<div class="functional-buttons  clearfix">
					<div class="button-container">
						<a class="button ajax_add_to_cart_button btn btn-default" href="" rel="nofollow" title="Add to cart" data-id-product="11">
							<i class="fa fa-shopping-cart"></i>
							Add to cart
						</a>
					</div>



					<div class="wishlist">
						<a class="addToWishlist btn wishlistProd_11" title="Wishlist" href="#" rel="11" onclick="">

						</a>
					</div>


					<div class="compare">
						<a class="add_to_compare btn" href="" data-id-product="11">
							<!--Add to Compare--></a>
					</div>
				</div>

			</div><div class="center-block col-xs-4 col-xs-7 col-md-8"><h5 itemprop="name">
					<a class="product-name" href="" title="Aenean" itemprop="url">
						Aenean
					</a>
				</h5><div itemprop="aggregateRating" itemscope="" itemtype="" class="comments_note">
					<div class="star_content clearfix">
						<div class="star"></div>
						<div class="star"></div>
						<div class="star"></div>
						<div class="star"></div>
						<div class="star"></div>
						<meta itemprop="worstRating" content="0">
						<meta itemprop="ratingValue" content="0">
						<meta itemprop="bestRating" content="5">
					</div>
					<span class="nb-comments"><span itemprop="reviewCount">0</span> Review(s)</span>
				</div><p class="product-desc">
					Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec convallis sem mauris facilisis, eros ut iaculis suscipit sollicitudin dignissim nunc
				</p><div class="right-block"><div class="right-block-content row"><div class="content_price col-xs-5 col-md-12">
									<span itemprop="price" class="price product-price">
						$450.00					</span>
							<meta itemprop="priceCurrency" content="USD">


						</div></div><div class="product-flags">
					</div><span class="availability">
											<span class="available-now">
							<link itemprop="availability" href="">In stock						</span>
									</span><div class="product_bottom">
						<a class="quick-view" href="#" rel="">
							<i class="fa fa-plus"></i>
							Quick View
						</a>
					</div></div></div></div></div></div>





<div class="ajax_block_product col-sp-12 first-in-line   last-line   last-item-of-tablet-line      last-item-of-mobile-line col-xs-12"><div class="product-container"><div class="row"><div class="left-block col-xs-4 col-xs-5 col-md-4">
				<div class="product-image-container">
					<div class="leo-more-info" data-idproduct="12"><div class="col-1">
							<!-- thumbnails -->
							<div class="views_block">
								<div class="thumbs_list thumbs_list_12">
									<ul class="thumbs_list_frame">
										<li>
											<a href="#" rel="other-views" class="thickbox-ajax-12 shown" title="Donec magna diam">
												<img src="images/183-medium_default.jpg" alt="Donec magna diam" height="125" width="125" rel="" class="leo-hover-image">
											</a>
										</li>
										<li>
											<a href="#" rel="other-views" class="thickbox-ajax-12" title="Donec magna diam">
												<img src="images/182-medium_default.jpg" alt="Donec magna diam" height="125" width="125" rel="" class="leo-hover-image">
											</a>
										</li>
									</ul>
								</div>
							</div>
						</div></div>
					<a class="product_img_link" href="#" title="Morbi vitae cons" itemprop="url">
						<img class="replace-2x img-responsive" src="images/182-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
						<span class="product-additional" data-idproduct="12"><img class="img-responsive" title="" alt="" src="images/183-home_default.jpg"></span>
					</a>

							<span class="new-box">
					<span class="new-label product-label">New</span>
				</span>
				</div>


				<div class="functional-buttons  clearfix">
					<div class="button-container">
						<a class="button ajax_add_to_cart_button btn btn-default" href="" rel="nofollow" title="Add to cart" data-id-product="12">
							<i class="fa fa-shopping-cart"></i>
							Add to cart
						</a>
					</div>



					<div class="wishlist">
						<a class="addToWishlist btn wishlistProd_12" title="Wishlist" href="#" rel="12" onclick="">

						</a>
					</div>


					<div class="compare">
						<a class="add_to_compare btn" href="" data-id-product="12">
							<!--Add to Compare--></a>
					</div>
				</div>

			</div><div class="center-block col-xs-4 col-xs-7 col-md-8"><h5 itemprop="name">
					<a class="product-name" href="" title="Morbi vitae cons" itemprop="url">
						Morbi vitae cons
					</a>
				</h5><div itemprop="aggregateRating" itemscope="" class="comments_note">
					<div class="star_content clearfix">
						<div class="star"></div>
						<div class="star"></div>
						<div class="star"></div>
						<div class="star"></div>
						<div class="star"></div>
						<meta itemprop="worstRating" content="0">
						<meta itemprop="ratingValue" content="0">
						<meta itemprop="bestRating" content="5">
					</div>
					<span class="nb-comments"><span itemprop="reviewCount">0</span> Review(s)</span>
				</div><p class="product-desc">
					Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec convallis sem mauris facilisis, eros ut iaculis suscipit sollicitudin dignissim nunc
				</p><div class="right-block"><div class="right-block-content row"><div class="content_price col-xs-5 col-md-12">
									<span itemprop="price" class="price product-price">
						$300.00					</span>
							<meta itemprop="priceCurrency" content="USD">


						</div></div><div class="product-flags">
					</div><span class="availability">
											<span class="available-now">
							<link itemprop="availability" href="">In stock						</span>
									</span><div class="product_bottom">
						<a class="quick-view" href="#" rel="">
							<i class="fa fa-plus"></i>
							Quick View
						</a>
					</div></div></div></div></div></div>





<div class="ajax_block_product col-sp-12   last-line   last-item-of-tablet-line      last-item-of-mobile-line      last-mobile-line col-xs-12"><div class="product-container">
		<div class="row">
			<div class="left-block col-xs-4 col-xs-5 col-md-4">
				<div class="product-image-container">
					<div class="leo-more-info" data-idproduct="14"><div class="col-1">
							<!-- thumbnails -->
							<div class="views_block">
								<div class="thumbs_list thumbs_list_14">
									<ul class="thumbs_list_frame">
										<li>
											<a href="#" rel="other-views" class="thickbox-ajax-14 shown" title="Donec magna diam">
												<img src="images/181-medium_default.jpg" alt="Donec magna diam" height="125" width="125" rel="" class="leo-hover-image">
											</a>
										</li>
										<li>
											<a href="#" rel="other-views" class="thickbox-ajax-14" title="Donec magna diam">
												<img src="images/180-medium_default.jpg" alt="Donec magna diam" height="125" width="125" rel="" class="leo-hover-image">
											</a>
										</li>
									</ul>
								</div>
							</div>
						</div></div>
					<a class="product_img_link" href="#" title="Morbi vitae cons" itemprop="url">
						<img class="replace-2x img-responsive" src="images/180-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
						<span class="product-additional" data-idproduct="14"><img class="img-responsive" title="" alt="" src="images/181-home_default.jpg"></span>
					</a>

							<span class="new-box">
					<span class="new-label product-label">New</span>
				</span>
				</div>


				<div class="functional-buttons  clearfix">
					<div class="button-container">
						<a class="button ajax_add_to_cart_button btn btn-default" href="=#" rel="nofollow" title="Add to cart" data-id-product="14">
							<i class="fa fa-shopping-cart"></i>
							Add to cart
						</a>
					</div>



					<div class="wishlist">
						<a class="addToWishlist btn wishlistProd_14" title="Wishlist" href="#" rel="14" onclick="">

						</a>
					</div>


					<div class="compare">
						<a class="add_to_compare btn" href="#" data-id-product="14">
							<!--Add to Compare--></a>
					</div>
				</div>

			</div><div class="center-block col-xs-4 col-xs-7 col-md-8"><h5 itemprop="name">
					<a class="product-name" href="#" title="Morbi vitae cons" itemprop="url">
						Morbi vitae cons
					</a>
				</h5><div itemprop="aggregateRating" itemscope="" class="comments_note">
					<div class="star_content clearfix">
						<div class="star"></div>
						<div class="star"></div>
						<div class="star"></div>
						<div class="star"></div>
						<div class="star"></div>
						<meta itemprop="worstRating" content="0">
						<meta itemprop="ratingValue" content="0">
						<meta itemprop="bestRating" content="5">
					</div>
					<span class="nb-comments"><span itemprop="reviewCount">0</span> Review(s)</span>
				</div><p class="product-desc">
					Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec convallis sem mauris facilisis, eros ut iaculis suscipit sollicitudin dignissim nunc
				</p><div class="right-block"><div class="right-block-content row"><div class="content_price col-xs-5 col-md-12">
									<span itemprop="price" class="price product-price">
						$250.00					</span>
							<meta itemprop="priceCurrency" content="USD">


						</div></div><div class="product-flags">
					</div><span class="availability">
											<span class="available-now">
							<link itemprop="availability" href="">In stock						</span>
									</span><div class="product_bottom">
						<a class="quick-view" href="#" rel="">
							<i class="fa fa-plus"></i>
							Quick View
						</a>
					</div></div></div></div></div></div>

</div>
<!-- Products list -->
<div class="product_list grid row">




<div class="ajax_block_product col-sp-12 col-sm-12 col-md-3 first-in-line     last-item-of-tablet-line      last-item-of-mobile-line col-xs-12"><div class="product-container"><div class="left-block">
			<div class="product-image-container">
				<div class="leo-more-info" data-idproduct="8"><div class="col-1">
						<!-- thumbnails -->
						<div class="views_block">
							<div class="thumbs_list thumbs_list_8">
								<ul class="thumbs_list_frame">
									<li>
										<a href="" rel="other-views" class="thickbox-ajax-8 shown" title="Donec magna diam">
											<img src="images/155-medium_default.jpg" alt="Donec magna diam" rel="" class="leo-hover-image" height="125" width="125">
										</a>
									</li>
									<li>
										<a href="" rel="other-views" class="thickbox-ajax-8" title="Donec magna diam">
											<img src="images/154-medium_default.jpg" alt="Donec magna diam" rel="" class="leo-hover-image" height="125" width="125">
										</a>
									</li>
								</ul>
							</div>
						</div>
					</div></div>
				<a class="product_img_link" href="" title="Vivamus condimentum" itemprop="url">
					<img class="replace-2x img-responsive" src="images/154-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
					<span class="product-additional" data-idproduct="8"><img class="img-responsive" title="" alt="" src="images/155-home_default.jpg"></span>
				</a>

							<span class="new-box">
					<span class="new-label product-label">New</span>
				</span>
			</div>


			<div class="functional-buttons  clearfix">
				<div class="button-container">
					<a class="button ajax_add_to_cart_button btn btn-default" href="" rel="nofollow" title="Add to cart" data-id-product="8">
						<i class="fa fa-shopping-cart"></i>
						Add to cart
					</a>
				</div>



				<div class="wishlist">
					<a class="addToWishlist btn wishlistProd_8" title="Wishlist" href="" rel="8" onclick="">

					</a>
				</div>


				<div class="compare">
					<a class="add_to_compare btn" href="" data-id-product="8">
						<!--Add to Compare--></a>
				</div>
			</div>

		</div><div class="right-block"><h5 itemprop="name">
				<a class="product-name" href="" title="Vivamus condimentum" itemprop="url">
					Vivamus condimentum
				</a>
			</h5><p itemprop="description" class="product-desc">
				Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec convallis sem mauris facilisis, eros ut iaculis suscipit sollicitudin dignissim nunc
			</p><div class="content_price">
									<span itemprop="price" class="price product-price">
						$250.00					</span>
				<meta itemprop="priceCurrency" content="USD">


			</div><span class="availability">
											<span class="available-now">
							<link itemprop="availability" href="">In stock						</span>
									</span><div itemprop="aggregateRating" itemscope="" class="comments_note">
				<div class="star_content clearfix">
					<div class="star"></div>
					<div class="star"></div>
					<div class="star"></div>
					<div class="star"></div>
					<div class="star"></div>
					<meta itemprop="worstRating" content="0">
					<meta itemprop="ratingValue" content="0">
					<meta itemprop="bestRating" content="5">
				</div>
				<span class="nb-comments"><span itemprop="reviewCount">0</span> Review(s)</span>
			</div></div><div class="product-flags">
		</div><div class="product_bottom">
			<a class="quick-view" href="" rel="">
				<i class="fa fa-plus"></i>
				Quick View
			</a>
		</div></div></div>





<div class="ajax_block_product col-sp-12 col-sm-12 col-md-3     last-item-of-tablet-line      last-item-of-mobile-line col-xs-12"><div class="product-container"><div class="left-block">
			<div class="product-image-container">
				<div class="leo-more-info" data-idproduct="9"><div class="col-1">
						<!-- thumbnails -->
						<div class="views_block">
							<div class="thumbs_list thumbs_list_9">
								<ul class="thumbs_list_frame">
									<li>
										<a href="" rel="other-views" class="thickbox-ajax-9 shown" title="Donec magna diam">
											<img src="images/157-medium_default.jpg" alt="Donec magna diam" rel="" class="leo-hover-image" height="125" width="125">
										</a>
									</li>
									<li>
										<a href="" rel="other-views" class="thickbox-ajax-9" title="Donec magna diam">
											<img src="images/156-medium_default.jpg" alt="Donec magna diam" rel="" class="leo-hover-image" height="125" width="125">
										</a>
									</li>
								</ul>
							</div>
						</div>
					</div></div>
				<a class="product_img_link" href="" title="Donec posuere metus" itemprop="url">
					<img class="replace-2x img-responsive" src="images/156-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
					<span class="product-additional" data-idproduct="9"><img class="img-responsive" title="" alt="" src="images/157-home_default.jpg"></span>
				</a>

							<span class="new-box">
					<span class="new-label product-label">New</span>
				</span>
			</div>


			<div class="functional-buttons  clearfix">
				<div class="button-container">
					<a class="button ajax_add_to_cart_button btn btn-default" href="" rel="nofollow" title="Add to cart" data-id-product="9">
						<i class="fa fa-shopping-cart"></i>
						Add to cart
					</a>
				</div>



				<div class="wishlist">
					<a class="addToWishlist btn wishlistProd_9" title="Wishlist" href="" rel="9" onclick="">

					</a>
				</div>


				<div class="compare">
					<a class="add_to_compare btn" href="" data-id-product="9">
						<!--Add to Compare--></a>
				</div>
			</div>

		</div><div class="right-block"><h5 itemprop="name">
				<a class="product-name" href="" title="Donec posuere metus" itemprop="url">
					Donec posuere metus
				</a>
			</h5><p itemprop="description" class="product-desc">
				Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec convallis sem mauris facilisis, eros ut iaculis suscipit sollicitudin dignissim nunc
			</p><div class="content_price">
									<span itemprop="price" class="price product-price">
						$350.00					</span>
				<meta itemprop="priceCurrency" content="USD">


			</div><span class="availability">
											<span class="available-now">
							<link itemprop="availability" href="">In stock						</span>
									</span><div itemprop="aggregateRating" itemscope="" class="comments_note">
				<div class="star_content clearfix">
					<div class="star"></div>
					<div class="star"></div>
					<div class="star"></div>
					<div class="star"></div>
					<div class="star"></div>
					<meta itemprop="worstRating" content="0">
					<meta itemprop="ratingValue" content="0">
					<meta itemprop="bestRating" content="5">
				</div>
				<span class="nb-comments"><span itemprop="reviewCount">0</span> Review(s)</span>
			</div></div><div class="product-flags">
		</div><div class="product_bottom">
			<a class="quick-view" href="" rel="">
				<i class="fa fa-plus"></i>
				Quick View
			</a>
		</div></div></div>





<div class="ajax_block_product col-sp-12 col-sm-12 col-md-3     last-item-of-tablet-line      last-item-of-mobile-line col-xs-12"><div class="product-container"><div class="left-block">
			<div class="product-image-container">
				<div class="leo-more-info" data-idproduct="10"><div class="col-1">
						<!-- thumbnails -->
						<div class="views_block">
							<div class="thumbs_list thumbs_list_10">
								<ul class="thumbs_list_frame">
									<li>
										<a href="" rel="other-views" class="thickbox-ajax-10 shown" title="Donec magna diam">
											<img src="images/159-medium_default.jpg" alt="Donec magna diam" rel="" class="leo-hover-image" height="125" width="125">
										</a>
									</li>
									<li>
										<a href="" rel="other-views" class="thickbox-ajax-10" title="Donec magna diam">
											<img src="images/158-medium_default.jpg" alt="Donec magna diam" rel="" class="leo-hover-image" height="125" width="125">
										</a>
									</li>
								</ul>
							</div>
						</div>
					</div></div>
				<a class="product_img_link" href="" title="Donec magna diam" itemprop="url">
					<img class="replace-2x img-responsive" src="images/158-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
					<span class="product-additional" data-idproduct="10"><img class="img-responsive" title="" alt="" src="images/159-home_default.jpg"></span>
				</a>

							<span class="new-box">
					<span class="new-label product-label">New</span>
				</span>
			</div>


			<div class="functional-buttons  clearfix">
				<div class="button-container">
					<a class="button ajax_add_to_cart_button btn btn-default" href="" rel="nofollow" title="Add to cart" data-id-product="10">
						<i class="fa fa-shopping-cart"></i>
						Add to cart
					</a>
				</div>



				<div class="wishlist">
					<a class="addToWishlist btn wishlistProd_10" title="Wishlist" href="" rel="10" onclick="">

					</a>
				</div>


				<div class="compare">
					<a class="add_to_compare btn" href="" data-id-product="10">
						<!--Add to Compare--></a>
				</div>
			</div>

		</div><div class="right-block"><h5 itemprop="name">
				<a class="product-name" href="" title="Donec magna diam" itemprop="url">
					Donec magna diam
				</a>
			</h5><p itemprop="description" class="product-desc">
				Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec convallis sem mauris facilisis, eros ut iaculis suscipit sollicitudin dignissim nunc
			</p><div class="content_price">
									<span itemprop="price" class="price product-price">
						$350.00					</span>
				<meta itemprop="priceCurrency" content="USD">


			</div><span class="availability">
											<span class="available-now">
							<link itemprop="availability" href="">In stock						</span>
									</span><div itemprop="aggregateRating" itemscope="" class="comments_note">
				<div class="star_content clearfix">
					<div class="star"></div>
					<div class="star"></div>
					<div class="star"></div>
					<div class="star"></div>
					<div class="star"></div>
					<meta itemprop="worstRating" content="0">
					<meta itemprop="ratingValue" content="0">
					<meta itemprop="bestRating" content="5">
				</div>
				<span class="nb-comments"><span itemprop="reviewCount">0</span> Review(s)</span>
			</div></div><div class="product-flags">
		</div><div class="product_bottom">
			<a class="quick-view" href="" rel="">
				<i class="fa fa-plus"></i>
				Quick View
			</a>
		</div></div></div>





<div class="ajax_block_product col-sp-12 col-sm-12 col-md-3 last-in-line        last-item-of-tablet-line      last-item-of-mobile-line col-xs-12"><div class="product-container"><div class="left-block">
			<div class="product-image-container">
				<div class="leo-more-info" data-idproduct="11"><div class="col-1">
						<!-- thumbnails -->
						<div class="views_block">
							<div class="thumbs_list thumbs_list_11">
								<ul class="thumbs_list_frame">
									<li>
										<a href="" rel="other-views" class="thickbox-ajax-11 shown" title="Donec magna diam">
											<img src="images/177-medium_default.jpg" alt="Donec magna diam" rel="" class="leo-hover-image" height="125" width="125">
										</a>
									</li>
									<li>
										<a href="" rel="other-views" class="thickbox-ajax-11" title="Donec magna diam">
											<img src="images/176-medium_default.jpg" alt="Donec magna diam" rel="" class="leo-hover-image" height="125" width="125">
										</a>
									</li>
								</ul>
							</div>
						</div>
					</div></div>
				<a class="product_img_link" href="" title="Aenean" itemprop="url">
					<img class="replace-2x img-responsive" src="images/176-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
					<span class="product-additional" data-idproduct="11"><img class="img-responsive" title="" alt="" src="images/177-home_default.jpg"></span>
				</a>

							<span class="new-box">
					<span class="new-label product-label">New</span>
				</span>
			</div>


			<div class="functional-buttons  clearfix">
				<div class="button-container">
					<a class="button ajax_add_to_cart_button btn btn-default" href="" rel="nofollow" title="Add to cart" data-id-product="11">
						<i class="fa fa-shopping-cart"></i>
						Add to cart
					</a>
				</div>



				<div class="wishlist">
					<a class="addToWishlist btn wishlistProd_11" title="Wishlist" href="" rel="11" onclick="">

					</a>
				</div>


				<div class="compare">
					<a class="add_to_compare btn" href="" data-id-product="11">
						<!--Add to Compare--></a>
				</div>
			</div>

		</div><div class="right-block"><h5 itemprop="name">
				<a class="product-name" href="" title="Aenean" itemprop="url">
					Aenean
				</a>
			</h5><p itemprop="description" class="product-desc">
				Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec convallis sem mauris facilisis, eros ut iaculis suscipit sollicitudin dignissim nunc
			</p><div class="content_price">
									<span itemprop="price" class="price product-price">
						$450.00					</span>
				<meta itemprop="priceCurrency" content="USD">


			</div><span class="availability">
											<span class="available-now">
							<link itemprop="availability" href="">In stock						</span>
									</span><div itemprop="aggregateRating" itemscope="" class="comments_note">
				<div class="star_content clearfix">
					<div class="star"></div>
					<div class="star"></div>
					<div class="star"></div>
					<div class="star"></div>
					<div class="star"></div>
					<meta itemprop="worstRating" content="0">
					<meta itemprop="ratingValue" content="0">
					<meta itemprop="bestRating" content="5">
				</div>
				<span class="nb-comments"><span itemprop="reviewCount">0</span> Review(s)</span>
			</div></div><div class="product-flags">
		</div><div class="product_bottom">
			<a class="quick-view" href="" rel="">
				<i class="fa fa-plus"></i>
				Quick View
			</a>
		</div></div></div>





<div class="ajax_block_product col-sp-12 col-sm-12 col-md-3 first-in-line   last-line   last-item-of-tablet-line      last-item-of-mobile-line col-xs-12"><div class="product-container"><div class="left-block">
			<div class="product-image-container">
				<div class="leo-more-info" data-idproduct="12"><div class="col-1">
						<!-- thumbnails -->
						<div class="views_block">
							<div class="thumbs_list thumbs_list_12">
								<ul class="thumbs_list_frame">
									<li>
										<a href="" rel="other-views" class="thickbox-ajax-12 shown" title="Donec magna diam">
											<img src="images/183-medium_default.jpg" alt="Donec magna diam" rel="" class="leo-hover-image" height="125" width="125">
										</a>
									</li>
									<li>
										<a href="" rel="other-views" class="thickbox-ajax-12" title="Donec magna diam">
											<img src="images/182-medium_default.jpg" alt="Donec magna diam" rel="" class="leo-hover-image" height="125" width="125">
										</a>
									</li>
								</ul>
							</div>
						</div>
					</div></div>
				<a class="product_img_link" href="" title="Morbi vitae cons" itemprop="url">
					<img class="replace-2x img-responsive" src="images/182-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
					<span class="product-additional" data-idproduct="12"><img class="img-responsive" title="" alt="" src="images/183-home_default.jpg"></span>
				</a>

							<span class="new-box">
					<span class="new-label product-label">New</span>
				</span>
			</div>


			<div class="functional-buttons  clearfix">
				<div class="button-container">
					<a class="button ajax_add_to_cart_button btn btn-default" href="" rel="nofollow" title="Add to cart" data-id-product="12">
						<i class="fa fa-shopping-cart"></i>
						Add to cart
					</a>
				</div>



				<div class="wishlist">
					<a class="addToWishlist btn wishlistProd_12" title="Wishlist" href="" rel="12" onclick="">

					</a>
				</div>


				<div class="compare">
					<a class="add_to_compare btn" href="" data-id-product="12">
						<!--Add to Compare--></a>
				</div>
			</div>

		</div><div class="right-block"><h5 itemprop="name">
				<a class="product-name" href="" title="Morbi vitae cons" itemprop="url">
					Morbi vitae cons
				</a>
			</h5><p itemprop="description" class="product-desc">
				Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec convallis sem mauris facilisis, eros ut iaculis suscipit sollicitudin dignissim nunc
			</p><div class="content_price">
									<span itemprop="price" class="price product-price">
						$300.00					</span>
				<meta itemprop="priceCurrency" content="USD">


			</div><span class="availability">
											<span class="available-now">
							<link itemprop="availability" href="">In stock						</span>
									</span><div itemprop="aggregateRating" itemscope="" class="comments_note">
				<div class="star_content clearfix">
					<div class="star"></div>
					<div class="star"></div>
					<div class="star"></div>
					<div class="star"></div>
					<div class="star"></div>
					<meta itemprop="worstRating" content="0">
					<meta itemprop="ratingValue" content="0">
					<meta itemprop="bestRating" content="5">
				</div>
				<span class="nb-comments"><span itemprop="reviewCount">0</span> Review(s)</span>
			</div></div><div class="product-flags">
		</div><div class="product_bottom">
			<a class="quick-view" href="" rel="">
				<i class="fa fa-plus"></i>
				Quick View
			</a>
		</div></div></div>





<div class="ajax_block_product col-sp-12 col-sm-12 col-md-3   last-line   last-item-of-tablet-line      last-item-of-mobile-line      last-mobile-line col-xs-12"><div class="product-container"><div class="left-block">
			<div class="product-image-container">
				<div class="leo-more-info" data-idproduct="14"><div class="col-1">
						<!-- thumbnails -->
						<div class="views_block">
							<div class="thumbs_list thumbs_list_14">
								<ul class="thumbs_list_frame">
									<li>
										<a href="" rel="other-views" class="thickbox-ajax-14 shown" title="Donec magna diam">
											<img src="images/181-medium_default.jpg" alt="Donec magna diam" rel="" class="leo-hover-image" height="125" width="125">
										</a>
									</li>
									<li>
										<a href="" rel="other-views" class="thickbox-ajax-14" title="Donec magna diam">
											<img src="images/180-medium_default.jpg" alt="Donec magna diam" rel="" class="leo-hover-image" height="125" width="125">
										</a>
									</li>
								</ul>
							</div>
						</div>
					</div></div>
				<a class="product_img_link" href="" title="Morbi vitae cons" itemprop="url">
					<img class="replace-2x img-responsive" src="images/180-home_default.jpg" alt="Donec magna diam" title="Donec magna diam" itemprop="image">
					<span class="product-additional" data-idproduct="14"><img class="img-responsive" title="" alt="" src="images/181-home_default.jpg"></span>
				</a>

							<span class="new-box">
					<span class="new-label product-label">New</span>
				</span>
			</div>


			<div class="functional-buttons  clearfix">
				<div class="button-container">
					<a class="button ajax_add_to_cart_button btn btn-default" href="" rel="nofollow" title="Add to cart" data-id-product="14">
						<i class="fa fa-shopping-cart"></i>
						Add to cart
					</a>
				</div>



				<div class="wishlist">
					<a class="addToWishlist btn wishlistProd_14" title="Wishlist" href="" rel="14" onclick="">

					</a>
				</div>


				<div class="compare">
					<a class="add_to_compare btn" href="" data-id-product="14">
						<!--Add to Compare--></a>
				</div>
			</div>

		</div><div class="right-block"><h5 itemprop="name">
				<a class="product-name" href="" title="Morbi vitae cons" itemprop="url">
					Morbi vitae cons
				</a>
			</h5><p itemprop="description" class="product-desc">
				Lorem psum dolor aet cosctetur aipiscing elit nunc aiquet varius curabitur lorem masa ultricies nec convallis sem mauris facilisis, eros ut iaculis suscipit sollicitudin dignissim nunc
			</p><div class="content_price">
									<span itemprop="price" class="price product-price">
						$250.00					</span>
				<meta itemprop="priceCurrency" content="USD">


			</div><span class="availability">
											<span class="available-now">
							<link itemprop="availability" href="">In stock						</span>
									</span><div itemprop="aggregateRating" itemscope="" class="comments_note">
				<div class="star_content clearfix">
					<div class="star"></div>
					<div class="star"></div>
					<div class="star"></div>
					<div class="star"></div>
					<div class="star"></div>
					<meta itemprop="worstRating" content="0">
					<meta itemprop="ratingValue" content="0">
					<meta itemprop="bestRating" content="5">
				</div>
				<span class="nb-comments"><span itemprop="reviewCount">0</span> Review(s)</span>
			</div></div><div class="product-flags">
		</div><div class="product_bottom">
			<a class="quick-view" href="" rel="">
				<i class="fa fa-plus"></i>
				Quick View
			</a>
		</div></div></div>

</div>





<div class="content_sortPagiBar">
	<div class="bottom-pagination-content clearfix">
		<form method="post" action="" class="compare-form">
			<button type="submit" class="btn btn-default button button-medium bt_compare bt_compare_bottom" disabled="disabled">
				<span>Compare (<strong class="total-compare-val">0</strong>)<i class="icon-chevron-right right"></i></span>
			</button>
			<input name="compare_product_count" class="compare_product_count" value="0" type="hidden">
			<input name="compare_product_list" class="compare_product_list" value="" type="hidden">
		</form>



		<!-- Pagination -->
		<div id="pagination_bottom" class="pagination clearfix">
			<form class="showall" action="" method="get">
				<div>
					<button type="submit" class="btn btn-default button exclusive-medium">
						<span>Show all</span>
					</button>
					<input name="id_lang" value="1" type="hidden">
					<input name="id_category" value="12" type="hidden">
					<input name="controller" value="category" type="hidden">
					<input name="n" id="nb_item" class="hidden" value="12">
				</div>
			</form>
			<ul class="pagination">
				<li id="pagination_previous_bottom" class="disabled pagination_previous">
						<span>
							<i class="icon-chevron-left"></i> <b>Previous</b>
						</span>
				</li>
				<li class="active current">
							<span>
								<span>1</span>
							</span>
				</li>
				<li>
					<a href="">
						<span>2</span>
					</a>
				</li>
				<li id="pagination_next_bottom" class="pagination_next">
					<a href="">
						<b>Next</b> <i class="icon-chevron-right"></i>
					</a>
				</li>
			</ul>
		</div>
		<div class="product-count">
			Showing 1 - 6 of 12 items
		</div>
		<!-- /Pagination -->

	</div>
</div>
</section>