<?php use Phalcon\Tag as Tag; ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <link rel="shortcut icon" href="favicon.ico" />
        <?php 
        	echo Tag::getTitle();
        	echo Tag::stylesheetLink('http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css');
        	echo Tag::stylesheetLink('http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css');
        ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <?php 
            echo $this->getContent();
        	echo Tag::javascriptInclude('http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js');
        	echo Tag::javascriptInclude('http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js');
        ?>
    </body>
</html>