<!-- Корзина покупок -->
<div class="column main-column">
	<div id="CONTENT">
		<h1><?=$title;?></h1>
		<?php if(!empty($breadcrumbs)): ?>
			<!-- Bread Crumbs -->
			<ul class="Thermo">
				<?php foreach($breadcrumbs as $crumb): ?>
					<li>
						<?=($crumb['active']) ? $crumb['text'] : $this->tag->linkTo($crumb['link'], $crumb['text']).' / '; ?>
					</li>
				<?php endforeach; ?>
			</ul>
			<!-- Bread Crumbs -->
		<?php endif; ?>
			<div class="clear"></div>
			<div class="_cart" id="SHOPPING_CART">
				<div class="hr"></div>
				<?php if(isset($basket) && !empty($basket)): ?>
					<?php if(isset($basket['items'])): ?>
						<!-- Выдача в корзине -->
							<?php $this->view->partial('partials/basket/big', ['items' => $basket['items'], 'informer' => (isset($basket['informer'])) ? $basket['informer'] : []]); ?>
						<!-- /Выдача в корзине -->
					<?php endif;?>
				<?php else: ?>
					<h2 class="basket"><?=$viewTranslate['BASKET_EMPTY'];?></h2>
					<div style="padding: 10 0 20 0;">
						<?=$viewTranslate['VISIT_CATALOGUE'];?> <?=$this->tag->linkTo([['for' => 'catalogue'], $viewTranslate['CATALOGUE']]); ?>
					</div>
				<?php endif; ?>
			</div>
	</div>
</div>
<!-- Корзина покупок -->