<?php use Phalcon\Tag as Tag; ?>
<div class="navbar">
	<div class="navbar-inner">
		<div class="container">
			<?php echo Tag::image(array('img/logo.png', 'width' => 80)) ?> <h1 class="logo-text"><?php echo $layoutTranslate['TITLE'] ?></h1>
			<form action="/" method="post" class="navbar-search pull-right">
				<input type="text" name="pattern" class="search-query" placeholder="<?php echo $layoutTranslate['SEARCH_FOR'] ?>">
			</form>
		</div>
	</div>
	<div class="navbar-inner navbar-menu">
		<nav>
			<!-- Меню навигации -->
			<?php //echo UIElements::getMenu($this, $layoutTranslate) ?>
			<!-- Меню навигации -->
		</nav>
	</div>
</div>

<div class="container">
	<!-- Выдача контента -->
	<?php echo $this->getContent() ?>
	<!-- Выдача контента -->
	<hr>
</div>

<footer>
	<div class="copyright">
		<?php echo Tag::linkTo("copyright", "Copyright © 2014 Stanislav WEB") ?>
	</div>
	<div class="language">
		<?php echo $layoutTranslate['CHANGE_LANGUE'] ?>: <?php echo Tag::linkTo("language/en", "English") ?>  | <?php echo Tag::linkTo("language/ru", "Русский") ?>
	</div>
</footer>