<?php use Phalcon\Tag as Tag; ?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<link rel="shortcut icon" href="/assets/<?=$shop['code'];?>/images/favicon.png"/>

		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
		<?php
			echo $this->tag->getTitle();
			echo $this->tag->stylesheetLink('assets/' . $shop['code'] . '/css/main.css');
		?>
		<?php
			echo $this->tag->javascriptInclude('assets/' . $shop['code'] . '/js/jquery-1.11.0.min.js');
			echo $this->tag->javascriptInclude('assets/' . $shop['code'] . '/js/main.js');
			echo $this->tag->javascriptInclude('assets/cart.js');
			echo $this->tag->javascriptInclude('assets/common.js');
		?>
		<!--[if IE]>
		<style type="text/css">
			BODY { behavior:url("/assets/<?=$shop['code'];?>/css/csshover3.htc"); }
		</style>
		<![endif]-->
	</head>
	<body onload="global.init();">

	<!-- Блоки окон и сообщений -->
	<div class="basket-container">
		<div class="Shadow" id="small-cart"></div>
	</div>

	<div class="status common loading"><div class="message">Секундочку...</div></div>
	<div class="status timeout" onclick="global.hideStatus('timeout');">
			<div class="message">
				<div class="title">Мы не дождались ответа от сервера</div>
				Попробуйте еще раз			</div>
	</div>
<div class="status server error" onclick="global.hideStatus('server.error');">
	<div class="message">
		<div class="title">На сервере случилась ошибка</div>
		Благодаря вам мы уже узнали о проблеме и сразу ею займемся.			</div>
</div>
<div class="status order success" onclick="global.hideStatus('order.success');">
	<div class="message">
		<div class="title">Заказ создан</div>
		<span class="body"></span>
	</div>
</div>
<div class="status order error" onclick="global.hideStatus('order.error');">
	<div class="message">
		<div class="title">Заказ не создан</div>
		<span class="body"></span>
	</div>
</div>
<div class="dialog dialog_black status coupon success" onclick="global.hideStatus('coupon.success');">
	<div class="message">
		<div class="title">Купон отправлен по почте</div>
		<span class="body"></span>
	</div>
</div>
<div class="dialog dialog_black status coupon error" onclick="global.hideStatus('coupon.error');">
	<div class="message">
		<div class="title">Не получилось выдать купон</div>
		<span class="body"></span>
	</div>
</div>
<div class="status password success" onclick="global.hideStatus('password.success');">
	<div class="message">
		<div class="title">Пароль отправлен</div>
		<span class="body"></span>
	</div>
</div>
<div class="status message success" onclick="global.hideStatus('message.success');">
	<div class="message">
		<div class="title">Отправка</div>
		<span class="body"></span>
	</div>
</div>
<div class="status password error" onclick="global.hideStatus('password.error');">
	<div class="message">
		<div class="title">Пароль не отправлен</div>
		<span class="body"></span>
	</div>
</div>
<div class="status customer error" onclick="global.hideStatus('customer.error');">
	<div class="message">
		<div class="title">Неправильная пара логин/пароль</div>
		<span class="body"></span>
	</div>
</div>

<div class="go-top-container">
	<div class="go-top-field">
		<div class="button-down"></div>
		<div class="button-top">Наверх</div>
	</div>
</div>
<div class="go-container prev">
	<div class="button"></div>
</div>
<div class="go-container next">
	<div class="button"></div>
</div>
	<!-- Hotline -->
	<?php $this->partial('partials/hotline'); ?>
	<!-- Hotline -->

	<!-- Header -->
	<?php $this->partial('partials/header'); ?>
	<!-- Header -->
	<!-- Top Navigation -->
		<?php $this->partial('partials/topnav'); ?>
	<!-- /Top Navigation -->
	<div class="content">
		<?php echo $this->getContent(); ?>
	</div>

</td>
</tr>
	<!-- Footer -->
		<?php $this->partial('partials/footer'); ?>
	<!-- Footer -->

</table>
<script type="text/javascript" language="javascript">
	global.drawTopLine();
</script>
<script type="text/javascript">
	var margin = Math.max(0,parseInt((($(window).width() - $('.page_container').width())*0.5 - $('.go-container').width())*0.5));
</script>
</body>
</html>